# AWS CloudFormation Linter Configuration
# AWS-DRS-Orchestration

ignore_checks:
  # Warnings
  - W2001  # Parameter not used - common in reusable templates
  - W3002  # Hardcoded path - acceptable for this project
  - W3005  # DependsOn may not be necessary - architectural choice
  - W3037  # Duplicate resource - false positives with nested stacks
  - W8001  # Condition not used - conditions may be for future use
  
  # Informational
  - I3011  # DeletionPolicy/UpdateReplacePolicy not set - using defaults intentionally
  - I3042  # Hardcoded partition in ARN - acceptable for standard AWS partition

ignore_templates:
  - cfn/security-stack.yaml  # Optional stack, may have conditional resources

regions:
  - us-east-1
  - us-west-2
