version: 0.2

env:
  variables:
    PROJECT_NAME: "aws-elasticdrs-orchestrator"
    ENVIRONMENT: "dev"
    DEPLOYMENT_BUCKET: "aws-elasticdrs-orchestrator"

phases:
  install:
    runtime-versions:
      python: 3.12
      nodejs: 18
    commands:
      - echo "Installing build dependencies..."
      - pip install --upgrade pip
      - pip install boto3 crhelper

  pre_build:
    commands:
      - echo "=== BUILD PHASE STARTED ==="
      - echo "Project $PROJECT_NAME"
      - echo "Environment $ENVIRONMENT"
      - echo "Deployment Bucket $DEPLOYMENT_BUCKET"

  build:
    commands:
      - echo "=== Building Lambda Packages ==="
      - cd lambda
      - echo "Creating Lambda deployment packages..."
      - cd ..
      - echo "Lambda packages built successfully"
      - echo "=== Building Frontend Application ==="
      - echo "Checking for frontend..."
      - echo "=== Uploading Build Artifacts to S3 ==="
      - echo "Uploading Lambda packages..."
      - aws s3 sync lambda/ s3://$DEPLOYMENT_BUCKET/lambda/ --exclude "*" --include "*.zip" --delete
      - echo "Uploading CloudFormation templates..."
      - aws s3 sync cfn/ s3://$DEPLOYMENT_BUCKET/cfn/ --exclude "*.md" --delete
      - echo "Uploading BuildSpec files..."
      - aws s3 sync buildspecs/ s3://$DEPLOYMENT_BUCKET/buildspecs/ --delete
      - echo "Uploading scripts..."
      - aws s3 sync scripts/ s3://$DEPLOYMENT_BUCKET/scripts/ --exclude "*.md" --delete

  post_build:
    commands:
      - echo "=== BUILD PHASE COMPLETED ==="
      - echo "Build completed successfully"
      - echo "Artifacts uploaded to s3://$DEPLOYMENT_BUCKET/"

artifacts:
  files:
    - '**/*'
  name: BuiltArtifacts

cache:
  paths:
    - '/root/.cache/pip/**/*'
    - 'frontend/node_modules/**/*'
    - '/root/.npm/**/*'