version: 0.2

env:
  variables:
    PROJECT_NAME: "aws-elasticdrs-orchestrator"
    ENVIRONMENT: "dev"
    DEPLOYMENT_BUCKET: "aws-elasticdrs-orchestrator"
    STACK_NAME: "aws-elasticdrs-orchestrator-dev"
    ADMIN_EMAIL: "admin@example.com"

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing deployment tools..."
      - pip install --upgrade pip
      - pip install boto3 awscli

  pre_build:
    commands:
      - echo "=== INFRASTRUCTURE DEPLOYMENT PHASE STARTED ==="
      - echo "Project $PROJECT_NAME"
      - echo "Environment $ENVIRONMENT"
      - echo "Stack Name $STACK_NAME"
      - echo "Deployment Bucket $DEPLOYMENT_BUCKET"
      - echo "Admin Email $ADMIN_EMAIL"
      - echo "Build ID $CODEBUILD_BUILD_ID"
      - echo "Source Version $CODEBUILD_SOURCE_VERSION"
      - echo "AWS Region $AWS_DEFAULT_REGION"
      - echo "=== Pre-deployment Validation ==="
      - echo "Checking if deployment bucket exists..."
      - aws s3 ls s3://$DEPLOYMENT_BUCKET/ > /dev/null || (echo "Deployment bucket not found" && exit 1)
      - echo "Deployment bucket accessible"
      - echo "Validating master template..."
      - aws cloudformation validate-template --template-body file://cfn/master-template.yaml > /dev/null
      - echo "Master template is valid"

  build:
    commands:
      - echo "=== CloudFormation Stack Deployment ==="
      - echo "Checking if stack exists..."
      - aws cloudformation describe-stacks --stack-name $STACK_NAME > /dev/null 2>&1 && echo "Stack exists - will update" || echo "Stack does not exist - will create"
      - echo "Deploying CloudFormation stack..."
      - aws cloudformation deploy --template-file cfn/master-template.yaml --stack-name $STACK_NAME --parameter-overrides ProjectName=$PROJECT_NAME Environment=$ENVIRONMENT SourceBucket=$DEPLOYMENT_BUCKET AdminEmail=$ADMIN_EMAIL EnableAutomatedDeployment=false GitHubRepositoryURL=https://github.com/johnjcousens/aws-elasticdrs-orchestrator --capabilities CAPABILITY_NAMED_IAM --tags Project=$PROJECT_NAME Environment=$ENVIRONMENT DeployedBy=CodePipeline BuildId=$CODEBUILD_BUILD_ID --no-fail-on-empty-changeset
      - echo "=== Deployment Verification ==="
      - echo "Retrieving stack outputs..."
      - aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs[].{Key:OutputKey,Value:OutputValue}' --output table
      - echo "Extracting key outputs..."
      - export API_ENDPOINT=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs[?OutputKey==`ApiEndpoint`].OutputValue' --output text)
      - export CLOUDFRONT_URL=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs[?OutputKey==`CloudFrontUrl`].OutputValue' --output text)
      - export USER_POOL_ID=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs[?OutputKey==`UserPoolId`].OutputValue' --output text)
      - echo "API Endpoint is $API_ENDPOINT"
      - echo "CloudFront URL is $CLOUDFRONT_URL"
      - echo "User Pool ID is $USER_POOL_ID"
      - test -n "$API_ENDPOINT" && test "$API_ENDPOINT" != "None" && echo "API Gateway deployed successfully" || (echo "API Gateway deployment failed" && exit 1)
      - test -n "$USER_POOL_ID" && test "$USER_POOL_ID" != "None" && echo "Cognito User Pool deployed successfully" || (echo "Cognito User Pool deployment failed" && exit 1)
      - echo "=== Post-Deployment Configuration ==="
      - echo "Creating deployment info file..."
      - echo "{\"stack_name\":\"$STACK_NAME\",\"api_endpoint\":\"$API_ENDPOINT\",\"cloudfront_url\":\"$CLOUDFRONT_URL\",\"user_pool_id\":\"$USER_POOL_ID\",\"deployment_timestamp\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\",\"build_id\":\"$CODEBUILD_BUILD_ID\",\"source_version\":\"$CODEBUILD_SOURCE_VERSION\"}" > deployment-info.json
      - echo "Deployment info saved to deployment-info.json"

  post_build:
    commands:
      - echo "=== INFRASTRUCTURE DEPLOYMENT PHASE COMPLETED ==="
      - echo "Checking build status..."
      - test $CODEBUILD_BUILD_SUCCEEDING -eq 1 && echo "Infrastructure deployment completed successfully" || echo "Infrastructure deployment failed"
      - echo "Stack Name is $STACK_NAME"
      - echo "API Endpoint is $API_ENDPOINT"
      - echo "CloudFront URL is $CLOUDFRONT_URL"
      - test $CODEBUILD_BUILD_SUCCEEDING -eq 1 && aws s3 cp deployment-info.json s3://$DEPLOYMENT_BUCKET/deployment-info/$CODEBUILD_BUILD_ID/ && echo "Deployment info uploaded to S3"
      - test $CODEBUILD_BUILD_SUCCEEDING -eq 0 && echo "Recent stack events:" && aws cloudformation describe-stack-events --stack-name $STACK_NAME --query 'StackEvents[0:10].{Time:Timestamp,Status:ResourceStatus,Type:ResourceType,Reason:ResourceStatusReason}' --output table
      - test $CODEBUILD_BUILD_SUCCEEDING -eq 0 && exit 1 || echo "Build completed successfully"

artifacts:
  files:
    - 'deployment-info.json'
    - 'cfn/**/*'
  name: DeploymentArtifacts

cache:
  paths:
    - '/root/.cache/pip/**/*'