version: 0.2

# BuildSpec for Infrastructure Deployment Phase
# Deploys CloudFormation infrastructure using the master template

env:
  variables:
    PROJECT_NAME: "aws-elasticdrs-orchestrator"
    ENVIRONMENT: "dev"
    DEPLOYMENT_BUCKET: "aws-elasticdrs-orchestrator"
    STACK_NAME: "aws-elasticdrs-orchestrator-dev"
    ADMIN_EMAIL: "admin@example.com"

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing deployment tools..."
      - pip install --upgrade pip
      - pip install boto3 awscli

  pre_build:
    commands:
      - echo "=== INFRASTRUCTURE DEPLOYMENT PHASE STARTED ==="
      - echo "Project: $PROJECT_NAME"
      - echo "Environment: $ENVIRONMENT"
      - echo "Stack Name: $STACK_NAME"
      - echo "Deployment Bucket: $DEPLOYMENT_BUCKET"
      - echo "Admin Email: $ADMIN_EMAIL"
      - echo "Build ID: $CODEBUILD_BUILD_ID"
      - echo "Source Version: $CODEBUILD_SOURCE_VERSION"
      - echo "AWS Region: $AWS_DEFAULT_REGION"
      
      - echo "=== Pre-deployment Validation ==="
      - echo "Checking if deployment bucket exists..."
      - aws s3 ls s3://$DEPLOYMENT_BUCKET/ > /dev/null || (echo "❌ Deployment bucket not found" && exit 1)
      - echo "✓ Deployment bucket accessible"
      
      - echo "Validating master template..."
      - aws cloudformation validate-template --template-body file://cfn/master-template.yaml > /dev/null
      - echo "✓ Master template is valid"

  build:
    commands:
      - echo "=== CloudFormation Stack Deployment ==="
      - |
        if aws cloudformation describe-stacks --stack-name $STACK_NAME > /dev/null 2>&1; then
          echo "Stack $STACK_NAME exists - performing update"
          OPERATION="update"
        else
          echo "Stack $STACK_NAME does not exist - performing create"
          OPERATION="create"
        fi
      
      - echo "Creating change set for preview..."
      - |
        CHANGE_SET_NAME="changeset-$(date +%Y%m%d-%H%M%S)"
        aws cloudformation create-change-set --stack-name $STACK_NAME --template-body file://cfn/master-template.yaml --change-set-name $CHANGE_SET_NAME --parameters ParameterKey=ProjectName,ParameterValue=$PROJECT_NAME ParameterKey=Environment,ParameterValue=$ENVIRONMENT ParameterKey=SourceBucket,ParameterValue=$DEPLOYMENT_BUCKET ParameterKey=AdminEmail,ParameterValue=$ADMIN_EMAIL ParameterKey=EnableAutomatedDeployment,ParameterValue=false ParameterKey=GitHubRepositoryURL,ParameterValue=https://github.com/johnjcousens/aws-elasticdrs-orchestrator --capabilities CAPABILITY_NAMED_IAM --tags Key=Project,Value=$PROJECT_NAME Key=Environment,Value=$ENVIRONMENT Key=DeployedBy,Value=CodePipeline Key=BuildId,Value=$CODEBUILD_BUILD_ID
      
      - echo "Waiting for change set creation..."
      - aws cloudformation wait change-set-create-complete --stack-name $STACK_NAME --change-set-name $CHANGE_SET_NAME
      - echo "Describing change set..."
      - aws cloudformation describe-change-set --stack-name $STACK_NAME --change-set-name $CHANGE_SET_NAME --query 'Changes[].{Action:Action,ResourceType:ResourceChange.ResourceType,LogicalId:ResourceChange.LogicalResourceId,Replacement:ResourceChange.Replacement}' --output table
      - echo "Executing change set..."
      - aws cloudformation execute-change-set --stack-name $STACK_NAME --change-set-name $CHANGE_SET_NAME
      - echo "Waiting for stack operation to complete..."
      - |
        if [ "$OPERATION" = "create" ]; then
          aws cloudformation wait stack-create-complete --stack-name $STACK_NAME
        else
          aws cloudformation wait stack-update-complete --stack-name $STACK_NAME
        fi
      
      - echo "=== Deployment Verification ==="
      - echo "Retrieving stack outputs..."
      - aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs[].{Key:OutputKey,Value:OutputValue}' --output table
      - echo "Verifying critical resources..."
      - |
        API_ENDPOINT=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs[?OutputKey==`ApiEndpoint`].OutputValue' --output text)
        CLOUDFRONT_URL=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs[?OutputKey==`CloudFrontUrl`].OutputValue' --output text)
        USER_POOL_ID=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs[?OutputKey==`UserPoolId`].OutputValue' --output text)
        echo "API Endpoint: $API_ENDPOINT"
        echo "CloudFront URL: $CLOUDFRONT_URL"
        echo "User Pool ID: $USER_POOL_ID"
        if [ ! -z "$API_ENDPOINT" ] && [ "$API_ENDPOINT" != "None" ]; then
          echo "✓ API Gateway deployed successfully"
        else
          echo "❌ API Gateway deployment failed"
          exit 1
        fi
        if [ ! -z "$USER_POOL_ID" ] && [ "$USER_POOL_ID" != "None" ]; then
          echo "✓ Cognito User Pool deployed successfully"
        else
          echo "❌ Cognito User Pool deployment failed"
          exit 1
        fi
      
      - echo "=== Post-Deployment Configuration ==="
      - |
        cat > deployment-info.json << EOF
        {
          "stack_name": "$STACK_NAME",
          "api_endpoint": "$API_ENDPOINT",
          "cloudfront_url": "$CLOUDFRONT_URL",
          "user_pool_id": "$USER_POOL_ID",
          "deployment_timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
          "build_id": "$CODEBUILD_BUILD_ID",
          "source_version": "$CODEBUILD_SOURCE_VERSION"
        }
        EOF
        echo "Deployment info saved to deployment-info.json"

  post_build:
    commands:
      - echo "=== INFRASTRUCTURE DEPLOYMENT PHASE COMPLETED ==="
      - |
        if [ $CODEBUILD_BUILD_SUCCEEDING -eq 1 ]; then
          echo "✅ Infrastructure deployment completed successfully"
          echo "Stack Name: $STACK_NAME"
          echo "API Endpoint: $API_ENDPOINT"
          echo "CloudFront URL: $CLOUDFRONT_URL"
          aws s3 cp deployment-info.json s3://$DEPLOYMENT_BUCKET/deployment-info/$CODEBUILD_BUILD_ID/
          echo "Deployment info uploaded to S3"
        else
          echo "❌ Infrastructure deployment failed"
          echo "Recent stack events:"
          aws cloudformation describe-stack-events --stack-name $STACK_NAME --query 'StackEvents[0:10].{Time:Timestamp,Status:ResourceStatus,Type:ResourceType,Reason:ResourceStatusReason}' --output table || echo "Could not retrieve stack events"
          exit 1
        fi

artifacts:
  files:
    - 'deployment-info.json'
    - 'cfn/**/*'
  name: DeploymentArtifacts

cache:
  paths:
    - '/root/.cache/pip/**/*'