version: 0.2

# BuildSpec for Test Phase
# Runs integration tests and end-to-end tests

env:
  variables:
    PROJECT_NAME: "aws-elasticdrs-orchestrator"
    ENVIRONMENT: "dev"
    DEPLOYMENT_BUCKET: "aws-elasticdrs-orchestrator"

phases:
  install:
    runtime-versions:
      python: 3.12
      nodejs: 18
    commands:
      - echo "Installing test dependencies..."
      - pip install --upgrade pip
      - pip install boto3 pytest moto requests pytest-cov
      - pip install pytest-html pytest-json-report
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
      - export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      - nvm install 18 && nvm use 18
      - npm install -g npm@latest

  pre_build:
    commands:
      - echo "=== TEST PHASE STARTED ==="
      - echo "Project: $PROJECT_NAME"
      - echo "Environment: $ENVIRONMENT"
      - echo "Deployment Bucket: $DEPLOYMENT_BUCKET"
      - echo "Build ID: $CODEBUILD_BUILD_ID"
      - echo "Source Version: $CODEBUILD_SOURCE_VERSION"

  build:
    commands:
      - echo "=== Python Integration Tests ==="
      - |
        if [ -d "tests/python/integration" ]; then
          echo "Running Python integration tests..."
          cd tests/python
          python -m pytest integration/ -v --tb=short --cov=../../lambda --cov-report=term-missing --cov-report=html:../../test-reports/coverage-html --html=../../test-reports/integration-report.html --self-contained-html --json-report --json-report-file=../../test-reports/integration-report.json
          cd ../..
          echo "✓ Python integration tests completed"
        else
          echo "⚠️  Integration tests directory not found, skipping..."
        fi
      
      - echo "=== Frontend Tests ==="
      - |
        if [ -f "frontend/package.json" ]; then
          cd frontend
          echo "Installing frontend dependencies..."
          npm ci --silent
          if npm run | grep -q "test"; then
            echo "Running frontend tests..."
            npm run test -- --coverage --watchAll=false
            echo "✓ Frontend tests completed"
          else
            echo "⚠️  No test script found in frontend package.json, skipping..."
          fi
          cd ..
        else
          echo "⚠️  Frontend not found, skipping frontend tests"
        fi
      
      - echo "=== End-to-End Tests ==="
      - |
        if [ -d "tests/e2e" ]; then
          echo "Running end-to-end tests..."
          cd tests/e2e
          if [ -f "package.json" ]; then
            npm ci --silent
            if npm run | grep -q "test:e2e"; then
              npm run test:e2e
              echo "✓ End-to-end tests completed"
            else
              echo "⚠️  No E2E test script found, skipping..."
            fi
          else
            echo "⚠️  E2E tests package.json not found, skipping..."
          fi
          cd ../..
        else
          echo "⚠️  End-to-end tests directory not found, skipping..."
        fi
      
      - echo "=== API Contract Tests ==="
      - |
        if [ -d "tests/contract" ]; then
          echo "Running API contract tests..."
          cd tests/contract
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
            python -m pytest . -v --tb=short
            echo "✓ Contract tests completed"
          else
            echo "⚠️  Contract tests requirements.txt not found, skipping..."
          fi
          cd ../..
        else
          echo "⚠️  Contract tests directory not found, skipping..."
        fi
      
      - echo "=== Security Tests ==="
      - |
        echo "Running security scans..."
        if command -v bandit > /dev/null; then
          echo "Running Bandit security scan on Python code..."
          bandit -r lambda/ -f json -o test-reports/bandit-report.json || echo "⚠️  Bandit scan completed with warnings"
        else
          pip install bandit
          bandit -r lambda/ -f json -o test-reports/bandit-report.json || echo "⚠️  Bandit scan completed with warnings"
        fi
        if [ -f "frontend/package.json" ]; then
          cd frontend
          echo "Running npm audit for frontend security..."
          npm audit --audit-level=high --json > ../test-reports/npm-audit.json || echo "⚠️  npm audit completed with warnings"
          cd ..
        fi
      
      - echo "=== Test Report Generation ==="
      - mkdir -p test-reports
      - |
        echo "Generating test summary..."
        cat > test-reports/test-summary.json << EOF
        {
          "build_id": "$CODEBUILD_BUILD_ID",
          "source_version": "$CODEBUILD_SOURCE_VERSION",
          "project": "$PROJECT_NAME",
          "environment": "$ENVIRONMENT",
          "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
          "test_results": {
            "integration_tests": "$([ -f test-reports/integration-report.json ] && echo 'completed' || echo 'skipped')",
            "frontend_tests": "$([ -d frontend ] && echo 'completed' || echo 'skipped')",
            "e2e_tests": "$([ -d tests/e2e ] && echo 'completed' || echo 'skipped')",
            "contract_tests": "$([ -d tests/contract ] && echo 'completed' || echo 'skipped')",
            "security_scan": "completed"
          }
        }
        EOF

  post_build:
    commands:
      - echo "=== TEST PHASE COMPLETED ==="
      - |
        if [ $CODEBUILD_BUILD_SUCCEEDING -eq 1 ]; then
          echo "✅ All tests completed successfully"
          if [ -d "test-reports" ]; then
            echo "Uploading test reports to S3..."
            aws s3 sync test-reports/ s3://$DEPLOYMENT_BUCKET/test-reports/$CODEBUILD_BUILD_ID/ --exclude "*.pyc"
            echo "Test reports available at: s3://$DEPLOYMENT_BUCKET/test-reports/$CODEBUILD_BUILD_ID/"
          fi
        else
          echo "❌ Tests failed - check the logs above for details"
          if [ -d "test-reports" ]; then
            echo "Uploading test reports for debugging..."
            aws s3 sync test-reports/ s3://$DEPLOYMENT_BUCKET/test-reports/$CODEBUILD_BUILD_ID/ --exclude "*.pyc"
          fi
          exit 1
        fi

artifacts:
  files:
    - 'test-reports/**/*'
  name: TestReports

cache:
  paths:
    - '/root/.cache/pip/**/*'
    - 'frontend/node_modules/**/*'
    - 'tests/e2e/node_modules/**/*'