version: 0.2

env:
  variables:
    PROJECT_NAME: "aws-elasticdrs-orchestrator"
    ENVIRONMENT: "dev"
    DEPLOYMENT_BUCKET: "aws-elasticdrs-orchestrator"

phases:
  install:
    runtime-versions:
      python: 3.12
      nodejs: 18
    commands:
      - echo "Installing test dependencies..."
      - pip install --upgrade pip
      - pip install pytest pytest-cov pytest-html pytest-json-report
      - pip install boto3 moto requests

  pre_build:
    commands:
      - echo "=== TEST PHASE STARTED ==="
      - echo "Project $PROJECT_NAME"
      - echo "Environment $ENVIRONMENT"
      - echo "Deployment Bucket $DEPLOYMENT_BUCKET"
      - echo "Build ID $CODEBUILD_BUILD_ID"
      - echo "Source Version $CODEBUILD_SOURCE_VERSION"

  build:
    commands:
      - echo "=== Python Unit Tests ==="
      - mkdir -p test-reports
      - cd tests/python
      - python -m pytest unit/ -v --tb=short --cov=../../lambda --cov-report=term-missing --cov-report=html:../../test-reports/coverage --junit-xml=../../test-reports/pytest-results.xml
      - cd $CODEBUILD_SRC_DIR
      - echo "=== Frontend Tests ==="
      - cd frontend
      - npm ci --silent
      - npm run type-check
      - npm run lint
      - cd $CODEBUILD_SRC_DIR
      - echo "=== Integration Tests ==="
      - echo "Current directory: $(pwd)"
      - echo "Listing tests directory: $(ls -la tests/)"
      - cd tests/integration
      - pip install pytest boto3 botocore
      - python -m pytest test_basic_integration.py -v --tb=short --junit-xml=../../test-reports/integration-results.xml
      - cd $CODEBUILD_SRC_DIR
      - echo "=== API Contract Tests ==="
      - echo "API contract tests would run here"
      - echo "=== Security Tests ==="
      - echo "Running basic security checks..."
      - pip install bandit safety
      - bandit -r lambda/ -f json -o test-reports/bandit-report.json || true
      - safety check --json --output test-reports/safety-report.json || true
      - echo "=== Test Report Generation ==="
      - echo "Test reports generated in test-reports/ directory"

  post_build:
    commands:
      - echo "=== TEST PHASE COMPLETED ==="
      - if [ $CODEBUILD_BUILD_SUCCEEDING -eq 1 ]; then echo "All tests passed successfully"; else echo "Tests failed - check the logs above for details"; exit 1; fi

artifacts:
  files:
    - 'test-reports/**/*'
  name: TestReports

cache:
  paths:
    - '/root/.cache/pip/**/*'
    - 'frontend/node_modules/**/*'
    - 'tests/e2e/node_modules/**/*'