AWSTemplateFormatVersion: '2010-09-09'
Description: |
  API Gateway Core Stack - Creates the REST API, Cognito authorizer, and
  request validator. Other stacks add resources and methods to this API.

# =============================================================================
# STACK OVERVIEW
# =============================================================================
# This stack creates the foundational API Gateway components that all other
# API stacks depend on. It must be created before resource and method stacks.
#
# Components Created:
# -------------------
# 1. REST API - The API Gateway REST API with regional endpoint
# 2. Cognito Authorizer - Validates JWT tokens from Cognito User Pool
# 3. Request Validator - Validates request body and parameters
# 4. Lambda Permission - Allows API Gateway to invoke the API handler
#
# Stack Dependencies:
# -------------------
# This stack requires:
# - Cognito User Pool (from auth-stack.yaml)
# - API Handler Lambda (from lambda-stack.yaml)
#
# Stacks that depend on this:
# - api-gateway-resources-stack.yaml (creates /path resources)
# - api-gateway-*-methods-stack.yaml (creates HTTP methods)
# - api-gateway-deployment-stack.yaml (deploys the API)
#
# Authentication Flow:
# --------------------
# 1. User authenticates with Cognito and receives JWT token
# 2. Frontend includes token in Authorization header
# 3. API Gateway validates token using Cognito authorizer
# 4. If valid, request proceeds to Lambda handler
# 5. If invalid, API Gateway returns 401 Unauthorized
#
# Request Validation:
# -------------------
# The request validator checks:
# - Required path parameters are present
# - Required query parameters are present
# - Request body matches the model schema (if defined)
#
# Endpoint Type:
# --------------
# Uses REGIONAL endpoint (not EDGE) for lower latency within the same region.
# CloudFront distribution (frontend-stack) provides edge caching if needed.

# =============================================================================
# PARAMETERS
# =============================================================================
# All parameters are passed from the master template.

Parameters:
  ProjectName:
    Type: String
    Description: Project name passed from master template
    Default: aws-drs-orchestration

  Environment:
    Type: String
    Description: Environment name passed from master template
    AllowedValues: [dev, test, prod]
    Default: dev

  UserPoolId:
    Type: String
    Description: Cognito User Pool ID from auth stack

  UserPoolClientId:
    Type: String
    Description: Cognito User Pool Client ID (passed from master template)

  ApiHandlerFunctionArn:
    Type: String
    Description: ARN of the API Handler Lambda function from lambda stack

# =============================================================================
# RESOURCES
# =============================================================================

Resources:
  # ===========================================================================
  # REST API
  # ===========================================================================
  # The main API Gateway REST API. Uses regional endpoint type for lower
  # latency. Resource policy allows all IPs (CloudFront handles edge security).
  # Binary media types enable file uploads via the API.
  
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub '${ProjectName}-api-${Environment}'
      Description: 'REST API for AWS DRS Orchestration with Cognito authentication'
      EndpointConfiguration:
        Types: [REGIONAL]
      Policy:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: execute-api:Invoke
            Resource: '*'
            Condition:
              IpAddress:
                aws:SourceIp: 
                  - '0.0.0.0/0'
      BinaryMediaTypes:
        - 'application/octet-stream'
        - 'multipart/form-data'

  # ===========================================================================
  # COGNITO AUTHORIZER
  # ===========================================================================
  # Validates JWT tokens from the Cognito User Pool. Extracts the token from
  # the Authorization header and verifies signature, expiration, and issuer.
  # Returns user claims (sub, email, groups) to Lambda via requestContext.
  
  ApiAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: !Sub '${ProjectName}-cognito-authorizer-${Environment}'
      Type: COGNITO_USER_POOLS
      IdentitySource: method.request.header.Authorization
      RestApiId: !Ref RestApi
      ProviderARNs:
        - !Sub 'arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${UserPoolId}'

  # ===========================================================================
  # REQUEST VALIDATOR
  # ===========================================================================
  # Validates incoming requests before invoking Lambda. Checks that required
  # path/query parameters are present and request body matches schema.
  # Returns 400 Bad Request if validation fails (before Lambda is invoked).
  
  ApiRequestValidator:
    Type: AWS::ApiGateway::RequestValidator
    Properties:
      Name: !Sub '${ProjectName}-request-validator-${Environment}'
      RestApiId: !Ref RestApi
      ValidateRequestBody: true
      ValidateRequestParameters: true

  # ===========================================================================
  # LAMBDA PERMISSION
  # ===========================================================================
  # Grants API Gateway permission to invoke the API handler Lambda.
  # Uses wildcard for stage/method so all endpoints can invoke the function.
  
  ApiGatewayInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ApiHandlerFunctionArn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApi}/*'

# =============================================================================
# OUTPUTS
# =============================================================================
# Export core API components for use by resource and method stacks.

Outputs:
  RestApiId:
    Description: 'REST API ID for use in other stacks'
    Value: !Ref RestApi
    Export:
      Name: !Sub '${AWS::StackName}-RestApiId'

  RestApiRootResourceId:
    Description: 'REST API Root Resource ID for use in other stacks'
    Value: !GetAtt RestApi.RootResourceId
    Export:
      Name: !Sub '${AWS::StackName}-RestApiRootResourceId'

  ApiAuthorizerId:
    Description: 'API Authorizer ID for use in other stacks'
    Value: !Ref ApiAuthorizer
    Export:
      Name: !Sub '${AWS::StackName}-ApiAuthorizerId'

  ApiRequestValidatorId:
    Description: 'API Request Validator ID for use in other stacks'
    Value: !Ref ApiRequestValidator
    Export:
      Name: !Sub '${AWS::StackName}-ApiRequestValidatorId'

  ApiHandlerFunctionArn:
    Description: 'API Handler Function ARN for use in other stacks'
    Value: !Ref ApiHandlerFunctionArn
    Export:
      Name: !Sub '${AWS::StackName}-ApiHandlerFunctionArn'
