AWSTemplateFormatVersion: '2010-09-09'
Description: |
  API Authentication Stack - Cognito User Pool, Identity Pool, and RBAC groups
  for user authentication and authorization.

# =============================================================================
# STACK OVERVIEW
# =============================================================================
# This stack creates the authentication infrastructure for the platform.
# Users authenticate via Cognito and receive JWT tokens for API access.
#
# Components:
# -----------
# 1. User Pool - Stores user accounts with email/password authentication
# 2. User Pool Client - OAuth2 client for frontend authentication
# 3. Identity Pool - Provides temporary AWS credentials for authenticated users
# 4. RBAC Groups - Role-based access control groups
#
# Authentication Flow:
# --------------------
# 1. User signs in with email/password via Cognito hosted UI or API
# 2. Cognito validates credentials and returns JWT tokens:
#    - ID Token: Contains user identity and group memberships
#    - Access Token: Used for API authorization
#    - Refresh Token: Used to obtain new tokens without re-authentication
# 3. Frontend includes Access Token in API requests
# 4. API Gateway validates token using Cognito authorizer
# 5. Lambda receives user claims (sub, email, groups) in requestContext
#
# RBAC Groups (Precedence Order):
# -------------------------------
# 1. DRSOrchestrationAdmin - Full platform access
# 2. DRSRecoveryManager    - Manage and execute recovery plans
# 3. DRSPlanManager        - Create/modify plans (no execution)
# 4. DRSOperator           - Execute existing plans only
# 5. DRSReadOnly           - View-only access
#
# Token Validity:
# ---------------
# - Access Token: 45 minutes
# - ID Token: 45 minutes
# - Refresh Token: 30 days
#
# Adding Users:
# -------------
# Users can be added via:
# - AWS Console: Cognito > User Pools > Users > Create user
# - AWS CLI: aws cognito-idp admin-create-user
# - Self-registration (if enabled)
#
# Assigning Roles:
# ----------------
# Add users to groups via:
# - AWS Console: Cognito > User Pools > Groups > Add user
# - AWS CLI: aws cognito-idp admin-add-user-to-group

# =============================================================================
# PARAMETERS
# =============================================================================
# Parameters passed from master template.

Parameters:
  ProjectName:
    Type: String
    Description: Project name passed from master template

  Environment:
    Type: String
    Description: Environment name passed from master template

  AdminEmail:
    Type: String
    Description: Admin email (passed from master template)

  ExecutionHistoryTableArn:
    Type: String
    Description: Execution history table ARN (passed from master template)

# =============================================================================
# RESOURCES
# =============================================================================

Resources:
  # ===========================================================================
  # COGNITO USER POOL
  # ===========================================================================
  # Stores user accounts with email-based authentication.
  # Password policy enforces strong passwords (8+ chars, mixed case, numbers, symbols).
  
  UserPool:
    Type: AWS::Cognito::UserPool
    DeletionPolicy: Delete
    Properties:
      UserPoolName: !Sub '${ProjectName}-users-${Environment}'
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: false
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: true
        - Name: given_name
          AttributeDataType: String
          Required: false
          Mutable: true
        - Name: family_name
          AttributeDataType: String
          Required: false
          Mutable: true
      UserPoolTags:
        Project: !Ref ProjectName
        Environment: !Ref Environment

  # ===========================================================================
  # RBAC GROUPS
  # ===========================================================================
  # Role-based access control groups. Users are assigned to groups to grant
  # permissions. Group membership is included in JWT tokens as cognito:groups.
  # Precedence determines which role takes priority when user has multiple.

  # ---------------------------------------------------------------------------
  # DRSOrchestrationAdmin (Precedence: 1) - Full platform access
  # ---------------------------------------------------------------------------
  DRSOrchestrationAdminGroup:
    Type: AWS::Cognito::UserPoolGroup
    DeletionPolicy: Delete
    Properties:
      UserPoolId: !Ref UserPool
      GroupName: DRSOrchestrationAdmin
      Description: 'Full administrative access to DRS Orchestration platform'
      Precedence: 1

  # ---------------------------------------------------------------------------
  # DRSRecoveryManager (Precedence: 2) - Manage and execute recovery plans
  # ---------------------------------------------------------------------------
  DRSRecoveryManagerGroup:
    Type: AWS::Cognito::UserPoolGroup
    DeletionPolicy: Delete
    Properties:
      UserPoolId: !Ref UserPool
      GroupName: DRSRecoveryManager
      Description: 'Can manage recovery plans and execute disaster recovery operations'
      Precedence: 2

  # ---------------------------------------------------------------------------
  # DRSPlanManager (Precedence: 3) - Create/modify plans, no execution
  # ---------------------------------------------------------------------------
  DRSPlanManagerGroup:
    Type: AWS::Cognito::UserPoolGroup
    DeletionPolicy: Delete
    Properties:
      UserPoolId: !Ref UserPool
      GroupName: DRSPlanManager
      Description: 'Can create and modify recovery plans and protection groups'
      Precedence: 3

  # ---------------------------------------------------------------------------
  # DRSOperator (Precedence: 4) - Execute existing plans only
  # ---------------------------------------------------------------------------
  DRSOperatorGroup:
    Type: AWS::Cognito::UserPoolGroup
    DeletionPolicy: Delete
    Properties:
      UserPoolId: !Ref UserPool
      GroupName: DRSOperator
      Description: 'Can execute existing recovery plans and monitor executions'
      Precedence: 4

  # ---------------------------------------------------------------------------
  # DRSReadOnly (Precedence: 5) - View-only access
  # ---------------------------------------------------------------------------
  DRSReadOnlyGroup:
    Type: AWS::Cognito::UserPoolGroup
    DeletionPolicy: Delete
    Properties:
      UserPoolId: !Ref UserPool
      GroupName: DRSReadOnly
      Description: 'Read-only access to DRS orchestration data and execution history'
      Precedence: 5

  # ===========================================================================
  # USER POOL CLIENT
  # ===========================================================================
  # OAuth2 client for frontend authentication. Supports SRP auth flow for
  # secure password-based authentication without sending password to server.
  
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    DeletionPolicy: Delete
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: !Sub '${ProjectName}-client-${Environment}'
      GenerateSecret: false  # pragma: allowlist secret
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs:
        - http://localhost:5173
        - !Sub 'https://${ProjectName}-${Environment}.s3-website-${AWS::Region}.amazonaws.com'
      LogoutURLs:
        - http://localhost:5173
        - !Sub 'https://${ProjectName}-${Environment}.s3-website-${AWS::Region}.amazonaws.com'
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      AllowedOAuthFlowsUserPoolClient: true
      RefreshTokenValidity: 30
      AccessTokenValidity: 45
      IdTokenValidity: 45
      TokenValidityUnits:
        AccessToken: minutes
        IdToken: minutes
        RefreshToken: days

  # ===========================================================================
  # IDENTITY POOL
  # ===========================================================================
  # Provides temporary AWS credentials for authenticated users.
  # Used when frontend needs direct AWS access (e.g., S3 uploads).
  
  IdentityPool:
    Type: AWS::Cognito::IdentityPool
    DeletionPolicy: Delete
    Properties:
      IdentityPoolName: !Sub '${ProjectName}_identity_pool_${Environment}'
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId: !Ref UserPoolClient
          ProviderName: !GetAtt UserPool.ProviderName

  # ===========================================================================
  # IAM ROLE FOR AUTHENTICATED USERS
  # ===========================================================================
  # Role assumed by authenticated users via Identity Pool.
  # Grants permission to invoke API Gateway endpoints.
  
  CognitoAuthenticatedRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Delete
    Properties:
      RoleName: !Sub '${ProjectName}-cognito-authenticated-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                'cognito-identity.amazonaws.com:aud': !Ref IdentityPool
              'ForAnyValue:StringLike':
                'cognito-identity.amazonaws.com:amr': authenticated
      Policies:
        - PolicyName: CognitoAuthenticatedPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cognito-sync:*
                  - cognito-identity:*
                Resource: '*'
              - Effect: Allow
                Action:
                  - execute-api:Invoke
                Resource: '*'

  # ===========================================================================
  # IDENTITY POOL ROLE ATTACHMENT
  # ===========================================================================
  # Maps the authenticated IAM role to the Identity Pool.
  
  IdentityPoolRoleMapping:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    DeletionPolicy: Delete
    DeletionPolicy: Delete
    Properties:
      IdentityPoolId: !Ref IdentityPool
      Roles:
        authenticated: !GetAtt CognitoAuthenticatedRole.Arn

# =============================================================================
# OUTPUTS
# =============================================================================
# Export Cognito resources for use by other stacks.

Outputs:
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolId'

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolClientId'

  IdentityPoolId:
    Description: Cognito Identity Pool ID
    Value: !Ref IdentityPool
    Export:
      Name: !Sub '${AWS::StackName}-IdentityPoolId'

  # ---------------------------------------------------------------------------
  # RBAC Group Names
  # ---------------------------------------------------------------------------
  DRSOrchestrationAdminGroupName:
    Description: DRS Orchestration Administrator Group
    Value: !Ref DRSOrchestrationAdminGroup
    Export:
      Name: !Sub '${AWS::StackName}-DRSOrchestrationAdminGroup'

  DRSRecoveryManagerGroupName:
    Description: DRS Recovery Manager Group
    Value: !Ref DRSRecoveryManagerGroup
    Export:
      Name: !Sub '${AWS::StackName}-DRSRecoveryManagerGroup'

  DRSPlanManagerGroupName:
    Description: DRS Plan Manager Group
    Value: !Ref DRSPlanManagerGroup
    Export:
      Name: !Sub '${AWS::StackName}-DRSPlanManagerGroup'

  DRSOperatorGroupName:
    Description: DRS Operator Group
    Value: !Ref DRSOperatorGroup
    Export:
      Name: !Sub '${AWS::StackName}-DRSOperatorGroup'

  DRSReadOnlyGroupName:
    Description: DRS Read-Only Group
    Value: !Ref DRSReadOnlyGroup
    Export:
      Name: !Sub '${AWS::StackName}-DRSReadOnlyGroup'