AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS DRS Orchestration - CodeBuild Projects Stack'

Parameters:
  ProjectName:
    Type: String
    Description: 'Project name for resource naming'

  Environment:
    Type: String
    Description: 'Environment name (dev, test, prod)'

  SourceBucket:
    Type: String
    Description: 'S3 bucket containing deployment artifacts'

  ArtifactBucketName:
    Type: String
    Description: 'S3 bucket for CI/CD artifacts'
    Default: 'aws-elasticdrs-orchestrator-cicd-artifacts-***REMOVED***-dev'

Resources:
  # IAM Role for CodeBuild Projects
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-codebuild-service-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Policies:
        - PolicyName: CodeBuildServicePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # S3 Access for artifacts and deployment bucket
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                  - s3:DeleteObject
                Resource:
                  - !Sub 'arn:aws:s3:::${ArtifactBucketName}/*'
                  - !Sub 'arn:aws:s3:::${SourceBucket}/*'
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${ArtifactBucketName}'
                  - !Sub 'arn:aws:s3:::${SourceBucket}'
              # CloudFormation access for infrastructure deployment
              - Effect: Allow
                Action:
                  - cloudformation:CreateStack
                  - cloudformation:UpdateStack
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeStackEvents
                  - cloudformation:DescribeStackResources
                  - cloudformation:GetTemplate
                  - cloudformation:ValidateTemplate
                  - cloudformation:CreateChangeSet
                  - cloudformation:DescribeChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:ListStacks
                Resource: '*'
              # IAM access for CloudFormation deployments
              - Effect: Allow
                Action:
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:GetRole
                  - iam:PassRole
                  - iam:AttachRolePolicy
                  - iam:DetachRolePolicy
                  - iam:PutRolePolicy
                  - iam:DeleteRolePolicy
                  - iam:GetRolePolicy
                  - iam:ListRolePolicies
                  - iam:ListAttachedRolePolicies
                  - iam:CreateInstanceProfile
                  - iam:DeleteInstanceProfile
                  - iam:AddRoleToInstanceProfile
                  - iam:RemoveRoleFromInstanceProfile
                  - iam:GetInstanceProfile
                Resource: '*'
              # Lambda access for function deployment
              - Effect: Allow
                Action:
                  - lambda:CreateFunction
                  - lambda:UpdateFunctionCode
                  - lambda:UpdateFunctionConfiguration
                  - lambda:DeleteFunction
                  - lambda:GetFunction
                  - lambda:ListFunctions
                  - lambda:InvokeFunction
                  - lambda:AddPermission
                  - lambda:RemovePermission
                  - lambda:GetPolicy
                Resource: '*'
              # API Gateway access
              - Effect: Allow
                Action:
                  - apigateway:*
                Resource: '*'
              # DynamoDB access
              - Effect: Allow
                Action:
                  - dynamodb:CreateTable
                  - dynamodb:DeleteTable
                  - dynamodb:DescribeTable
                  - dynamodb:UpdateTable
                  - dynamodb:ListTables
                  - dynamodb:TagResource
                  - dynamodb:UntagResource
                Resource: '*'
              # Cognito access
              - Effect: Allow
                Action:
                  - cognito-idp:*
                  - cognito-identity:*
                Resource: '*'
              # Step Functions access
              - Effect: Allow
                Action:
                  - states:CreateStateMachine
                  - states:DeleteStateMachine
                  - states:UpdateStateMachine
                  - states:DescribeStateMachine
                  - states:ListStateMachines
                  - states:TagResource
                  - states:UntagResource
                Resource: '*'
              # EventBridge access
              - Effect: Allow
                Action:
                  - events:PutRule
                  - events:DeleteRule
                  - events:DescribeRule
                  - events:PutTargets
                  - events:RemoveTargets
                  - events:ListTargetsByRule
                Resource: '*'
              # CloudFront access
              - Effect: Allow
                Action:
                  - cloudfront:CreateDistribution
                  - cloudfront:UpdateDistribution
                  - cloudfront:DeleteDistribution
                  - cloudfront:GetDistribution
                  - cloudfront:ListDistributions
                  - cloudfront:CreateInvalidation
                  - cloudfront:GetInvalidation
                  - cloudfront:ListInvalidations
                  - cloudfront:TagResource
                  - cloudfront:UntagResource
                Resource: '*'
              # WAF access
              - Effect: Allow
                Action:
                  - wafv2:*
                Resource: '*'
              # CloudTrail access
              - Effect: Allow
                Action:
                  - cloudtrail:CreateTrail
                  - cloudtrail:DeleteTrail
                  - cloudtrail:UpdateTrail
                  - cloudtrail:DescribeTrails
                  - cloudtrail:StartLogging
                  - cloudtrail:StopLogging
                  - cloudtrail:GetTrailStatus
                Resource: '*'
              # CodeBuild report group access for security scanning
              - Effect: Allow
                Action:
                  - codebuild:CreateReportGroup
                  - codebuild:UpdateReportGroup
                  - codebuild:DeleteReportGroup
                  - codebuild:DescribeReportGroups
                  - codebuild:CreateReport
                  - codebuild:UpdateReport
                  - codebuild:BatchPutTestCases
                  - codebuild:BatchPutCodeCoverages
                Resource: '*'
              # Secrets Manager access
              - Effect: Allow
                Action:
                  - secretsmanager:CreateSecret
                  - secretsmanager:DeleteSecret
                  - secretsmanager:UpdateSecret
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
                  - secretsmanager:TagResource
                  - secretsmanager:UntagResource
                Resource: '*'
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # CodeBuild Project for Validation (cfn-lint, syntax checks)
  ValidateProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub '${ProjectName}-validate-${Environment}'
      Description: 'Validate CloudFormation templates and code quality'
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
        EnvironmentVariables:
          - Name: PROJECT_NAME
            Value: !Ref ProjectName
          - Name: ENVIRONMENT
            Value: !Ref Environment
          - Name: DEPLOYMENT_BUCKET
            Value: !Ref SourceBucket
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspecs/validate-buildspec.yml
      TimeoutInMinutes: 15
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # CodeBuild Project for Building (Lambda packages, frontend)
  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub '${ProjectName}-build-${Environment}'
      Description: 'Build Lambda packages and frontend application'
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
        EnvironmentVariables:
          - Name: PROJECT_NAME
            Value: !Ref ProjectName
          - Name: ENVIRONMENT
            Value: !Ref Environment
          - Name: DEPLOYMENT_BUCKET
            Value: !Ref SourceBucket
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspecs/build-buildspec.yml
      TimeoutInMinutes: 30
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # CodeBuild Project for Testing (integration tests)
  TestProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub '${ProjectName}-test-${Environment}'
      Description: 'Run integration and end-to-end tests'
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
        EnvironmentVariables:
          - Name: PROJECT_NAME
            Value: !Ref ProjectName
          - Name: ENVIRONMENT
            Value: !Ref Environment
          - Name: DEPLOYMENT_BUCKET
            Value: !Ref SourceBucket
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspecs/test-buildspec.yml
      TimeoutInMinutes: 20
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # CodeBuild Project for Infrastructure Deployment
  DeployInfraProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub '${ProjectName}-deploy-infra-${Environment}'
      Description: 'Deploy CloudFormation infrastructure'
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
        EnvironmentVariables:
          - Name: PROJECT_NAME
            Value: !Ref ProjectName
          - Name: ENVIRONMENT
            Value: !Ref Environment
          - Name: DEPLOYMENT_BUCKET
            Value: !Ref SourceBucket
          - Name: STACK_NAME
            Value: !Sub '${ProjectName}-${Environment}'
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspecs/deploy-infra-buildspec.yml
      TimeoutInMinutes: 60
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # CodeBuild Project for Security Scanning
  SecurityScanProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub '${ProjectName}-security-scan-${Environment}'
      Description: 'Comprehensive security scanning with Bandit, Semgrep, Safety, and ESLint'
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
        EnvironmentVariables:
          - Name: PROJECT_NAME
            Value: !Ref ProjectName
          - Name: ENVIRONMENT
            Value: !Ref Environment
          - Name: SECURITY_THRESHOLD_CRITICAL
            Value: '0'
          - Name: SECURITY_THRESHOLD_HIGH
            Value: '10'
          - Name: SECURITY_THRESHOLD_TOTAL
            Value: '50'
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspecs/security-buildspec.yml
      TimeoutInMinutes: 20
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # CodeBuild Project for Frontend Deployment
  DeployFrontendProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub '${ProjectName}-deploy-frontend-${Environment}'
      Description: 'Deploy frontend to S3 and invalidate CloudFront'
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
        EnvironmentVariables:
          - Name: PROJECT_NAME
            Value: !Ref ProjectName
          - Name: ENVIRONMENT
            Value: !Ref Environment
          - Name: DEPLOYMENT_BUCKET
            Value: !Ref SourceBucket
          - Name: STACK_NAME
            Value: !Sub '${ProjectName}-${Environment}'
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspecs/deploy-frontend-buildspec.yml
      TimeoutInMinutes: 15
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

Outputs:
  CodeBuildServiceRoleArn:
    Description: 'CodeBuild service role ARN'
    Value: !GetAtt CodeBuildServiceRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-CodeBuildServiceRoleArn'

  ValidateProjectName:
    Description: 'Validation CodeBuild project name'
    Value: !Ref ValidateProject
    Export:
      Name: !Sub '${AWS::StackName}-ValidateProjectName'

  ValidateProjectArn:
    Description: 'Validation CodeBuild project ARN'
    Value: !GetAtt ValidateProject.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ValidateProjectArn'

  BuildProjectName:
    Description: 'Build CodeBuild project name'
    Value: !Ref BuildProject
    Export:
      Name: !Sub '${AWS::StackName}-BuildProjectName'

  BuildProjectArn:
    Description: 'Build CodeBuild project ARN'
    Value: !GetAtt BuildProject.Arn
    Export:
      Name: !Sub '${AWS::StackName}-BuildProjectArn'

  TestProjectName:
    Description: 'Test CodeBuild project name'
    Value: !Ref TestProject
    Export:
      Name: !Sub '${AWS::StackName}-TestProjectName'

  TestProjectArn:
    Description: 'Test CodeBuild project ARN'
    Value: !GetAtt TestProject.Arn
    Export:
      Name: !Sub '${AWS::StackName}-TestProjectArn'

  DeployInfraProjectName:
    Description: 'Infrastructure deployment CodeBuild project name'
    Value: !Ref DeployInfraProject
    Export:
      Name: !Sub '${AWS::StackName}-DeployInfraProjectName'

  DeployInfraProjectArn:
    Description: 'Infrastructure deployment CodeBuild project ARN'
    Value: !GetAtt DeployInfraProject.Arn
    Export:
      Name: !Sub '${AWS::StackName}-DeployInfraProjectArn'

  SecurityScanProjectName:
    Description: 'Security scan CodeBuild project name'
    Value: !Ref SecurityScanProject
    Export:
      Name: !Sub '${AWS::StackName}-SecurityScanProjectName'

  SecurityScanProjectArn:
    Description: 'Security scan CodeBuild project ARN'
    Value: !GetAtt SecurityScanProject.Arn
    Export:
      Name: !Sub '${AWS::StackName}-SecurityScanProjectArn'

  DeployFrontendProjectName:
    Description: 'Frontend deployment CodeBuild project name'
    Value: !Ref DeployFrontendProject
    Export:
      Name: !Sub '${AWS::StackName}-DeployFrontendProjectName'

  DeployFrontendProjectArn:
    Description: 'Frontend deployment CodeBuild project ARN'
    Value: !GetAtt DeployFrontendProject.Arn
    Export:
      Name: !Sub '${AWS::StackName}-DeployFrontendProjectArn'