AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS DRS Orchestration - CodeCommit Repository Stack'

Parameters:
  ProjectName:
    Type: String
    Description: 'Project name for resource naming'

  Environment:
    Type: String
    Description: 'Environment name (dev, test, prod)'

Resources:
  # CodeCommit Repository
  Repository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Sub '${ProjectName}-${Environment}'
      RepositoryDescription: !Sub 'AWS DRS Orchestration source code repository for ${Environment} environment'
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # S3 Bucket for CI/CD artifacts (always created)
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-cicd-artifacts-${AWS::AccountId}-${Environment}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
          - Id: DeleteIncompleteMultipartUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

Outputs:
  RepositoryName:
    Description: 'CodeCommit repository name'
    Value: !GetAtt Repository.Name
    Export:
      Name: !Sub '${AWS::StackName}-RepositoryName'

  RepositoryArn:
    Description: 'CodeCommit repository ARN'
    Value: !GetAtt Repository.Arn
    Export:
      Name: !Sub '${AWS::StackName}-RepositoryArn'

  RepositoryCloneUrlHttp:
    Description: 'CodeCommit repository HTTPS clone URL'
    Value: !GetAtt Repository.CloneUrlHttp
    Export:
      Name: !Sub '${AWS::StackName}-RepositoryCloneUrlHttp'

  RepositoryCloneUrlSsh:
    Description: 'CodeCommit repository SSH clone URL'
    Value: !GetAtt Repository.CloneUrlSsh
    Export:
      Name: !Sub '${AWS::StackName}-RepositoryCloneUrlSsh'

  ArtifactBucketName:
    Description: 'S3 bucket for CI/CD artifacts'
    Value: !Ref ArtifactBucket
    Export:
      Name: !Sub '${AWS::StackName}-ArtifactBucketName'

  ArtifactBucketArn:
    Description: 'S3 bucket ARN for CI/CD artifacts'
    Value: !GetAtt ArtifactBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ArtifactBucketArn'