AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS DRS Orchestration - CodePipeline Stack'

Parameters:
  ProjectName:
    Type: String
    Description: 'Project name for resource naming'

  Environment:
    Type: String
    Description: 'Environment name (dev, test, prod)'

  RepositoryName:
    Type: String
    Description: 'CodeCommit repository name'

  ArtifactBucketName:
    Type: String
    Description: 'S3 bucket for CI/CD artifacts'

  ValidateProjectName:
    Type: String
    Description: 'CodeBuild project name for validation'

  BuildProjectName:
    Type: String
    Description: 'CodeBuild project name for building'

  TestProjectName:
    Type: String
    Description: 'CodeBuild project name for testing'

  DeployInfraProjectName:
    Type: String
    Description: 'CodeBuild project name for infrastructure deployment'

  DeployFrontendProjectName:
    Type: String
    Description: 'CodeBuild project name for frontend deployment'

  SecurityScanProjectName:
    Type: String
    Description: 'CodeBuild project name for security scanning'

  AdminEmail:
    Type: String
    Description: 'Admin email address for pipeline notifications'
    AllowedPattern: '^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
    ConstraintDescription: 'Must be a valid email address'

  EnablePipelineNotifications:
    Type: String
    Default: 'true'
    Description: 'Enable SNS email notifications for pipeline and security scan failures'
    AllowedValues:
      - 'true'
      - 'false'

Conditions:
  EnableNotifications: !Equals [!Ref EnablePipelineNotifications, 'true']

Resources:
  # IAM Role for CodePipeline
  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-codepipeline-service-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodePipelineServicePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # S3 Access for artifacts
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: !Sub 'arn:aws:s3:::${ArtifactBucketName}/*'
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !Sub 'arn:aws:s3:::${ArtifactBucketName}'
              # CodeCommit Access
              - Effect: Allow
                Action:
                  - codecommit:CancelUploadArchive
                  - codecommit:GetBranch
                  - codecommit:GetCommit
                  - codecommit:GetRepository
                  - codecommit:ListBranches
                  - codecommit:ListRepositories
                  - codecommit:UploadArchive
                  - codecommit:GetUploadArchiveStatus
                Resource: !Sub 'arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:${RepositoryName}'
              # CodeBuild Access
              - Effect: Allow
                Action:
                  - codebuild:BatchGetBuilds
                  - codebuild:StartBuild
                Resource:
                  - !Sub 'arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/${ValidateProjectName}'
                  - !Sub 'arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/${SecurityScanProjectName}'
                  - !Sub 'arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/${BuildProjectName}'
                  - !Sub 'arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/${TestProjectName}'
                  - !Sub 'arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/${DeployInfraProjectName}'
                  - !Sub 'arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/${DeployFrontendProjectName}'
              # SNS permissions for notifications (conditional)
              - !If
                - EnableNotifications
                - Effect: Allow
                  Action:
                    - sns:Publish
                  Resource: !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${ProjectName}-pipeline-notifications-${Environment}'
                - !Ref AWS::NoValue
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # CodePipeline
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub '${ProjectName}-pipeline-${Environment}'
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucketName
      Stages:
        # Source Stage - CodeCommit
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: '1'
              Configuration:
                RepositoryName: !Ref RepositoryName
                BranchName: main
                PollForSourceChanges: true
              OutputArtifacts:
                - Name: SourceOutput

        # Validate Stage - Code quality and CloudFormation validation
        - Name: Validate
          Actions:
            - Name: ValidateAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref ValidateProjectName
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: ValidateOutput

        # Security Scan Stage - Comprehensive security scanning
        - Name: SecurityScan
          Actions:
            - Name: SecurityScanAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref SecurityScanProjectName
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: SecurityScanOutput

        # Build Stage - Lambda packages and frontend
        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref BuildProjectName
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput

        # Test Stage - Integration and E2E tests
        - Name: Test
          Actions:
            - Name: TestAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref TestProjectName
              InputArtifacts:
                - Name: BuildOutput
              OutputArtifacts:
                - Name: TestOutput

        # Deploy Infrastructure Stage
        - Name: DeployInfrastructure
          Actions:
            - Name: DeployInfraAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref DeployInfraProjectName
                EnvironmentVariables: |
                  [
                    {
                      "name": "ADMIN_EMAIL",
                      "value": "***REMOVED***",
                      "type": "PLAINTEXT"
                    }
                  ]
              InputArtifacts:
                - Name: TestOutput
              OutputArtifacts:
                - Name: DeployInfraOutput

        # Deploy Frontend Stage
        - Name: DeployFrontend
          Actions:
            - Name: DeployFrontendAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref DeployFrontendProjectName
              InputArtifacts:
                - Name: DeployInfraOutput
              OutputArtifacts:
                - Name: DeployFrontendOutput

      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # CloudWatch Event Rule for Pipeline State Changes (Conditional)
  PipelineEventRule:
    Type: AWS::Events::Rule
    Condition: EnableNotifications
    Properties:
      Name: !Sub '${ProjectName}-pipeline-events-${Environment}'
      Description: 'Capture pipeline state changes'
      EventPattern:
        source:
          - aws.codepipeline
        detail-type:
          - CodePipeline Pipeline Execution State Change
          - CodePipeline Stage Execution State Change
        detail:
          pipeline:
            - !Ref Pipeline
          state:
            - FAILED
      State: ENABLED
      Targets:
        - Arn: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${ProjectName}-notification-formatter-${Environment}'
          Id: PipelineFailureNotificationFormatter
        - Arn: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/events/codepipeline'
          Id: PipelineLogTarget

  # CloudWatch Event Rule for Security Scan Failures (Conditional)
  SecurityScanFailureEventRule:
    Type: AWS::Events::Rule
    Condition: EnableNotifications
    Properties:
      Name: !Sub '${ProjectName}-security-scan-failures-${Environment}'
      Description: 'Capture security scan build failures'
      EventPattern:
        source:
          - aws.codebuild
        detail-type:
          - CodeBuild Build State Change
        detail:
          project-name:
            - !Ref SecurityScanProjectName
          build-status:
            - FAILED
      State: ENABLED
      Targets:
        - Arn: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${ProjectName}-notification-formatter-${Environment}'
          Id: SecurityScanFailureNotificationFormatter

  # EventBridge Permission for Pipeline Events to invoke Notification Formatter Lambda
  PipelineEventRuleLambdaPermission:
    Type: AWS::Lambda::Permission
    Condition: EnableNotifications
    Properties:
      FunctionName: !Sub '${ProjectName}-notification-formatter-${Environment}'
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt PipelineEventRule.Arn

  # EventBridge Permission for Security Scan Events to invoke Notification Formatter Lambda
  SecurityScanEventRuleLambdaPermission:
    Type: AWS::Lambda::Permission
    Condition: EnableNotifications
    Properties:
      FunctionName: !Sub '${ProjectName}-notification-formatter-${Environment}'
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt SecurityScanFailureEventRule.Arn

  # CloudWatch Log Group for Pipeline Events
  PipelineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: '/aws/events/codepipeline'
      RetentionInDays: 30
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

Outputs:
  PipelineName:
    Description: 'CodePipeline name'
    Value: !Ref Pipeline
    Export:
      Name: !Sub '${AWS::StackName}-PipelineName'

  PipelineArn:
    Description: 'CodePipeline ARN'
    Value: !Sub 'arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${Pipeline}'
    Export:
      Name: !Sub '${AWS::StackName}-PipelineArn'

  PipelineUrl:
    Description: 'CodePipeline console URL'
    Value: !Sub 'https://console.aws.amazon.com/codesuite/codepipeline/pipelines/${Pipeline}/view'
    Export:
      Name: !Sub '${AWS::StackName}-PipelineUrl'

  CodePipelineServiceRoleArn:
    Description: 'CodePipeline service role ARN'
    Value: !GetAtt CodePipelineServiceRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-CodePipelineServiceRoleArn'

  PipelineEventRuleArn:
    Description: 'Pipeline event rule ARN'
    Value: !GetAtt PipelineEventRule.Arn
    Export:
      Name: !Sub '${AWS::StackName}-PipelineEventRuleArn'
    Condition: EnableNotifications

  PipelineNotificationsTopicArn:
    Description: 'Pipeline notifications SNS topic ARN'
    Value: !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${ProjectName}-pipeline-notifications-${Environment}'
    Export:
      Name: !Sub '${AWS::StackName}-PipelineNotificationsTopicArn'
    Condition: EnableNotifications

  SecurityScanFailureEventRuleArn:
    Description: 'Security scan failure event rule ARN'
    Value: !GetAtt SecurityScanFailureEventRule.Arn
    Export:
      Name: !Sub '${AWS::StackName}-SecurityScanFailureEventRuleArn'
    Condition: EnableNotifications