AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cross-account role for DRS Orchestration operations'

Parameters:
  SourceAccountNumber:
    Description: 'AWS Account ID where DRS Orchestration is deployed (hub account)'
    Type: String
    AllowedPattern: '[0-9]{12}'
    ConstraintDescription: 'Must be a valid 12-digit AWS account ID'
  
  Environment:
    Type: String
    Description: 'Environment name (dev, test, prod)'
    Default: 'test'
    AllowedValues: ['dev', 'test', 'qa', 'prod']
  
  ProjectName:
    Type: String
    Description: 'Project name for resource naming'
    Default: 'drs-orchestration'

Resources:
  # Cross-account role that hub account can assume
  DRSOrchestrationCrossAccountRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-cross-account-role-${Environment}'
      Description: 'Role for DRS Orchestration hub account to perform DRS operations'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${SourceAccountNumber}:role/${ProjectName}-orchestration-role-${Environment}'
            Action: 'sts:AssumeRole'
            Condition:
              StringEquals:
                'sts:ExternalId': !Sub '${ProjectName}-${Environment}-${AWS::AccountId}'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AWSElasticDisasterRecoveryConsoleFullAccess'
      Policies:
        - PolicyName: !Sub '${ProjectName}-cross-account-policy-${Environment}'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # DRS Operations
              - Sid: DRSOperations
                Effect: Allow
                Action:
                  # Core DRS read operations
                  - 'drs:DescribeJobs'
                  - 'drs:DescribeJobLogItems'
                  - 'drs:DescribeSourceServers'
                  - 'drs:DescribeRecoveryInstances'
                  - 'drs:DescribeRecoverySnapshots'
                  - 'drs:DescribeReplicationConfigurationTemplates'
                  - 'drs:DescribeLaunchConfigurationTemplates'
                  - 'drs:DescribeSourceNetworks'
                  - 'drs:GetReplicationConfiguration'
                  - 'drs:GetLaunchConfiguration'
                  - 'drs:GetFailbackReplicationConfiguration'
                  - 'drs:ListTagsForResource'
                  # DRS recovery operations
                  - 'drs:StartRecovery'
                  - 'drs:TerminateRecoveryInstances'
                  - 'drs:DisconnectRecoveryInstance'
                  - 'drs:ReverseReplication'
                  - 'drs:StartFailback'
                  - 'drs:StopFailback'
                  # DRS configuration management
                  - 'drs:UpdateLaunchConfiguration'
                  - 'drs:UpdateReplicationConfiguration'
                  - 'drs:UpdateFailbackReplicationConfiguration'
                  - 'drs:CreateReplicationConfigurationTemplate'
                  - 'drs:UpdateReplicationConfigurationTemplate'
                  - 'drs:DeleteReplicationConfigurationTemplate'
                  - 'drs:CreateLaunchConfigurationTemplate'
                  - 'drs:UpdateLaunchConfigurationTemplate'
                  - 'drs:DeleteLaunchConfigurationTemplate'
                  # DRS replication management
                  - 'drs:StartReplication'
                  - 'drs:StopReplication'
                  - 'drs:PauseReplication'
                  - 'drs:ResumeReplication'
                  - 'drs:RetryDataReplication'
                  # DRS source server management
                  - 'drs:CreateSourceServer'
                  - 'drs:DeleteSourceServer'
                  - 'drs:MarkAsArchived'
                  - 'drs:CreateExtendedSourceServer'
                  # DRS service management
                  - 'drs:InitializeService'
                  - 'drs:CreateSourceNetwork'
                  - 'drs:DeleteSourceNetwork'
                  - 'drs:UpdateSourceNetwork'
                  - 'drs:DeleteJob'
                  # DRS tag management
                  - 'drs:TagResource'
                  - 'drs:UntagResource'
                  # CRITICAL: Required for DRS to register recovery instances
                  - 'drs:CreateRecoveryInstanceForDrs'
                Resource: '*'
              
              # EC2 Operations (required by DRS during recovery)
              - Sid: EC2Operations
                Effect: Allow
                Action:
                  - 'ec2:DescribeInstances'
                  - 'ec2:DescribeInstanceStatus'
                  - 'ec2:DescribeInstanceTypes'
                  - 'ec2:DescribeInstanceTypeOfferings'
                  - 'ec2:DescribeInstanceAttribute'
                  - 'ec2:DescribeAccountAttributes'
                  - 'ec2:DescribeLaunchTemplates'
                  - 'ec2:DescribeLaunchTemplateVersions'
                  - 'ec2:DescribeAvailabilityZones'
                  - 'ec2:DescribeNetworkInterfaces'
                  - 'ec2:DescribeVolumes'
                  - 'ec2:DescribeVolumeAttribute'
                  - 'ec2:DescribeSnapshots'
                  - 'ec2:DescribeSubnets'
                  - 'ec2:DescribeSecurityGroups'
                  - 'ec2:DescribeVpcs'
                  - 'ec2:DescribeImages'
                  - 'ec2:DescribeTags'
                  - 'ec2:GetEbsDefaultKmsKeyId'
                  - 'ec2:GetEbsEncryptionByDefault'
                Resource: '*'
              
              # EC2 Write Operations (required by DRS)
              - Sid: EC2WriteOperations
                Effect: Allow
                Action:
                  - 'ec2:RunInstances'
                  - 'ec2:StartInstances'
                  - 'ec2:StopInstances'
                  - 'ec2:TerminateInstances'
                  - 'ec2:ModifyInstanceAttribute'
                  - 'ec2:CreateVolume'
                  - 'ec2:AttachVolume'
                  - 'ec2:DetachVolume'
                  - 'ec2:DeleteVolume'
                  - 'ec2:ModifyVolume'
                  - 'ec2:CreateLaunchTemplate'
                  - 'ec2:CreateLaunchTemplateVersion'
                  - 'ec2:ModifyLaunchTemplate'
                  - 'ec2:DeleteLaunchTemplate'
                  - 'ec2:DeleteLaunchTemplateVersions'
                  - 'ec2:CreateNetworkInterface'
                  - 'ec2:AttachNetworkInterface'
                  - 'ec2:DeleteNetworkInterface'
                  - 'ec2:ModifyNetworkInterfaceAttribute'
                  - 'ec2:CreateTags'
                  - 'ec2:CreateSecurityGroup'
                  # EC2 Snapshot/AMI operations (required for DRS drill conversions)
                  - 'ec2:CreateSnapshot'
                  - 'ec2:DeleteSnapshot'
                  - 'ec2:CreateImage'
                  - 'ec2:DeregisterImage'
                  - 'ec2:CopyImage'
                  - 'ec2:RegisterImage'
                Resource: '*'
              
              # IAM Operations (for instance profiles)
              - Sid: IAMOperations
                Effect: Allow
                Action:
                  - 'iam:ListInstanceProfiles'
                  - 'iam:PassRole'
                Resource: '*'
              
              # SSM Operations (for post-launch automation)
              - Sid: SSMOperations
                Effect: Allow
                Action:
                  - 'ssm:ListDocuments'
                  - 'ssm:DescribeDocument'
                  - 'ssm:StartAutomationExecution'
                  - 'ssm:DescribeAutomationExecutions'
                  - 'ssm:GetAutomationExecution'
                  - 'ssm:StopAutomationExecution'
                Resource: '*'
              
              # S3 Operations (for post-launch logs)
              - Sid: S3Operations
                Effect: Allow
                Action:
                  - 's3:ListAllMyBuckets'
                  - 's3:GetBucketLocation'
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:DeleteObject'
                  - 's3:ListBucket'
                Resource: 
                  - 'arn:aws:s3:::*drs*'
                  - 'arn:aws:s3:::*drs*/*'
                  - 'arn:aws:s3:::*orchestration*'
                  - 'arn:aws:s3:::*orchestration*/*'

Outputs:
  CrossAccountRoleArn:
    Description: 'ARN of the cross-account role for DRS Orchestration'
    Value: !GetAtt DRSOrchestrationCrossAccountRole.Arn
    Export:
      Name: !Sub '${ProjectName}-cross-account-role-arn-${Environment}'
  
  CrossAccountRoleName:
    Description: 'Name of the cross-account role'
    Value: !Ref DRSOrchestrationCrossAccountRole
    Export:
      Name: !Sub '${ProjectName}-cross-account-role-name-${Environment}'
  
  ExternalId:
    Description: 'External ID for secure cross-account access'
    Value: !Sub '${ProjectName}-${Environment}-${AWS::AccountId}'
    Export:
      Name: !Sub '${ProjectName}-external-id-${Environment}'