AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cross-account role for DRS Orchestration operations - Deploy in target and staging accounts (Standardized Role Name)'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'Orchestration Account Configuration'
        Parameters:
          - OrchestrationAccountId
          - ExternalId
      - Label:
          default: 'Project Configuration'
        Parameters:
          - ProjectName

Parameters:
  OrchestrationAccountId:
    Description: 'AWS Account ID where DRS Orchestration is deployed'
    Type: String
    AllowedPattern: '[0-9]{12}'
    ConstraintDescription: 'Must be a valid 12-digit AWS account ID'
  
  ExternalId:
    Description: 'External ID for secure cross-account access (standardized across all accounts)'
    Type: String
    Default: 'drs-orchestration-cross-account'
    MinLength: 8
    MaxLength: 64
    ConstraintDescription: 'Must be between 8 and 64 characters'
  
  ProjectName:
    Type: String
    Description: 'Project name for resource naming'
    Default: 'drs-orchestration'

Conditions:
  UseCustomExternalId: !Not [!Equals [!Ref ExternalId, 'drs-orchestration-cross-account']]

Resources:
  DRSOrchestrationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DRSOrchestrationRole
      Description: !Sub 'Standardized cross-account role for DRS Orchestration account (${OrchestrationAccountId}) to perform DRS operations in ${AWS::AccountId}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:${AWS::Partition}:iam::${OrchestrationAccountId}:root'
            Action: 'sts:AssumeRole'
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref ExternalId
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/AWSElasticDisasterRecoveryConsoleFullAccess'
      Tags:
        - Key: Name
          Value: DRSOrchestrationRole
        - Key: ManagedBy
          Value: CloudFormation
        - Key: OrchestrationAccount
          Value: !Ref OrchestrationAccountId

  # Inline policy for DRS operations
  DRSOrchestrationPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: DRSOrchestrationPolicy
      Roles:
        - !Ref DRSOrchestrationRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # DRS Core Operations
          - Sid: DRSCoreOperations
            Effect: Allow
            Action:
              # Read operations
              - 'drs:DescribeJobs'
              - 'drs:DescribeJobLogItems'
              - 'drs:DescribeSourceServers'
              - 'drs:DescribeRecoveryInstances'
              - 'drs:DescribeRecoverySnapshots'
              - 'drs:DescribeReplicationConfigurationTemplates'
              - 'drs:DescribeLaunchConfigurationTemplates'
              - 'drs:DescribeSourceNetworks'
              - 'drs:GetReplicationConfiguration'
              - 'drs:GetLaunchConfiguration'
              - 'drs:GetFailbackReplicationConfiguration'
              - 'drs:ListTagsForResource'
              # Recovery operations
              - 'drs:StartRecovery'
              - 'drs:TerminateRecoveryInstances'
              - 'drs:DisconnectRecoveryInstance'
              - 'drs:ReverseReplication'
              - 'drs:StartFailbackLaunch'
              - 'drs:StopFailback'
              # Configuration management
              - 'drs:UpdateLaunchConfiguration'
              - 'drs:UpdateReplicationConfiguration'
              - 'drs:UpdateFailbackReplicationConfiguration'
              - 'drs:CreateReplicationConfigurationTemplate'
              - 'drs:UpdateReplicationConfigurationTemplate'
              - 'drs:DeleteReplicationConfigurationTemplate'
              - 'drs:CreateLaunchConfigurationTemplate'
              - 'drs:UpdateLaunchConfigurationTemplate'
              - 'drs:DeleteLaunchConfigurationTemplate'
              # Replication management
              - 'drs:StartReplication'
              - 'drs:StopReplication'
              - 'drs:RetryDataReplication'
              # Source server management
              - 'drs:DeleteSourceServer'
              - 'drs:CreateExtendedSourceServer'
              - 'drs:ListExtensibleSourceServers'
              - 'drs:ListStagingAccounts'
              # Service management
              - 'drs:InitializeService'
              - 'drs:CreateSourceNetwork'
              - 'drs:DeleteSourceNetwork'
              - 'drs:DeleteJob'
              # Tag management
              - 'drs:TagResource'
              - 'drs:UntagResource'
              # CRITICAL: Required for DRS to register recovery instances
              - 'drs:CreateRecoveryInstanceForDrs'
            Resource: '*'
          
          # EC2 Read Operations (required by DRS)
          - Sid: EC2ReadOperations
            Effect: Allow
            Action:
              - 'ec2:DescribeInstances'
              - 'ec2:DescribeInstanceStatus'
              - 'ec2:DescribeInstanceTypes'
              - 'ec2:DescribeInstanceTypeOfferings'
              - 'ec2:DescribeInstanceAttribute'
              - 'ec2:DescribeAccountAttributes'
              - 'ec2:DescribeLaunchTemplates'
              - 'ec2:DescribeLaunchTemplateVersions'
              - 'ec2:DescribeAvailabilityZones'
              - 'ec2:DescribeNetworkInterfaces'
              - 'ec2:DescribeVolumes'
              - 'ec2:DescribeVolumeAttribute'
              - 'ec2:DescribeSnapshots'
              - 'ec2:DescribeSubnets'
              - 'ec2:DescribeSecurityGroups'
              - 'ec2:DescribeVpcs'
              - 'ec2:DescribeImages'
              - 'ec2:DescribeTags'
              - 'ec2:GetEbsDefaultKmsKeyId'
              - 'ec2:GetEbsEncryptionByDefault'
            Resource: '*'
          
          # EC2 Write Operations (required by DRS for recovery)
          - Sid: EC2WriteOperations
            Effect: Allow
            Action:
              - 'ec2:RunInstances'
              - 'ec2:StartInstances'
              - 'ec2:StopInstances'
              - 'ec2:TerminateInstances'
              - 'ec2:ModifyInstanceAttribute'
              - 'ec2:CreateVolume'
              - 'ec2:AttachVolume'
              - 'ec2:DetachVolume'
              - 'ec2:DeleteVolume'
              - 'ec2:ModifyVolume'
              - 'ec2:CreateLaunchTemplate'
              - 'ec2:CreateLaunchTemplateVersion'
              - 'ec2:ModifyLaunchTemplate'
              - 'ec2:DeleteLaunchTemplate'
              - 'ec2:DeleteLaunchTemplateVersions'
              - 'ec2:CreateNetworkInterface'
              - 'ec2:AttachNetworkInterface'
              - 'ec2:DeleteNetworkInterface'
              - 'ec2:ModifyNetworkInterfaceAttribute'
              - 'ec2:CreateTags'
              - 'ec2:CreateSecurityGroup'
              # Snapshot/AMI operations (required for DRS drill conversions)
              - 'ec2:CreateSnapshot'
              - 'ec2:DeleteSnapshot'
              - 'ec2:CreateImage'
              - 'ec2:DeregisterImage'
              - 'ec2:CopyImage'
              - 'ec2:RegisterImage'
            Resource: '*'
          
          # SSM Operations (for DRS agent deployment)
          - Sid: SSMOperations
            Effect: Allow
            Action:
              # Document operations
              - 'ssm:ListDocuments'
              - 'ssm:DescribeDocument'
              - 'ssm:GetDocument'
              # Command execution
              - 'ssm:SendCommand'
              - 'ssm:ListCommands'
              - 'ssm:ListCommandInvocations'
              - 'ssm:GetCommandInvocation'
              - 'ssm:CancelCommand'
              # Instance management
              - 'ssm:DescribeInstanceInformation'
              - 'ssm:DescribeInstanceProperties'
              - 'ssm:GetConnectionStatus'
              # Automation
              - 'ssm:StartAutomationExecution'
              - 'ssm:DescribeAutomationExecutions'
              - 'ssm:GetAutomationExecution'
              - 'ssm:StopAutomationExecution'
            Resource: '*'
          
          # IAM Operations (for instance profiles and role passing)
          - Sid: IAMReadOperations
            Effect: Allow
            Action:
              - 'iam:ListInstanceProfiles'
              - 'iam:GetInstanceProfile'
              - 'iam:ListRoles'
              - 'iam:GetRole'
            Resource: '*'
          
          # IAM PassRole (for DRS service roles and EC2 instance profiles)
          - Sid: IAMPassRoleDRS
            Effect: Allow
            Action:
              - 'iam:PassRole'
            Resource:
              - !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/service-role/AWSElasticDisasterRecoveryReplicationServerRole'
              - !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/service-role/AWSElasticDisasterRecoveryConversionServerRole'
              - !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/service-role/AWSElasticDisasterRecoveryRecoveryInstanceRole'
            Condition:
              StringEquals:
                'iam:PassedToService':
                  - 'drs.amazonaws.com'
                  - 'ec2.amazonaws.com'
          
          # IAM PassRole for EC2 instance profiles (required for recovery instances)
          # DRS needs to pass custom EC2 roles configured in launch settings
          - Sid: IAMPassRoleEC2
            Effect: Allow
            Action:
              - 'iam:PassRole'
            Resource:
              - !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/*'
            Condition:
              StringEquals:
                'iam:PassedToService': 'ec2.amazonaws.com'
          
          # S3 Operations (for DRS logs and artifacts)
          - Sid: S3Operations
            Effect: Allow
            Action:
              - 's3:ListAllMyBuckets'
              - 's3:GetBucketLocation'
              - 's3:GetObject'
              - 's3:PutObject'
              - 's3:DeleteObject'
              - 's3:ListBucket'
            Resource:
              - 'arn:aws:s3:::*drs*'
              - 'arn:aws:s3:::*drs*/*'
              - 'arn:aws:s3:::*orchestration*'
              - 'arn:aws:s3:::*orchestration*/*'
          
          # KMS Operations (for cross-account encryption)
          - Sid: KMSOperations
            Effect: Allow
            Action:
              - 'kms:Decrypt'
              - 'kms:Encrypt'
              - 'kms:DescribeKey'
              - 'kms:CreateGrant'
              - 'kms:ListGrants'
              - 'kms:RevokeGrant'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey*'
            Resource: '*'
          
          # EC2 Snapshot cross-account operations (required for DRS cross-account recovery)
          - Sid: EC2SnapshotCrossAccount
            Effect: Allow
            Action:
              - 'ec2:ModifySnapshotAttribute'
              - 'ec2:CopySnapshot'
            Resource: '*'

Outputs:
  RoleArn:
    Description: 'ARN of the DRS Orchestration cross-account role (standardized name: DRSOrchestrationRole)'
    Value: !GetAtt DRSOrchestrationRole.Arn
    Export:
      Name: !Sub '${ProjectName}-role-arn'
  
  RoleName:
    Description: 'Name of the DRS Orchestration role (standardized: DRSOrchestrationRole)'
    Value: !Ref DRSOrchestrationRole
    Export:
      Name: !Sub '${ProjectName}-role-name'
  
  ExternalId:
    Description: 'External ID for secure cross-account access (standardized: drs-orchestration-cross-account)'
    Value: !Ref ExternalId
    Export:
      Name: !Sub '${ProjectName}-external-id'
  
  AccountId:
    Description: 'Account ID where this role is deployed'
    Value: !Ref AWS::AccountId
    Export:
      Name: !Sub '${ProjectName}-account-id'
  
  OrchestrationAccountId:
    Description: 'Orchestration account ID that can assume this role'
    Value: !Ref OrchestrationAccountId
    Export:
      Name: !Sub '${ProjectName}-orchestration-account'
