AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS DRS Orchestration - Database Stack (DynamoDB Tables) - CamelCase Schema Migration'

Parameters:
  ProjectName:
    Type: String
    Default: 'aws-elasticdrs-orchestrator'
    Description: 'Project name used for resource naming'

  Environment:
    Type: String
    Default: 'dev'
    Description: 'Environment name (dev, test, prod)'

Resources:
  # Protection Groups Table - CamelCase Schema Migration
  ProtectionGroupsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-protection-groups-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: groupId
          AttributeType: S
      KeySchema:
        - AttributeName: groupId
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: TTL
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # Recovery Plans Table
  RecoveryPlansTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-recovery-plans-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: planId
          AttributeType: S
      KeySchema:
        - AttributeName: planId
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: TTL
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # Execution History Table
  ExecutionHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-execution-history-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: executionId
          AttributeType: S
        - AttributeName: planId
          AttributeType: S
        - AttributeName: startTime
          AttributeType: N
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: executionId
          KeyType: HASH
        - AttributeName: planId
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: planIdIndex
          KeySchema:
            - AttributeName: planId
              KeyType: HASH
            - AttributeName: startTime
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: statusIndex
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: startTime
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: TTL  # TTL attribute for automatic record expiration
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # Target Accounts Table
  TargetAccountsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-target-accounts-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: accountId
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: lastValidated
          AttributeType: S
      KeySchema:
        - AttributeName: accountId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: statusIndex
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: lastValidated
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: TTL
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

Outputs:
  ProtectionGroupsTableName:
    Description: 'DynamoDB table name for Protection Groups'
    Value: !Ref ProtectionGroupsTable
    Export:
      Name: !Sub '${AWS::StackName}-ProtectionGroupsTableName'

  ProtectionGroupsTableArn:
    Description: 'DynamoDB table ARN for Protection Groups'
    Value: !GetAtt ProtectionGroupsTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ProtectionGroupsTableArn'

  RecoveryPlansTableName:
    Description: 'DynamoDB table name for Recovery Plans'
    Value: !Ref RecoveryPlansTable
    Export:
      Name: !Sub '${AWS::StackName}-RecoveryPlansTableName'

  RecoveryPlansTableArn:
    Description: 'DynamoDB table ARN for Recovery Plans'
    Value: !GetAtt RecoveryPlansTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-RecoveryPlansTableArn'

  ExecutionHistoryTableName:
    Description: 'DynamoDB table name for Execution History'
    Value: !Ref ExecutionHistoryTable
    Export:
      Name: !Sub '${AWS::StackName}-ExecutionHistoryTableName'

  ExecutionHistoryTableArn:
    Description: 'DynamoDB table ARN for Execution History'
    Value: !GetAtt ExecutionHistoryTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ExecutionHistoryTableArn'

  TargetAccountsTableName:
    Description: 'DynamoDB table name for Target Accounts'
    Value: !Ref TargetAccountsTable
    Export:
      Name: !Sub '${AWS::StackName}-TargetAccountsTableName'

  TargetAccountsTableArn:
    Description: 'DynamoDB table ARN for Target Accounts'
    Value: !GetAtt TargetAccountsTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-TargetAccountsTableArn'
