AWSTemplateFormatVersion: '2010-09-09'
Description: |
  DRS Agent Installer SSM Document - Creates SSM document for installing AWS DRS
  Replication Agent with cross-account support. Based on AWS-provided
  AWSDisasterRecovery-InstallDRAgentOnInstance with added AccountId parameter.
  Supports Windows (PowerShell) and Linux (Shell/Python). Features: SHA512
  checksum validation, dual-stack URLs with fallback, temp directory cleanup.
  Usage: aws ssm send-command --document-name DRS-InstallAgentCrossAccount-{env}
  --targets Key=instanceids,Values=i-xxx --parameters Region=us-east-1,AccountId=111122223333

# =============================================================================
# COMPARISON WITH AWS MANAGED DOCUMENT
# =============================================================================
# This document is based on AWS-provided AWSDisasterRecovery-InstallDRAgentOnInstance.
# All original functionality is preserved with the addition of cross-account support.
#
# Identical Features (verified against AWS managed document):
# - Region parameter: All 28 DRS-supported regions
# - Tags parameter: Same validation pattern and processing logic
# - Windows: TLS 1.2 enforcement, dual-stack URLs with fallback
# - Windows: SHA512 checksum validation (PowerShell 3.x and 4.x+ compatible)
# - Windows: Tag parsing and argument construction
# - Windows: Temporary directory creation and cleanup
# - Windows: Comprehensive error handling with stack traces
# - Linux: Dual-stack download URLs with fallback
# - Linux: SHA512 checksum validation using sha512sum
# - Linux: Python 2/3 auto-detection (python3 preferred)
# - Linux: Tag processing via Python script
# - Linux: File cleanup after installation
# - Both: 3600 second (1 hour) timeout
#
# Added Enhancement:
# - AccountId parameter: 12-digit AWS account ID for cross-account replication
#   - Windows: $requestedAccountId variable, --account-id argument
#   - Linux: account_id variable in Python script, --account-id argument
#   - Leave empty for same-account replication (default behavior)

# =============================================================================
# PARAMETERS
# =============================================================================

Parameters:
  ProjectName:
    Type: String
    Description: 'Project name used for resource naming'
  
  Environment:
    Type: String
    Description: 'Environment name (dev, test, prod)'

# =============================================================================
# RESOURCES
# =============================================================================

Resources:
  # ===========================================================================
  # SSM DOCUMENT: DRS AGENT INSTALLER
  # ===========================================================================
  # Custom SSM document extending AWS-provided DRS agent installer.
  # 
  # Key Enhancements over AWS default:
  # - AccountId parameter for cross-account replication
  # - Enables hub-and-spoke DR architecture where source servers in multiple
  #   accounts replicate to a central DR account
  # 
  # Document Parameters:
  # - Region: Target AWS region for DRS replication (required)
  # - AccountId: Target account for cross-account setup (optional)
  # - Tags: Resource tags for the source server (optional)
  #
  # Installation Flow:
  # 1. Create temporary directory
  # 2. Download installer and SHA512 hash (dual-stack with fallback)
  # 3. Validate checksum
  # 4. Execute installer with region, account-id (if provided), and tags
  # 5. Clean up temporary files
  # 6. Return exit code
  DRSAgentInstallerDocument:
    Type: AWS::SSM::Document
    Properties:
      Name: !Sub 'DRS-InstallAgentCrossAccount-${Environment}'
      DocumentType: Command
      DocumentFormat: YAML
      Content:
        description: |
          Install AWS Elastic Disaster Recovery (DRS) Replication Agent with cross-account support.
          Based on AWS-provided AWSDisasterRecovery-InstallDRAgentOnInstance with added AccountId parameter.
        schemaVersion: '2.2'
        parameters:
          Region:
            type: String
            description: (Required) AWS Region into which you are replicating.
            allowedValues:
              - us-east-1
              - us-east-2
              - us-west-1
              - us-west-2
              - ap-southeast-1
              - ap-southeast-2
              - ap-southeast-3
              - ap-northeast-1
              - ap-northeast-2
              - ap-northeast-3
              - eu-central-1
              - eu-west-1
              - eu-west-2
              - eu-west-3
              - ca-central-1
              - ap-south-1
              - sa-east-1
              - eu-north-1
              - me-south-1
              - af-south-1
              - ap-east-1
              - eu-south-1
              - eu-central-2
              - eu-south-2
              - ap-south-2
              - ap-southeast-4
              - me-central-1
              - il-central-1
          AccountId:
            type: String
            description: (Optional) Target AWS Account ID for cross-account replication. Leave empty for same-account replication.
            default: ""
            allowedPattern: "^(\\d{12})?$"
          Tags:
            type: String
            description: (Optional) Use this parameter to add resource tags to the Source server. Use a comma to separate each tag (for example --tags KEY=VALUE,[KEY=VALUE]...)
            default: ""
            allowedPattern: "^(([a-zA-Z_0-9.:+/@\\-]{1,50}=[a-zA-Z_0-9.:+/@ \\-]{1,50})(,[a-zA-Z_0-9.:+/@\\-]{1,50}=[a-zA-Z_0-9.:+/@ \\-]{1,50}){0,20})?$"
        mainSteps:
          - action: aws:runPowerShellScript
            name: InstallWindowsAgent
            precondition:
              StringEquals:
                - platformType
                - Windows
            inputs:
              timeoutSeconds: '3600'
              runCommand:
                - "try {"
                - "[string] $parent = [System.IO.Path]::GetTempPath()"
                - "[string] $name = [System.Guid]::NewGuid()"
                - "$tmpDir = New-Item -ItemType Directory -Path (Join-Path $parent $name)"
                - "cd $tmpDir"
                - "}"
                - "catch {"
                - "Write-Error \"Failed while creating temporary directory for script invocation\""
                - "exit 1"
                - "}"
                - "try {"
                - "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::tls12"
                - "$webClient = New-Object System.Net.WebClient"
                - "try {"
                - "$webClient.DownloadFile('https://aws-elastic-disaster-recovery-{{Region}}.s3.dualstack.{{Region}}.amazonaws.com/latest/windows/AwsReplicationWindowsInstaller.exe', (Join-Path $tmpDir 'AwsReplicationWindowsInstaller.exe'))"
                - "$webClient.DownloadFile('https://aws-elastic-disaster-recovery-hashes-{{Region}}.s3.dualstack.{{Region}}.amazonaws.com/latest/windows/AwsReplicationWindowsInstaller.exe.sha512', (Join-Path $tmpDir 'AwsReplicationWindowsInstaller.exe.sha512'))"
                - "} catch {"
                - "Write-Warning \"Primary download failed, trying fallback URLs\""
                - "$webClient.DownloadFile('https://aws-elastic-disaster-recovery-{{Region}}.s3.{{Region}}.amazonaws.com/latest/windows/AwsReplicationWindowsInstaller.exe', (Join-Path $tmpDir 'AwsReplicationWindowsInstaller.exe'))"
                - "$webClient.DownloadFile('https://aws-elastic-disaster-recovery-hashes-{{Region}}.s3.{{Region}}.amazonaws.com/latest/windows/AwsReplicationWindowsInstaller.exe.sha512', (Join-Path $tmpDir 'AwsReplicationWindowsInstaller.exe.sha512'))"
                - "}"
                - "}"
                - "catch {"
                - "Write-Error \"Failed while trying to download the AWS Elastic Disaster Recovery client from both URLs\""
                - "cd .."
                - "Remove-Item -Force -Recurse $tmpDir"
                - "exit 1"
                - "}"
                - "try {"
                - "$psMajorVersion=$PSVersionTable.PSVersion.Major"
                - "if ( $psMajorVersion -lt 4 ) {"
                - "$hashAlgorithm = [Security.Cryptography.HashAlgorithm]::Create(\"SHA512\")"
                - "$fileBytes = [io.File]::ReadAllBytes((Join-Path $tmpDir 'AwsReplicationWindowsInstaller.exe'))"
                - "$hashBytes = $hashAlgorithm.ComputeHash($fileBytes)"
                - "$fileHash = -Join ($hashBytes | ForEach {\"{0:x2}\" -f $_})"
                - "} else {"
                - "$hashObject = Get-FileHash -Algorithm SHA512 -Path AwsReplicationWindowsInstaller.exe"
                - "$fileHash = $hashObject.Hash"
                - "}"
                - "$hash = Get-Content AwsReplicationWindowsInstaller.exe.sha512"
                - "}"
                - "catch {"
                - "cd .."
                - "Remove-Item -Force -Recurse $tmpDir"
                - "Write-Error \"Failed while trying to verify downloaded client hash\""
                - "exit 1"
                - "}"
                - "try {"
                - "if($fileHash -eq $hash){"
                - "$requestedTags=\"{{Tags}}\""
                - "$tagList=$requestedTags.split(',')"
                - "$finalTags=\"\""
                - "foreach ($tag in $tagList){"
                - "$tagKeyVal=$tag.split('=')"
                - "$tagKey=$tagKeyVal[0]"
                - "$tagVal=$tagKeyVal[1]"
                - "$finalTags=$finalTags+' '+$tagKey+'='+'\"'+$tagVal+'\"'"
                - "}"
                - "$requestedAccountId=\"{{AccountId}}\""
                - "$process = New-object System.Diagnostics.Process"
                - "$startInfo = New-object System.Diagnostics.ProcessStartInfo"
                - "$startInfo.FileName = (Join-Path $tmpDir 'AwsReplicationWindowsInstaller.exe')"
                - "$baseArgs = \"--no-prompt --region {{Region}}\""
                - "if ( $requestedAccountId ) { $baseArgs = $baseArgs + \" --account-id $requestedAccountId\" }"
                - "if ( $requestedTags ) { $baseArgs = $baseArgs + \" --tags $finalTags\" }"
                - "$startInfo.Arguments = $baseArgs"
                - "$startInfo.WorkingDirectory=$tmpDir"
                - "$startInfo.UseShellExecute=$False"
                - "$process.StartInfo = $startInfo"
                - "$process.Start()"
                - "$process.WaitForExit()"
                - "$result = $process.ExitCode"
                - "}else{"
                - "Write-Error \"Checksum validation failed\""
                - "cd .."
                - "Remove-Item -Force -Recurse $tmpDir"
                - "exit 1"
                - "}"
                - "cd .."
                - "Remove-Item -Force -Recurse -Path $tmpDir"
                - "if( $result -ne 0 ){"
                - "Write-Error \"Installation failed\""
                - "exit $result"
                - "}"
                - "}"
                - "catch {"
                - "Write-Error \"General error during agent installation\""
                - "Write-Error $_"
                - "Write-Error $_.ScriptStackTrace"
                - "cd .."
                - "Remove-Item -Force -Recurse $tmpDir"
                - "exit 1"
                - "}"
          - action: aws:runShellScript
            name: InstallLinuxAgent
            precondition:
              StringEquals:
                - platformType
                - Linux
            inputs:
              timeoutSeconds: '3600'
              runCommand:
                - "sudo curl -o ./aws-installer.sha512 https://aws-elastic-disaster-recovery-hashes-{{ Region }}.s3.dualstack.{{ Region }}.amazonaws.com/latest/linux/aws-replication-installer-init.sha512 || sudo curl -o ./aws-installer.sha512 https://aws-elastic-disaster-recovery-hashes-{{ Region }}.s3.{{ Region }}.amazonaws.com/latest/linux/aws-replication-installer-init.sha512"
                - "asset_hash=$(cat ./aws-installer.sha512)"
                - "sudo curl -o ./aws-replication-installer-init https://aws-elastic-disaster-recovery-{{ Region }}.s3.dualstack.{{ Region }}.amazonaws.com/latest/linux/aws-replication-installer-init || sudo curl -o ./aws-replication-installer-init https://aws-elastic-disaster-recovery-{{ Region }}.s3.{{ Region }}.amazonaws.com/latest/linux/aws-replication-installer-init"
                - "computed_hash=$(sha512sum ./aws-replication-installer-init | cut -d' ' -f1)"
                - "if [ \"$computed_hash\" != \"$asset_hash\" ]; then"
                - "echo \"Checksum validation failed\" >&2"
                - "else"
                - "pyexec=python3"
                - "which python3"
                - "ispy3=$?"
                - "if [ $ispy3 -eq 1 ]; then pyexec=python; fi"
                - "cat << EOF > install_agent.py"
                - "#!/usr/bin/python"
                - "import subprocess"
                - "import shlex"
                - "raw_cmd = \"./aws-replication-installer-init --no-prompt --region {0} \".format('{{ Region }}')"
                - "account_id = '{{ AccountId }}'"
                - "if account_id:"
                - "  raw_cmd += \"--account-id {0} \".format(account_id)"
                - "cmd = shlex.split(raw_cmd)"
                - "if len('{{ Tags }}' ) > 0:"
                - "  tags_to_split='{{ Tags }}'"
                - "  tags=tags_to_split.split(',')"
                - "  cmd.append(\"--tags\")"
                - "  for tag in tags:"
                - "    cmd.append(tag)"
                - "try:"
                - "   response = subprocess.check_output(cmd, shell=False)"
                - "except Exception as e:"
                - "   print(e)"
                - "   exit(1)"
                - "exit(0)"
                - "EOF"
                - "chmod +x ./aws-replication-installer-init"
                - "chmod +x install_agent.py"
                - "$pyexec install_agent.py"
                - "result=$?"
                - "fi"
                - "rm -f ./aws-installer.sha512 ./aws-replication-installer-init"
                - "rm -f install_agent.py"
                - "exit $result"
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

# =============================================================================
# OUTPUTS
# =============================================================================
# Exported values for use in automation and cross-stack references.

Outputs:
  # Document name for use in SSM Run Command
  DocumentName:
    Description: 'SSM Document name for DRS Agent installation'
    Value: !Ref DRSAgentInstallerDocument
    Export:
      Name: !Sub '${AWS::StackName}-DocumentName'
  
  # Document ARN for IAM policies and automation
  DocumentArn:
    Description: 'SSM Document ARN for DRS Agent installation'
    Value: !Sub 'arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:document/${DRSAgentInstallerDocument}'
    Export:
      Name: !Sub '${AWS::StackName}-DocumentArn'
