AWSTemplateFormatVersion: '2010-09-09'
Description: |
  DRS Target/Staging Account Setup - Combined stack for deploying cross-account
  IAM role and SSM agent installer document. Deploy this template in each target
  or staging account that the DRS Orchestration platform needs to manage.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'Orchestration Account Configuration'
        Parameters:
          - OrchestrationAccountId
      - Label:
          default: 'Project Configuration'
        Parameters:
          - ProjectName
          - Environment

Parameters:
  OrchestrationAccountId:
    Description: 'AWS Account ID where DRS Orchestration platform is deployed'
    Type: String
    AllowedPattern: '[0-9]{12}'
    ConstraintDescription: 'Must be a valid 12-digit AWS account ID'
  
  ProjectName:
    Type: String
    Description: 'Project name for resource naming'
    Default: 'drs-orchestration'
  
  Environment:
    Type: String
    Description: 'Environment name (dev, test, prod, qa)'
    Default: 'prod'

Resources:
  # Cross-Account IAM Role
  DRSOrchestrationRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Delete
    Properties:
      RoleName: DRSOrchestrationRole
      Description: !Sub 'Cross-account role for DRS Orchestration (${OrchestrationAccountId}) to manage DRS in ${AWS::AccountId}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: 
                - !Sub 'arn:${AWS::Partition}:iam::${OrchestrationAccountId}:root'
            Action: 'sts:AssumeRole'
            Condition:
              StringEquals:
                'sts:ExternalId': !Sub '${ProjectName}-${Environment}'
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/AWSElasticDisasterRecoveryConsoleFullAccess'
      Tags:
        - Key: Name
          Value: DRSOrchestrationRole
        - Key: ManagedBy
          Value: CloudFormation
        - Key: OrchestrationAccount
          Value: !Ref OrchestrationAccountId

  # Inline Policy for DRS Operations
  DRSOrchestrationPolicy:
    Type: AWS::IAM::Policy
    DeletionPolicy: Delete
    Properties:
      PolicyName: DRSOrchestrationPolicy
      Roles:
        - !Ref DRSOrchestrationRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DRSCoreOperations
            Effect: Allow
            Action:
              - 'drs:*'
            Resource: '*'
          - Sid: EC2Operations
            Effect: Allow
            Action:
              - 'ec2:Describe*'
              - 'ec2:Get*'
              - 'ec2:RunInstances'
              - 'ec2:StartInstances'
              - 'ec2:StopInstances'
              - 'ec2:TerminateInstances'
              - 'ec2:ModifyInstanceAttribute'
              - 'ec2:CreateVolume'
              - 'ec2:AttachVolume'
              - 'ec2:DetachVolume'
              - 'ec2:DeleteVolume'
              - 'ec2:ModifyVolume'
              - 'ec2:CreateLaunchTemplate'
              - 'ec2:CreateLaunchTemplateVersion'
              - 'ec2:ModifyLaunchTemplate'
              - 'ec2:DeleteLaunchTemplate'
              - 'ec2:DeleteLaunchTemplateVersions'
              - 'ec2:CreateNetworkInterface'
              - 'ec2:AttachNetworkInterface'
              - 'ec2:DeleteNetworkInterface'
              - 'ec2:ModifyNetworkInterfaceAttribute'
              - 'ec2:CreateTags'
              - 'ec2:CreateSecurityGroup'
              - 'ec2:CreateSnapshot'
              - 'ec2:DeleteSnapshot'
              - 'ec2:CreateImage'
              - 'ec2:DeregisterImage'
              - 'ec2:CopyImage'
              - 'ec2:RegisterImage'
              - 'ec2:ModifySnapshotAttribute'
              - 'ec2:CopySnapshot'
            Resource: '*'
          - Sid: SSMOperations
            Effect: Allow
            Action:
              - 'ssm:ListDocuments'
              - 'ssm:DescribeDocument'
              - 'ssm:GetDocument'
              - 'ssm:SendCommand'
              - 'ssm:ListCommands'
              - 'ssm:ListCommandInvocations'
              - 'ssm:GetCommandInvocation'
              - 'ssm:CancelCommand'
              - 'ssm:DescribeInstanceInformation'
              - 'ssm:DescribeInstanceProperties'
              - 'ssm:GetConnectionStatus'
              - 'ssm:StartAutomationExecution'
              - 'ssm:DescribeAutomationExecutions'
              - 'ssm:GetAutomationExecution'
              - 'ssm:StopAutomationExecution'
            Resource: '*'
          - Sid: IAMReadOperations
            Effect: Allow
            Action:
              - 'iam:ListInstanceProfiles'
              - 'iam:GetInstanceProfile'
              - 'iam:ListRoles'
              - 'iam:GetRole'
            Resource: '*'
          - Sid: IAMPassRoleDRS
            Effect: Allow
            Action:
              - 'iam:PassRole'
            Resource:
              - !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/service-role/AWSElasticDisasterRecoveryReplicationServerRole'
              - !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/service-role/AWSElasticDisasterRecoveryConversionServerRole'
              - !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/service-role/AWSElasticDisasterRecoveryRecoveryInstanceRole'
            Condition:
              StringEquals:
                'iam:PassedToService':
                  - 'drs.amazonaws.com'
                  - 'ec2.amazonaws.com'
          - Sid: IAMPassRoleEC2
            Effect: Allow
            Action:
              - 'iam:PassRole'
            Resource:
              - !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/*'
            Condition:
              StringEquals:
                'iam:PassedToService': 'ec2.amazonaws.com'
          - Sid: S3Operations
            Effect: Allow
            Action:
              - 's3:ListAllMyBuckets'
              - 's3:GetBucketLocation'
              - 's3:GetObject'
              - 's3:PutObject'
              - 's3:DeleteObject'
              - 's3:ListBucket'
            Resource:
              - 'arn:aws:s3:::*drs*'
              - 'arn:aws:s3:::*drs*/*'
              - 'arn:aws:s3:::*orchestration*'
              - 'arn:aws:s3:::*orchestration*/*'
          - Sid: KMSOperations
            Effect: Allow
            Action:
              - 'kms:Decrypt'
              - 'kms:Encrypt'
              - 'kms:DescribeKey'
              - 'kms:CreateGrant'
              - 'kms:ListGrants'
              - 'kms:RevokeGrant'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey*'
            Resource: '*'

  # SSM Document for DRS Agent Installation
  DRSAgentInstallerDocument:
    Type: AWS::SSM::Document
    DeletionPolicy: Delete
    Properties:
      Name: 'DRS-InstallAgent-CrossAccount'
      DocumentType: Command
      DocumentFormat: YAML
      Content:
        description: 'Install AWS DRS Replication Agent with cross-account support'
        schemaVersion: '2.2'
        parameters:
          Region:
            type: String
            description: (Required) AWS Region for DRS replication
            allowedValues:
              - us-east-1
              - us-east-2
              - us-west-1
              - us-west-2
              - eu-west-1
              - eu-west-2
              - eu-west-3
              - eu-central-1
              - ap-northeast-1
              - ap-northeast-2
              - ap-northeast-3
              - ap-southeast-1
              - ap-southeast-2
              - ap-south-1
              - ca-central-1
              - sa-east-1
              - eu-north-1
              - ap-east-1
          AccountId:
            type: String
            description: (Optional) Target AWS Account ID for cross-account replication
            default: ""
            allowedPattern: "^(\\d{12})?$"
          Tags:
            type: String
            description: (Optional) Resource tags (KEY=VALUE,KEY=VALUE)
            default: ""
            allowedPattern: "^(([a-zA-Z_0-9.:+/@\\-]{1,50}=[a-zA-Z_0-9.:+/@ \\-]{1,50})(,[a-zA-Z_0-9.:+/@\\-]{1,50}=[a-zA-Z_0-9.:+/@ \\-]{1,50}){0,20})?$"
        mainSteps:
          - action: aws:runPowerShellScript
            name: InstallWindowsAgent
            precondition:
              StringEquals:
                - platformType
                - Windows
            inputs:
              timeoutSeconds: '3600'
              runCommand:
                - "try { $tmpDir = New-Item -ItemType Directory -Path (Join-Path ([System.IO.Path]::GetTempPath()) ([System.Guid]::NewGuid())); cd $tmpDir } catch { Write-Error 'Failed creating temp directory'; exit 1 }"
                - "try { [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::tls12; $webClient = New-Object System.Net.WebClient; try { $webClient.DownloadFile('https://aws-elastic-disaster-recovery-{{Region}}.s3.dualstack.{{Region}}.amazonaws.com/latest/windows/AwsReplicationWindowsInstaller.exe', (Join-Path $tmpDir 'AwsReplicationWindowsInstaller.exe')); $webClient.DownloadFile('https://aws-elastic-disaster-recovery-hashes-{{Region}}.s3.dualstack.{{Region}}.amazonaws.com/latest/windows/AwsReplicationWindowsInstaller.exe.sha512', (Join-Path $tmpDir 'AwsReplicationWindowsInstaller.exe.sha512')) } catch { Write-Warning 'Primary download failed, trying fallback'; $webClient.DownloadFile('https://aws-elastic-disaster-recovery-{{Region}}.s3.{{Region}}.amazonaws.com/latest/windows/AwsReplicationWindowsInstaller.exe', (Join-Path $tmpDir 'AwsReplicationWindowsInstaller.exe')); $webClient.DownloadFile('https://aws-elastic-disaster-recovery-hashes-{{Region}}.s3.{{Region}}.amazonaws.com/latest/windows/AwsReplicationWindowsInstaller.exe.sha512', (Join-Path $tmpDir 'AwsReplicationWindowsInstaller.exe.sha512')) } } catch { Write-Error 'Download failed'; cd ..; Remove-Item -Force -Recurse $tmpDir; exit 1 }"
                - "try { if ($PSVersionTable.PSVersion.Major -lt 4) { $hashAlgorithm = [Security.Cryptography.HashAlgorithm]::Create('SHA512'); $fileBytes = [io.File]::ReadAllBytes((Join-Path $tmpDir 'AwsReplicationWindowsInstaller.exe')); $hashBytes = $hashAlgorithm.ComputeHash($fileBytes); $fileHash = -Join ($hashBytes | ForEach {\"{0:x2}\" -f $_}) } else { $hashObject = Get-FileHash -Algorithm SHA512 -Path AwsReplicationWindowsInstaller.exe; $fileHash = $hashObject.Hash }; $hash = Get-Content AwsReplicationWindowsInstaller.exe.sha512 } catch { cd ..; Remove-Item -Force -Recurse $tmpDir; Write-Error 'Hash verification failed'; exit 1 }"
                - "try { if($fileHash -eq $hash){ $requestedTags='{{Tags}}'; $tagList=$requestedTags.split(','); $finalTags=''; foreach ($tag in $tagList){ $tagKeyVal=$tag.split('='); $tagKey=$tagKeyVal[0]; $tagVal=$tagKeyVal[1]; $finalTags=$finalTags+' '+$tagKey+'='+'\"'+$tagVal+'\"' }; $requestedAccountId='{{AccountId}}'; $process = New-object System.Diagnostics.Process; $startInfo = New-object System.Diagnostics.ProcessStartInfo; $startInfo.FileName = (Join-Path $tmpDir 'AwsReplicationWindowsInstaller.exe'); $baseArgs = '--no-prompt --region {{Region}}'; if ( $requestedAccountId ) { $baseArgs = $baseArgs + \" --account-id $requestedAccountId\" }; if ( $requestedTags ) { $baseArgs = $baseArgs + \" --tags $finalTags\" }; $startInfo.Arguments = $baseArgs; $startInfo.WorkingDirectory=$tmpDir; $startInfo.UseShellExecute=$False; $process.StartInfo = $startInfo; $process.Start(); $process.WaitForExit(); $result = $process.ExitCode }else{ Write-Error 'Checksum validation failed'; cd ..; Remove-Item -Force -Recurse $tmpDir; exit 1 }; cd ..; Remove-Item -Force -Recurse -Path $tmpDir; if( $result -ne 0 ){ Write-Error 'Installation failed'; exit $result } } catch { Write-Error 'Installation error'; Write-Error $_; Write-Error $_.ScriptStackTrace; cd ..; Remove-Item -Force -Recurse $tmpDir; exit 1 }"
          - action: aws:runShellScript
            name: InstallLinuxAgent
            precondition:
              StringEquals:
                - platformType
                - Linux
            inputs:
              timeoutSeconds: '3600'
              runCommand:
                - "sudo curl -o ./aws-installer.sha512 https://aws-elastic-disaster-recovery-hashes-{{ Region }}.s3.dualstack.{{ Region }}.amazonaws.com/latest/linux/aws-replication-installer-init.sha512 || sudo curl -o ./aws-installer.sha512 https://aws-elastic-disaster-recovery-hashes-{{ Region }}.s3.{{ Region }}.amazonaws.com/latest/linux/aws-replication-installer-init.sha512"
                - "asset_hash=$(cat ./aws-installer.sha512)"
                - "sudo curl -o ./aws-replication-installer-init https://aws-elastic-disaster-recovery-{{ Region }}.s3.dualstack.{{ Region }}.amazonaws.com/latest/linux/aws-replication-installer-init || sudo curl -o ./aws-replication-installer-init https://aws-elastic-disaster-recovery-{{ Region }}.s3.{{ Region }}.amazonaws.com/latest/linux/aws-replication-installer-init"
                - "computed_hash=$(sha512sum ./aws-replication-installer-init | cut -d' ' -f1)"
                - "if [ \"$computed_hash\" != \"$asset_hash\" ]; then echo 'Checksum validation failed' >&2; else pyexec=python3; which python3; ispy3=$?; if [ $ispy3 -eq 1 ]; then pyexec=python; fi; cat << EOF > install_agent.py"
                - "#!/usr/bin/python"
                - "import subprocess"
                - "import shlex"
                - "raw_cmd = \"./aws-replication-installer-init --no-prompt --region {0} \".format('{{ Region }}')"
                - "account_id = '{{ AccountId }}'"
                - "if account_id:"
                - "  raw_cmd += \"--account-id {0} \".format(account_id)"
                - "cmd = shlex.split(raw_cmd)"
                - "if len('{{ Tags }}' ) > 0:"
                - "  tags_to_split='{{ Tags }}'"
                - "  tags=tags_to_split.split(',')"
                - "  cmd.append(\"--tags\")"
                - "  for tag in tags:"
                - "    cmd.append(tag)"
                - "try:"
                - "   response = subprocess.check_output(cmd, shell=False)"
                - "except Exception as e:"
                - "   print(e)"
                - "   exit(1)"
                - "exit(0)"
                - "EOF"
                - "chmod +x ./aws-replication-installer-init; chmod +x install_agent.py; $pyexec install_agent.py; result=$?; fi; rm -f ./aws-installer.sha512 ./aws-replication-installer-init install_agent.py; exit $result"
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

Outputs:
  RoleArn:
    Description: 'Cross-account role ARN'
    Value: !GetAtt DRSOrchestrationRole.Arn
    Export:
      Name: !Sub '${ProjectName}-role-arn'
  
  RoleName:
    Description: 'Cross-account role name'
    Value: !Ref DRSOrchestrationRole
    Export:
      Name: !Sub '${ProjectName}-role-name'
  
  ExternalId:
    Description: 'External ID for role assumption (auto-generated from ProjectName-Environment)'
    Value: !Sub '${ProjectName}-${Environment}'
    Export:
      Name: !Sub '${ProjectName}-external-id'
  
  DocumentName:
    Description: 'SSM Document name for DRS Agent installation'
    Value: !Ref DRSAgentInstallerDocument
    Export:
      Name: !Sub '${AWS::StackName}-DocumentName'
  
  DocumentArn:
    Description: 'SSM Document ARN'
    Value: !Sub 'arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:document/${DRSAgentInstallerDocument}'
    Export:
      Name: !Sub '${AWS::StackName}-DocumentArn'
