AWSTemplateFormatVersion: '2010-09-09'
Description: |
  AWS DRS Orchestration - EventBridge Scheduled Rules
  
  Automated scheduling for DR operations and data synchronization.
  
  Scheduled Operations:
  - Tag Sync (hourly): Synchronizes DRS tags to DynamoDB
  - Staging Account Sync (5 min): Discovers staging accounts
  - Weekly DR Drill (optional): Automated Wave 1 recovery drill
  - Monthly Full Drill (optional): Automated all-waves recovery drill
  
  Event-Driven Operations:
  - Manual Trigger: Custom EventBridge events for DR orchestration
  
  Integration Points:
  - Step Functions: DR orchestration state machine
  - API Handler: Tag synchronization operations
  - Data Management Handler: Staging account sync (write operations)
  - Query Handler: Read-only query operations
  
  Conditional Resources:
  - EnableTagSync: Controls tag synchronization (default: true)
  - EnableStagingAccountSync: Controls staging sync (default: true)
  - EnableWeeklyDrill: Controls scheduled drills (default: false)

# =============================================================================
# PARAMETERS
# =============================================================================

Parameters:
  ProjectName:
    Type: String
    Default: drs-orchestration
    Description: Project name for resource naming

  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, test, qa, uat, prod]
    Description: Deployment environment

  # ---------------------------------------------------------------------------
  # Step Functions Configuration
  # ---------------------------------------------------------------------------
  ModularOrchestratorArn:
    Type: String
    Description: ARN of the DR orchestration Step Function state machine

  # ---------------------------------------------------------------------------
  # DR Drill Configuration
  # ---------------------------------------------------------------------------
  EnableWeeklyDrill:
    Type: String
    Default: 'false'
    AllowedValues: ['true', 'false']
    Description: Enable weekly scheduled drill for Wave 1 (disabled by default)

  WeeklyDrillSchedule:
    Type: String
    Default: 'cron(0 6 ? * SAT *)'
    Description: 'Cron expression for weekly drill (default: Saturday 6 AM UTC)'

  DrillTags:
    Type: String
    Default: '{"DR-Wave":"1","DR-Enabled":"true"}'
    Description: JSON string of tags to filter servers for scheduled drills

  MaxWaitMinutes:
    Type: Number
    Default: 120
    Description: Maximum wait time for drill completion in minutes

  # ---------------------------------------------------------------------------
  # Tag Sync Configuration
  # ---------------------------------------------------------------------------
  EnableTagSync:
    Type: String
    Default: 'true'
    AllowedValues: ['true', 'false']
    Description: Enable hourly tag synchronization from DRS source servers

  ApiHandlerFunctionArn:
    Type: String
    Description: ARN of the API Handler Lambda for tag sync operations

  # ---------------------------------------------------------------------------
  # Staging Account Sync Configuration
  # ---------------------------------------------------------------------------
  QueryHandlerFunctionArn:
    Type: String
    Description: ARN of the Query Handler Lambda for read-only operations

  DataManagementHandlerFunctionArn:
    Type: String
    Description: ARN of the Data Management Handler Lambda for staging account sync operations

  ExecutionHandlerFunctionArn:
    Type: String
    Description: ARN of the Execution Handler Lambda for execution polling operations

  EnableExecutionPolling:
    Type: String
    Default: 'true'
    AllowedValues: ['true', 'false']
    Description: Enable automatic execution polling every 1 minute

  EnableStagingAccountSync:
    Type: String
    Default: 'true'
    AllowedValues: ['true', 'false']
    Description: Enable automatic staging account discovery every 5 minutes

  EnableInventorySync:
    Type: String
    Default: 'true'
    AllowedValues: ['true', 'false']
    Description: Enable automatic source server inventory sync every 15 minutes

  EnableRecoveryInstanceSync:
    Type: String
    Default: 'true'
    AllowedValues: ['true', 'false']
    Description: Enable automatic recovery instance sync every 5 minutes

Conditions:
  EnableWeeklyDrillCondition: !Equals [!Ref EnableWeeklyDrill, 'true']
  EnableTagSyncCondition: !Equals [!Ref EnableTagSync, 'true']
  EnableExecutionPollingCondition: !Equals [!Ref EnableExecutionPolling, 'true']
  EnableStagingAccountSyncCondition: !Equals [!Ref EnableStagingAccountSync, 'true']
  EnableInventorySyncCondition: !Equals [!Ref EnableInventorySync, 'true']
  EnableRecoveryInstanceSyncCondition: !Equals [!Ref EnableRecoveryInstanceSync, 'true']

# =============================================================================
# RESOURCES
# =============================================================================

Resources:
  # ===========================================================================
  # IAM ROLE FOR EVENTBRIDGE
  # ===========================================================================
  # Allows EventBridge to invoke Step Functions and Lambda functions.
  # Used by all scheduled rules and event-driven triggers.
  EventBridgeInvokeRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Delete
    Properties:
      RoleName: !Sub '${ProjectName}-eventbridge-invoke-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: InvokeStepFunctions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - states:StartExecution
                Resource: !Ref ModularOrchestratorArn
        - PolicyName: InvokeLambda
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !Ref ApiHandlerFunctionArn
                  - !Ref DataManagementHandlerFunctionArn
                  - !Ref QueryHandlerFunctionArn
                  - !Ref ExecutionHandlerFunctionArn

  # ===========================================================================
  # SCHEDULED DR DRILL RULES
  # ===========================================================================
  # Automated DR drills for compliance and readiness validation.
  # Disabled by default - enable via EnableWeeklyDrill parameter.
  
  # Weekly Drill: Wave 1 servers only (Saturday 6 AM UTC)
  # Filters servers by DR-Wave=1 and DR-Enabled=true tags
  # Runs as isDrill=true to auto-terminate recovery instances
  WeeklyDrillWave1Rule:
    Type: AWS::Events::Rule
    DeletionPolicy: Delete
    Condition: EnableWeeklyDrillCondition
    Properties:
      Name: !Sub '${ProjectName}-weekly-drill-wave1-${Environment}'
      Description: 'Weekly DR drill for Wave 1 servers'
      ScheduleExpression: !Ref WeeklyDrillSchedule
      State: ENABLED
      Targets:
        - Id: ModularOrchestratorTarget
          Arn: !Ref ModularOrchestratorArn
          RoleArn: !GetAtt EventBridgeInvokeRole.Arn
          Input: !Sub |
            {
              "action": "drill",
              "tags": ${DrillTags},
              "options": {
                "isDrill": true,
                "maxWaitMinutes": ${MaxWaitMinutes},
                "region": "${AWS::Region}"
              },
              "invocationSource": "EVENTBRIDGE",
              "invocationDetails": {
                "scheduleRuleName": "${ProjectName}-weekly-drill-wave1-${Environment}",
                "scheduleExpression": "${WeeklyDrillSchedule}"
              }
            }

  # Monthly Full Drill: All DR-enabled servers (1st of month, 6 AM UTC)
  # DISABLED by default - enable manually in AWS Console when ready
  # Includes all waves, longer timeout (240 min)
  MonthlyFullDrillRule:
    Type: AWS::Events::Rule
    DeletionPolicy: Delete
    Condition: EnableWeeklyDrillCondition
    Properties:
      Name: !Sub '${ProjectName}-monthly-full-drill-${Environment}'
      Description: 'Monthly full DR drill for all waves'
      ScheduleExpression: 'cron(0 6 1 * ? *)'  # First day of month, 6 AM UTC
      State: DISABLED  # Disabled by default, enable manually
      Targets:
        - Id: ModularOrchestratorTarget
          Arn: !Ref ModularOrchestratorArn
          RoleArn: !GetAtt EventBridgeInvokeRole.Arn
          Input: !Sub |
            {
              "action": "drill",
              "tags": {"DR-Enabled": "true"},
              "options": {
                "isDrill": true,
                "maxWaitMinutes": 240,
                "region": "${AWS::Region}"
              },
              "invocationSource": "EVENTBRIDGE",
              "invocationDetails": {
                "scheduleRuleName": "${ProjectName}-monthly-full-drill-${Environment}",
                "scheduleExpression": "cron(0 6 1 * ? *)"
              }
            }

  # ===========================================================================
  # MANUAL TRIGGER RULE
  # ===========================================================================
  # Allows programmatic DR orchestration via custom EventBridge events.
  # 
  # Usage: Send event to EventBridge with:
  #   Source: {ProjectName}.manual
  #   DetailType: DRS Orchestration Request
  #   Detail: { action, tags, options }
  #
  # Example AWS CLI:
  #   aws events put-events --entries '[{
  #     "Source": "drs-orchestration.manual",
  #     "DetailType": "DRS Orchestration Request",
  #     "Detail": "{\"action\":\"drill\",\"tags\":{\"DR-Wave\":\"1\"}}"
  #   }]'
  ManualTriggerRule:
    Type: AWS::Events::Rule
    DeletionPolicy: Delete
    Properties:
      Name: !Sub '${ProjectName}-manual-trigger-${Environment}'
      Description: 'Manual trigger for DRS orchestration via EventBridge'
      EventPattern:
        source:
          - !Sub '${ProjectName}.manual'
        detail-type:
          - 'DRS Orchestration Request'
      State: ENABLED
      Targets:
        - Id: ModularOrchestratorTarget
          Arn: !Ref ModularOrchestratorArn
          RoleArn: !GetAtt EventBridgeInvokeRole.Arn
          InputPath: '$.detail'

  # ===========================================================================
  # TAG SYNC SCHEDULED RULE
  # ===========================================================================
  # Hourly synchronization of DRS tags from source servers to DynamoDB.
  # Keeps the orchestration database current with EC2 tag changes.
  # Syncs both DR tags and instance type information.
  TagSyncScheduleRule:
    Type: AWS::Events::Rule
    DeletionPolicy: Delete
    Condition: EnableTagSyncCondition
    Properties:
      Name: !Sub '${ProjectName}-tag-sync-schedule-${Environment}'
      Description: 'Scheduled DRS tag synchronization every 1 hour'
      ScheduleExpression: 'rate(1 hour)'
      State: ENABLED
      Targets:
        - Id: TagSyncTarget
          Arn: !Ref ApiHandlerFunctionArn
          RoleArn: !GetAtt EventBridgeInvokeRole.Arn
          Input: '{"synch_tags": true, "synch_instance_type": true}'

  # Lambda permission for EventBridge to invoke API Handler
  TagSyncSchedulePermission:
    Type: AWS::Lambda::Permission
    DeletionPolicy: Delete
    Condition: EnableTagSyncCondition
    Properties:
      FunctionName: !Ref ApiHandlerFunctionArn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt TagSyncScheduleRule.Arn

  # ===========================================================================
  # STAGING ACCOUNT SYNC SCHEDULED RULE
  # ===========================================================================
  # Automatic discovery and sync of staging account configurations.
  # Runs every 5 minutes to detect new DRS staging accounts.
  # Populates TargetAccounts table with discovered account/region pairs.
  # Routes to Data Management Handler (write operations).
  StagingAccountSyncScheduleRule:
    Type: AWS::Events::Rule
    DeletionPolicy: Delete
    Condition: EnableStagingAccountSyncCondition
    Properties:
      Name: !Sub '${ProjectName}-staging-account-sync-${Environment}'
      Description: 'Automatic staging account discovery and sync every 5 minutes'
      ScheduleExpression: 'rate(5 minutes)'
      State: ENABLED
      Targets:
        - Id: StagingAccountSyncTarget
          Arn: !Ref DataManagementHandlerFunctionArn
          RoleArn: !GetAtt EventBridgeInvokeRole.Arn
          Input: '{"operation": "sync_staging_accounts"}'

  # Lambda permission for EventBridge to invoke Data Management Handler
  StagingAccountSyncSchedulePermission:
    Type: AWS::Lambda::Permission
    DeletionPolicy: Delete
    Condition: EnableStagingAccountSyncCondition
    Properties:
      FunctionName: !Ref DataManagementHandlerFunctionArn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt StagingAccountSyncScheduleRule.Arn

  # ---------------------------------------------------------------------------
  # Source Server Inventory Sync (every 15 minutes)
  # ---------------------------------------------------------------------------
  InventorySyncScheduleRule:
    Type: AWS::Events::Rule
    DeletionPolicy: Delete
    Condition: EnableInventorySyncCondition
    Properties:
      Name: !Sub '${ProjectName}-inventory-sync-${Environment}'
      Description: 'Sync source server inventory from DRS and EC2 every 15 minutes'
      ScheduleExpression: 'rate(15 minutes)'
      State: ENABLED
      Targets:
        - Id: InventorySyncTarget
          Arn: !Ref DataManagementHandlerFunctionArn
          RoleArn: !GetAtt EventBridgeInvokeRole.Arn
          Input: '{"operation": "sync_source_server_inventory"}'

  InventorySyncSchedulePermission:
    Type: AWS::Lambda::Permission
    DeletionPolicy: Delete
    Condition: EnableInventorySyncCondition
    Properties:
      FunctionName: !Ref DataManagementHandlerFunctionArn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt InventorySyncScheduleRule.Arn

  # ---------------------------------------------------------------------------
  # Recovery Instance Sync (every 5 minutes)
  # ---------------------------------------------------------------------------
  RecoveryInstanceSyncScheduleRule:
    Type: AWS::Events::Rule
    DeletionPolicy: Delete
    Condition: EnableRecoveryInstanceSyncCondition
    Properties:
      Name: !Sub '${ProjectName}-recovery-instance-sync-${Environment}'
      Description: 'Sync recovery instance data from DRS and EC2 every 5 minutes'
      ScheduleExpression: 'rate(5 minutes)'
      State: ENABLED
      Targets:
        - Id: RecoveryInstanceSyncTarget
          Arn: !Ref DataManagementHandlerFunctionArn
          RoleArn: !GetAtt EventBridgeInvokeRole.Arn
          Input: '{"operation": "sync_recovery_instances"}'

  RecoveryInstanceSyncSchedulePermission:
    Type: AWS::Lambda::Permission
    DeletionPolicy: Delete
    Condition: EnableRecoveryInstanceSyncCondition
    Properties:
      FunctionName: !Ref DataManagementHandlerFunctionArn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt RecoveryInstanceSyncScheduleRule.Arn

  # ---------------------------------------------------------------------------
  # Execution Polling (every 1 minute)
  # ---------------------------------------------------------------------------
  ExecutionPollingScheduleRule:
    Type: AWS::Events::Rule
    DeletionPolicy: Delete
    Condition: EnableExecutionPollingCondition
    Properties:
      Name: !Sub '${ProjectName}-execution-polling-schedule-${Environment}'
      Description: 'Poll active DR executions for status updates every 1 minute'
      ScheduleExpression: 'rate(1 minute)'
      State: ENABLED
      Targets:
        - Id: ExecutionPollingTarget
          Arn: !Ref ExecutionHandlerFunctionArn
          RoleArn: !GetAtt EventBridgeInvokeRole.Arn
          Input: '{"operation": "find"}'

  ExecutionPollingSchedulePermission:
    Type: AWS::Lambda::Permission
    DeletionPolicy: Delete
    DeletionPolicy: Delete
    Condition: EnableExecutionPollingCondition
    Properties:
      FunctionName: !Ref ExecutionHandlerFunctionArn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ExecutionPollingScheduleRule.Arn

# =============================================================================
# OUTPUTS
# =============================================================================
# Exported values for cross-stack references and operational monitoring.

Outputs:
  # IAM role ARN for other stacks that need EventBridge integration
  EventBridgeInvokeRoleArn:
    Description: ARN of the EventBridge invoke role
    Value: !GetAtt EventBridgeInvokeRole.Arn
    Export:
      Name: !Sub '${ProjectName}-eventbridge-role-${Environment}'

  # DR Drill rule outputs (conditional)
  WeeklyDrillRuleName:
    Condition: EnableWeeklyDrillCondition
    Description: Name of the weekly drill rule
    Value: !Ref WeeklyDrillWave1Rule

  # Manual trigger outputs for programmatic DR orchestration
  ManualTriggerRuleName:
    Description: Name of the manual trigger rule
    Value: !Ref ManualTriggerRule

  ManualTriggerEventSource:
    Description: Event source for manual triggers (use in aws events put-events)
    Value: !Sub '${ProjectName}.manual'

  # Tag sync outputs (conditional)
  TagSyncScheduleRuleName:
    Condition: EnableTagSyncCondition
    Description: Name of the tag sync schedule rule
    Value: !Ref TagSyncScheduleRule

  TagSyncScheduleExpression:
    Condition: EnableTagSyncCondition
    Description: Schedule expression for tag sync (hourly)
    Value: 'rate(1 hour)'

  # Staging account sync outputs (conditional)
  StagingAccountSyncScheduleRuleName:
    Condition: EnableStagingAccountSyncCondition
    Description: Name of the staging account sync schedule rule
    Value: !Ref StagingAccountSyncScheduleRule

  StagingAccountSyncScheduleExpression:
    Condition: EnableStagingAccountSyncCondition
    Description: Schedule expression for staging account sync (every 5 minutes)
    Value: 'rate(5 minutes)'

  # Recovery instance sync outputs (conditional)
  RecoveryInstanceSyncScheduleRuleName:
    Condition: EnableRecoveryInstanceSyncCondition
    Description: Name of the recovery instance sync schedule rule
    Value: !Ref RecoveryInstanceSyncScheduleRule

  RecoveryInstanceSyncScheduleExpression:
    Condition: EnableRecoveryInstanceSyncCondition
    Description: Schedule expression for recovery instance sync (every 5 minutes)
    Value: 'rate(5 minutes)'
