AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS DRS Orchestration - Frontend Stack (S3, CloudFront, Custom Resources)'

Parameters:
  ProjectName:
    Type: String
    Description: 'Project name used for resource naming'

  Environment:
    Type: String
    Description: 'Environment name (dev, test, prod)'

  BucketSuffix:
    Type: String
    Description: 'Unique suffix for bucket name (timestamp or random string)'
    Default: 'v1'

  # Cognito IDs from API Stack
  UserPoolId:
    Type: String
    Description: 'Cognito User Pool ID'

  UserPoolClientId:
    Type: String
    Description: 'Cognito User Pool Client ID'

  IdentityPoolId:
    Type: String
    Description: 'Cognito Identity Pool ID'

  # API endpoint from API Stack
  ApiEndpoint:
    Type: String
    Description: 'API Gateway endpoint URL'

  # Lambda ARNs from Lambda Stack
  FrontendDeployerFunctionArn:
    Type: String
    Description: 'Frontend Deployer Lambda Function ARN (Consolidated)'

  # Source bucket for frontend source code
  SourceBucket:
    Type: String
    Description: 'S3 bucket containing frontend source code'

  # Frontend build version for triggering rebuilds
  FrontendBuildVersion:
    Type: String
    Description: 'Frontend build version - auto-generated timestamp to trigger rebuilds'
    Default: 'v1'



Resources:
  # S3 Bucket for Frontend Hosting
  FrontendBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub '${ProjectName}-fe-${AWS::AccountId}-${Environment}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
          - Id: ExpireCurrentVersions
            Status: Enabled
            ExpirationInDays: 90
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # CloudFront Origin Access Control
  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    DeletionPolicy: Delete
    Properties:
      OriginAccessControlConfig:
        Name: !Sub '${ProjectName}-oac-${Environment}'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DeletionPolicy: Delete
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub '${ProjectName} Frontend Distribution'
        DefaultRootObject: index.html
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            OriginAccessControlId: !Ref CloudFrontOAC
            S3OriginConfig:
              OriginAccessIdentity: ''
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          Compress: true
          DefaultTTL: 86400
          MaxTTL: 31536000
          MinTTL: 0
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
        PriceClass: PriceClass_100
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # S3 Bucket Policy for CloudFront
  # DependsOn FrontendDeploymentResource ensures proper resource ordering
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: FrontendDeploymentResource
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub '${FrontendBucket.Arn}/*'
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}'

  # Custom Resource for Frontend Deployment (Consolidated)
  FrontendDeploymentResource:
    Type: Custom::FrontendDeployer
    DependsOn:
      - FrontendBucket
      - CloudFrontDistribution
    Properties:
      ServiceToken: !Ref FrontendDeployerFunctionArn
      BucketName: !Ref FrontendBucket
      DistributionId: !Ref CloudFrontDistribution
      SourceBucket: !Ref SourceBucket
      ApiEndpoint: !Ref ApiEndpoint
      UserPoolId: !Ref UserPoolId
      UserPoolClientId: !Ref UserPoolClientId
      IdentityPoolId: !Ref IdentityPoolId
      Region: !Ref AWS::Region
      FrontendBuildVersion: !Ref FrontendBuildVersion

Outputs:
  FrontendBucketName:
    Description: 'S3 bucket for frontend hosting'
    Value: !Ref FrontendBucket
    Export:
      Name: !Sub '${AWS::StackName}-FrontendBucketName'

  CloudFrontUrl:
    Description: 'CloudFront Distribution URL'
    Value: !Sub 'https://${CloudFrontDistribution.DomainName}'
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontUrl'

  CloudFrontDistributionId:
    Description: 'CloudFront Distribution ID'
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontDistributionId'

  FrontendBuildVersion:
    Description: 'Current frontend build version'
    Value: !Ref FrontendBuildVersion
    Export:
      Name: !Sub '${AWS::StackName}-FrontendBuildVersion'


