AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  AWS DRS Orchestration - Frontend Stack. Deploys React web console with S3 hosting,
  CloudFront CDN, and automated deployment via Custom Resource Lambda. Update
  FrontendBuildVersion parameter to trigger rebuilds.
  
  SAFETY FIRST: Bucket is ONLY emptied during confirmed stack deletion.
  
  When bucket IS emptied (DELETE_IN_PROGRESS or DELETE_FAILED):
  - Stack is actively being deleted
  - All objects, versions, and delete markers are removed
  - Allows CloudFormation to delete the S3 bucket resource
  
  When bucket is NOT emptied (safe defaults):
  - UPDATE_ROLLBACK_IN_PROGRESS: Update failed, rolling back
  - UPDATE_IN_PROGRESS: Stack update in progress
  - Any other status: Not a deletion operation
  - Stack not found: Cannot verify deletion intent
  - Status check failed: Fail safe, skip cleanup
  
  This prevents accidental data loss during UPDATE operations where
  CloudFormation may send DELETE events for resource replacements.

# =============================================================================
# PARAMETERS
# =============================================================================

Parameters:
  ProjectName:
    Type: String
    Description: 'Project name used for resource naming'

  Environment:
    Type: String
    Description: 'Environment name (dev, test, prod)'

  # ---------------------------------------------------------------------------
  # Cognito Configuration (from API Stack)
  # ---------------------------------------------------------------------------
  UserPoolId:
    Type: String
    Description: 'Cognito User Pool ID for authentication'

  UserPoolClientId:
    Type: String
    Description: 'Cognito User Pool Client ID for frontend app'

  IdentityPoolId:
    Type: String
    Description: 'Cognito Identity Pool ID for AWS credentials'

  # ---------------------------------------------------------------------------
  # API Configuration (from API Stack)
  # ---------------------------------------------------------------------------
  ApiEndpoint:
    Type: String
    Description: 'API Gateway endpoint URL for backend calls'

  # ---------------------------------------------------------------------------
  # Lambda Configuration (from Lambda Stack)
  # ---------------------------------------------------------------------------
  FrontendDeployerFunctionArn:
    Type: String
    Description: 'Frontend Deployer Lambda ARN for Custom Resource'

  # ---------------------------------------------------------------------------
  # Source Configuration
  # ---------------------------------------------------------------------------
  SourceBucket:
    Type: String
    Description: 'S3 bucket containing frontend source code (deployment bucket)'

  FrontendBuildVersion:
    Type: String
    Description: 'Frontend build version - auto-generated timestamp to trigger rebuilds'
    Default: 'v1'

  WebACLArn:
    Type: String
    Description: 'WAF Web ACL ARN for CloudFront protection'
    Default: ''

# =============================================================================
# CONDITIONS
# =============================================================================

Conditions:
  HasWebACL: !Not [!Equals [!Ref WebACLArn, '']]

# =============================================================================
# RESOURCES
# =============================================================================

Resources:
  # ===========================================================================
  # S3 BUCKET FOR ACCESS LOGGING
  # ===========================================================================
  # Dedicated bucket for S3 and CloudFront access logs.
  # Required for CKV_AWS_18 (S3 logging) and CKV_AWS_86 (CloudFront logging).
  AccessLogsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub '${ProjectName}-access-logs-${AWS::AccountId}-${Environment}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldLogs
            Status: Enabled
            ExpirationInDays: 90
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: AccessLogs

  # Bucket policy for access logs bucket - allows S3 and CloudFront to write logs
  AccessLogsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DeletionPolicy: Delete
    Properties:
      Bucket: !Ref AccessLogsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # Deny non-HTTPS access
          - Sid: DenyNonHTTPS
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !GetAtt AccessLogsBucket.Arn
              - !Sub '${AccessLogsBucket.Arn}/*'
            Condition:
              Bool:
                'aws:SecureTransport': 'false'
          # Allow S3 to write access logs
          - Sid: S3ServerAccessLogsPolicy
            Effect: Allow
            Principal:
              Service: logging.s3.amazonaws.com
            Action: 's3:PutObject'
            Resource: !Sub '${AccessLogsBucket.Arn}/s3-logs/*'
            Condition:
              ArnLike:
                'aws:SourceArn': !Sub 'arn:${AWS::Partition}:s3:::${ProjectName}-fe-${AWS::AccountId}-${Environment}'
              StringEquals:
                'aws:SourceAccount': !Ref 'AWS::AccountId'
  # ===========================================================================
  # S3 BUCKET FOR FRONTEND HOSTING
  # ===========================================================================
  # Private bucket for React build artifacts. CloudFront serves content via OAC.
  # 
  # Security Configuration:
  # - All public access blocked (PublicAccessBlockConfiguration)
  # - Server-side encryption enabled (AES256)
  # - Versioning enabled for rollback capability
  # 
  # Lifecycle Rules:
  # - Old versions expire after 30 days (cleanup)
  # - Current versions expire after 90 days (forces refresh)
  FrontendBucket:
    Type: AWS::S3::Bucket
    DependsOn: AccessLogsBucketPolicy
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub '${ProjectName}-fe-${AWS::AccountId}-${Environment}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LoggingConfiguration:
        DestinationBucketName: !Ref AccessLogsBucket
        LogFilePrefix: 's3-logs/'
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
          - Id: ExpireCurrentVersions
            Status: Enabled
            ExpirationInDays: 90
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # ===========================================================================
  # CLOUDFRONT ORIGIN ACCESS CONTROL (OAC)
  # ===========================================================================
  # Modern replacement for Origin Access Identity (OAI).
  # Allows CloudFront to access private S3 bucket using SigV4 signing.
  # More secure than OAI: supports SSE-KMS and provides better audit trail.
  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    DeletionPolicy: Delete
    Properties:
      OriginAccessControlConfig:
        Name: !Sub '${ProjectName}-oac-${Environment}'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # ===========================================================================
  # CLOUDFRONT DISTRIBUTION
  # ===========================================================================
  # Global CDN for frontend delivery with edge caching.
  # 
  # Configuration:
  # - HTTPS enforced (redirect HTTP to HTTPS)
  # - Compression enabled for faster delivery
  # - PriceClass_100: North America and Europe edges (cost optimization)
  # 
  # Cache Behavior:
  # - DefaultTTL: 24 hours for static assets
  # - MaxTTL: 1 year for immutable assets (hashed filenames)
  # 
  # SPA Support:
  # - 403/404 errors return index.html with 200 status
  # - Enables client-side routing (React Router)
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DeletionPolicy: Delete
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub '${ProjectName} Frontend Distribution'
        DefaultRootObject: index.html
        WebACLId: !If [HasWebACL, !Ref WebACLArn, !Ref 'AWS::NoValue']
        Logging:
          Bucket: !GetAtt AccessLogsBucket.DomainName
          Prefix: 'cloudfront-logs/'
          IncludeCookies: false
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            OriginAccessControlId: !Ref CloudFrontOAC
            S3OriginConfig:
              OriginAccessIdentity: ''
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          Compress: true
          DefaultTTL: 86400
          MaxTTL: 31536000
          MinTTL: 0
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
        PriceClass: PriceClass_100
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # ===========================================================================
  # S3 BUCKET POLICY
  # ===========================================================================
  # Grants CloudFront distribution read access to bucket objects.
  # Uses AWS:SourceArn condition to restrict access to this specific distribution.
  # DependsOn FrontendDeploymentResource ensures content exists before policy.
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DeletionPolicy: Delete
    DependsOn: FrontendDeploymentResource
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # Deny non-HTTPS access (CKV_AWS_18 requirement)
          - Sid: DenyNonHTTPS
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !GetAtt FrontendBucket.Arn
              - !Sub '${FrontendBucket.Arn}/*'
            Condition:
              Bool:
                'aws:SecureTransport': 'false'
          # Allow CloudFront to read objects
          - Sid: AllowCloudFrontAccess
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: 's3:GetObject'
            Resource: !Sub '${FrontendBucket.Arn}/*'
            Condition:
              StringEquals:
                'AWS:SourceArn': !Sub 'arn:${AWS::Partition}:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}'

  # ===========================================================================
  # CUSTOM RESOURCE: FRONTEND DEPLOYMENT
  # ===========================================================================
  # Triggers Frontend Deployer Lambda during CloudFormation create/update.
  # 
  # Lambda Actions:
  # 1. Downloads frontend source from SourceBucket
  # 2. Generates aws-config.json with Cognito/API settings
  # 3. Builds React application (npm install && npm run build)
  # 4. Uploads dist/ to FrontendBucket
  # 5. Creates CloudFront invalidation for immediate updates
  # 
  # Rebuild Triggers:
  # - FrontendBuildVersion parameter change forces rebuild
  # - Any parameter change (ApiEndpoint, UserPoolId, etc.) triggers update
  FrontendDeploymentResource:
    Type: Custom::FrontendDeployer
    DeletionPolicy: Delete
    DeletionPolicy: Delete
    DependsOn:
      - FrontendBucket
      - CloudFrontDistribution
    Properties:
      ServiceToken: !Ref FrontendDeployerFunctionArn
      BucketName: !Ref FrontendBucket
      DistributionId: !Ref CloudFrontDistribution
      SourceBucket: !Ref SourceBucket
      ApiEndpoint: !Ref ApiEndpoint
      UserPoolId: !Ref UserPoolId
      UserPoolClientId: !Ref UserPoolClientId
      IdentityPoolId: !Ref IdentityPoolId
      Region: !Ref AWS::Region
      FrontendBuildVersion: !Ref FrontendBuildVersion

# =============================================================================
# OUTPUTS
# =============================================================================
# Exported values for cross-stack references and deployment verification.

Outputs:
  # Access logs bucket for S3 and CloudFront logging
  AccessLogsBucketName:
    Description: 'S3 bucket for access logs'
    Value: !Ref AccessLogsBucket
    Export:
      Name: !Sub '${AWS::StackName}-AccessLogsBucketName'

  # S3 bucket name for manual deployments or debugging
  FrontendBucketName:
    Description: 'S3 bucket for frontend hosting'
    Value: !Ref FrontendBucket
    Export:
      Name: !Sub '${AWS::StackName}-FrontendBucketName'

  # Primary access URL for the web console
  CloudFrontUrl:
    Description: 'CloudFront Distribution URL'
    Value: !Sub 'https://${CloudFrontDistribution.DomainName}'
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontUrl'

  # Distribution ID for cache invalidation operations
  CloudFrontDistributionId:
    Description: 'CloudFront Distribution ID'
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontDistributionId'

  # Build version for tracking deployments
  FrontendBuildVersion:
    Description: 'Current frontend build version'
    Value: !Ref FrontendBuildVersion
    Export:
      Name: !Sub '${AWS::StackName}-FrontendBuildVersion'


