AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  AWS DRS Orchestration - GitHub Actions OIDC Integration. Enables passwordless
  authentication for GitHub Actions CI/CD. Deploy once before using workflows.

# =============================================================================
# GITHUB ACTIONS OIDC SETUP GUIDE
# =============================================================================
#
# Authentication Flow:
# 1. GitHub Actions requests OIDC token from GitHub's identity provider
# 2. Workflow assumes IAM role using sts:AssumeRoleWithWebIdentity
# 3. Role trust policy validates GitHub org, repo, and branch/environment
# 4. Temporary credentials granted for deployment operations
#
# Security Model:
# - No long-lived AWS credentials stored in GitHub
# - Role assumption restricted to specific repository and branches
# - Session duration limited to 1 hour
# - Permissions scoped to deployment operations only
#
# Prerequisites:
# - GitHub OIDC provider must exist in AWS account
# - If not present, create via AWS CLI:
#     aws iam create-open-id-connect-provider \
#       --url https://token.actions.githubusercontent.com \
#       --client-id-list sts.amazonaws.com
#
# =============================================================================
# GITHUB REPOSITORY SETUP
# =============================================================================
#
# Step 1: Add Repository Secrets (Settings > Secrets and variables > Actions)
# ---------------------------------------------------------------------------
# Required secrets:
#   AWS_ROLE_ARN        : (from stack output GitHubActionsRoleArn)
#   AWS_REGION          : us-east-2 (or your deployment region)
#   DEPLOYMENT_BUCKET   : hrp-drs-tech-adapter-dev (your S3 bucket)
#   STACK_NAME          : hrp-drs-tech-adapter-dev (your CloudFormation stack)
#
# Optional secrets:
#   ADMIN_EMAIL         : admin@example.com (for SNS notifications)
#
# Step 2: Configure Workflow Permissions
# ---------------------------------------------------------------------------
# Your workflow MUST have id-token write permission for OIDC:
#
#   permissions:
#     id-token: write    # Required for OIDC token generation
#     contents: read     # Required to checkout repository
#
# Step 3: Add AWS Credentials Step to Workflow
# ---------------------------------------------------------------------------
# Use aws-actions/configure-aws-credentials action:
#
#   - name: Configure AWS Credentials
#     uses: aws-actions/configure-aws-credentials@v4
#     with:
#       role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
#       aws-region: ${{ secrets.AWS_REGION }}
#       role-session-name: GitHubActions-${{ github.run_id }}
#
# Step 4: Example Complete Workflow (.github/workflows/deploy.yml)
# ---------------------------------------------------------------------------
#   name: Deploy to AWS
#   on:
#     push:
#       branches: [main]
#     pull_request:
#       branches: [main]
#
#   permissions:
#     id-token: write
#     contents: read
#
#   jobs:
#     deploy:
#       runs-on: ubuntu-latest
#       steps:
#         - name: Checkout
#           uses: actions/checkout@v4
#
#         - name: Configure AWS Credentials
#           uses: aws-actions/configure-aws-credentials@v4
#           with:
#             role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
#             aws-region: ${{ secrets.AWS_REGION }}
#             role-session-name: GitHubActions-${{ github.run_id }}
#
#         - name: Verify AWS Identity
#           run: aws sts get-caller-identity
#
#         - name: Deploy CloudFormation
#           run: |
#             aws cloudformation deploy \
#               --template-file cfn/master-template.yaml \
#               --stack-name ${{ secrets.STACK_NAME }} \
#               --capabilities CAPABILITY_NAMED_IAM \
#               --no-fail-on-empty-changeset
#
# Troubleshooting:
# ---------------------------------------------------------------------------
# - "Not authorized to perform sts:AssumeRoleWithWebIdentity"
#   → Check role trust policy matches your GitHub org/repo/branch
#   → Verify OIDC provider exists in AWS account
#
# - "Credentials could not be loaded"
#   → Ensure workflow has 'id-token: write' permission
#   → Check role ARN is correct in secrets
#
# - "Access Denied" on AWS resources
#   → Verify IAM role has required permissions for the operation
#   → Check resource ARNs in policy match your environment
#
# =============================================================================
# PARAMETERS
# =============================================================================

Parameters:
  ProjectName:
    Type: String
    Description: 'Project name used for resource naming'

  Environment:
    Type: String
    Description: 'Environment name (dev, test, prod)'
    AllowedValues: [dev, test, qa, uat, prod]

  GitHubOrg:
    Type: String
    Description: 'GitHub organization or username'
    Default: 'johnjcousens'

  GitHubRepo:
    Type: String
    Description: 'GitHub repository name'
    Default: 'hrp-drs-tech-adapter'

  DeploymentBucket:
    Type: String
    Description: 'S3 bucket for deployment artifacts'

  ApplicationStackName:
    Type: String
    Description: 'Name of the application stack that GitHub Actions will deploy'

# =============================================================================
# RESOURCES
# =============================================================================

Resources:
  # ===========================================================================
  # GITHUB ACTIONS IAM ROLE
  # ===========================================================================
  # IAM role assumed by GitHub Actions workflows via OIDC federation.
  # Trust policy restricts access to specific GitHub repository and branches.
  # 
  # Allowed principals:
  # - Main branch pushes: repo:org/repo:ref:refs/heads/main
  # - Pull requests: repo:org/repo:pull_request
  # - Environment deployments: repo:org/repo:environment:*
  #
  # Note: Uses existing GitHub OIDC provider in account.
  # If provider doesn't exist, create it first or uncomment GitHubOidcProvider below.
  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-github-actions-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub 'arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com'
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                'token.actions.githubusercontent.com:aud': sts.amazonaws.com
              StringLike:
                'token.actions.githubusercontent.com:sub':
                  - !Sub 'repo:${GitHubOrg}/${GitHubRepo}:ref:refs/heads/main'
                  - !Sub 'repo:${GitHubOrg}/${GitHubRepo}:pull_request'
                  - !Sub 'repo:${GitHubOrg}/${GitHubRepo}:environment:*'
      MaxSessionDuration: 3600
      # =========================================================================
      # DEPLOYMENT PERMISSIONS POLICY
      # =========================================================================
      # Grants permissions required for CloudFormation deployments.
      # Organized by AWS service with comments explaining each permission set.
      Policies:
        - PolicyName: GitHubActionsDeploymentPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # ---------------------------------------------------------------
              # S3: Deployment Bucket Access
              # ---------------------------------------------------------------
              # Read/write access to deployment artifact buckets.
              # Used for: CloudFormation templates, Lambda packages, frontend builds
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                  - s3:GetBucketLocation
                Resource:
                  - !Sub 'arn:aws:s3:::${DeploymentBucket}'
                  - !Sub 'arn:aws:s3:::${DeploymentBucket}/*'
                  # Archive test stack bucket
                  - 'arn:aws:s3:::aws-drs-orchestrator-archive-test-bucket'
                  - 'arn:aws:s3:::aws-drs-orchestrator-archive-test-bucket/*'
              # ---------------------------------------------------------------
              # S3: Frontend Bucket Management
              # ---------------------------------------------------------------
              # Full bucket management for CloudFront-hosted frontend.
              # CloudFormation creates/configures these buckets during deployment.
              - Effect: Allow
                Action:
                  - s3:CreateBucket
                  - s3:DeleteBucket
                  - s3:GetBucketPolicy
                  - s3:PutBucketPolicy
                  - s3:DeleteBucketPolicy
                  - s3:GetBucketAcl
                  - s3:PutBucketAcl
                  - s3:GetBucketCORS
                  - s3:PutBucketCORS
                  - s3:GetBucketWebsite
                  - s3:PutBucketWebsite
                  - s3:DeleteBucketWebsite
                  - s3:GetBucketVersioning
                  - s3:PutBucketVersioning
                  - s3:GetBucketPublicAccessBlock
                  - s3:PutBucketPublicAccessBlock
                  - s3:GetBucketTagging
                  - s3:PutBucketTagging
                  - s3:GetEncryptionConfiguration
                  - s3:PutEncryptionConfiguration
                  - s3:GetLifecycleConfiguration
                  - s3:PutLifecycleConfiguration
                  - s3:GetBucketOwnershipControls
                  - s3:PutBucketOwnershipControls
                  - s3:ListBucket
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:GetObjectVersion
                  - s3:DeleteObjectVersion
                  - s3:ListBucketVersions
                Resource:
                  # Current stack frontend bucket
                  - !Sub 'arn:aws:s3:::${ProjectName}-fe-${AWS::AccountId}-${Environment}'
                  - !Sub 'arn:aws:s3:::${ProjectName}-fe-${AWS::AccountId}-${Environment}/*'
                  # All DRS orchestrator frontend buckets (wildcard pattern)
                  - !Sub 'arn:aws:s3:::aws-*drs-orchestrator*-fe-${AWS::AccountId}-*'
                  - !Sub 'arn:aws:s3:::aws-*drs-orchestrator*-fe-${AWS::AccountId}-*/*'
              # ---------------------------------------------------------------
              # CloudFormation: Stack Management
              # ---------------------------------------------------------------
              # Full stack lifecycle management for DRS orchestration stacks.
              # Includes create, update, delete, and change set operations.
              - Effect: Allow
                Action:
                  - cloudformation:CreateStack
                  - cloudformation:UpdateStack
                  - cloudformation:DeleteStack
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeStackEvents
                  - cloudformation:DescribeStackResources
                  - cloudformation:GetTemplate
                  - cloudformation:GetTemplateSummary
                  - cloudformation:ValidateTemplate
                  - cloudformation:CreateChangeSet
                  - cloudformation:DescribeChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:ListStacks
                  - cloudformation:ListStackResources
                  - cloudformation:ContinueUpdateRollback
                Resource:
                  # Allow access to all DRS orchestration stacks (current and archive test)
                  - !Sub 'arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/aws-*drs-orchestrat*/*'
                  - !Sub 'arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/aws-*elasticdrs-orchestrat*/*'
              # CloudFormation: Global operations (no resource restriction)
              - Effect: Allow
                Action:
                  - cloudformation:ValidateTemplate
                  - cloudformation:ListStacks
                Resource: '*'
              # ---------------------------------------------------------------
              # IAM: Role Management for CloudFormation
              # ---------------------------------------------------------------
              # Required for CloudFormation to create/manage Lambda execution roles,
              # Step Functions roles, and other service roles defined in templates.
              - Effect: Allow
                Action:
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:GetRole
                  - iam:PassRole
                  - iam:AttachRolePolicy
                  - iam:DetachRolePolicy
                  - iam:PutRolePolicy
                  - iam:DeleteRolePolicy
                  - iam:GetRolePolicy
                  - iam:ListRolePolicies
                  - iam:ListAttachedRolePolicies
                  - iam:TagRole
                  - iam:UntagRole
                  - iam:UpdateRole
                  - iam:UpdateAssumeRolePolicy
                  - iam:CreateServiceLinkedRole
                Resource: '*'
              # ---------------------------------------------------------------
              # COMPUTE & ORCHESTRATION SERVICES
              # ---------------------------------------------------------------
              # Lambda: Function deployment and configuration
              - Effect: Allow
                Action:
                  - lambda:*
                Resource: '*'
              # Step Functions: State machine deployment
              - Effect: Allow
                Action:
                  - states:*
                Resource: '*'
              # EventBridge: Scheduled rules and event routing
              - Effect: Allow
                Action:
                  - events:*
                Resource: '*'
              # ---------------------------------------------------------------
              # API & FRONTEND SERVICES
              # ---------------------------------------------------------------
              # API Gateway: REST API deployment
              - Effect: Allow
                Action:
                  - apigateway:*
                Resource: '*'
              # CloudFront: CDN distribution management
              - Effect: Allow
                Action:
                  - cloudfront:*
                Resource: '*'
              # Cognito: User authentication infrastructure
              - Effect: Allow
                Action:
                  - cognito-idp:*
                  - cognito-identity:*
                Resource: '*'
              # ---------------------------------------------------------------
              # DATA & STORAGE SERVICES
              # ---------------------------------------------------------------
              # DynamoDB: Table deployment and configuration
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource: '*'
              # ---------------------------------------------------------------
              # NOTIFICATION & LOGGING SERVICES
              # ---------------------------------------------------------------
              # SNS: Notification topic deployment
              - Effect: Allow
                Action:
                  - sns:*
                Resource: '*'
              # CloudWatch Logs: Log group management
              - Effect: Allow
                Action:
                  - logs:*
                Resource: '*'
              # ---------------------------------------------------------------
              # SECURITY SERVICES
              # ---------------------------------------------------------------
              # WAF: Web application firewall rules
              - Effect: Allow
                Action:
                  - wafv2:*
                Resource: '*'
              # Secrets Manager: Secret storage for API keys
              - Effect: Allow
                Action:
                  - secretsmanager:*
                Resource: '*'
              # KMS: Encryption key management
              - Effect: Allow
                Action:
                  - kms:*
                Resource: '*'
              # ---------------------------------------------------------------
              # UTILITY PERMISSIONS
              # ---------------------------------------------------------------
              # STS: Identity verification for deployment scripts
              - Effect: Allow
                Action:
                  - sts:GetCallerIdentity
                Resource: '*'
              # Resource tagging: Tag management across services
              - Effect: Allow
                Action:
                  - tag:*
                Resource: '*'
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

# =============================================================================
# OUTPUTS
# =============================================================================
# Values required for GitHub Actions workflow configuration.
# Add these to GitHub repository secrets for CI/CD integration.

Outputs:
  # Primary output: Role ARN for GitHub Actions to assume
  GitHubActionsRoleArn:
    Description: 'IAM Role ARN for GitHub Actions (use in GitHub secrets as AWS_ROLE_ARN)'
    Value: !GetAtt GitHubActionsRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-GitHubActionsRoleArn'

  # Reference to existing OIDC provider
  OidcProviderArn:
    Description: 'GitHub OIDC Provider ARN (existing provider in account)'
    Value: !Sub 'arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com'
    Export:
      Name: !Sub '${AWS::StackName}-OidcProviderArn'

  # Deployment configuration outputs
  DeploymentBucketName:
    Description: 'S3 bucket for deployment artifacts'
    Value: !Ref DeploymentBucket
    Export:
      Name: !Sub '${AWS::StackName}-DeploymentBucket'

  ApplicationStackName:
    Description: 'Application stack name for deployments'
    Value: !Ref ApplicationStackName
    Export:
      Name: !Sub '${AWS::StackName}-ApplicationStackName'

  # Setup instructions for GitHub repository configuration
  GitHubSecretsInstructions:
    Description: 'Instructions for GitHub repository secrets'
    Value: !Sub |
      Add these secrets to your GitHub repository:
      - AWS_ROLE_ARN: ${GitHubActionsRole.Arn}
      - AWS_REGION: ${AWS::Region}
      - DEPLOYMENT_BUCKET: ${DeploymentBucket}
      - STACK_NAME: ${ApplicationStackName}
