AWSTemplateFormatVersion: "2010-09-09"
Description: |
  DR Orchestration Lambda Functions
  
  Deploys Lambda functions for wave-based disaster recovery orchestration:
  - Data Management Handler: CRUD for Protection Groups, Recovery Plans, Target Accounts, Tag Sync
  - Execution Handler: Recovery execution, pause/resume, termination, DRS operations
  - Query Handler: Source servers, quotas, capacity, EC2 resources, configuration export
  - DR Orchestration Step Function: Wave execution logic invoked by Step Functions
  - Frontend Deployer: Builds and deploys React frontend to S3/CloudFront
  
  All functions share unified OrchestrationRoleArn for DRS, DynamoDB, SNS, Step Functions access.
  Supports cross-account DRS operations via IAM role assumption.
  
  Note: DRS Agent Deployer is commented out (not yet implemented).

Parameters:
  ProjectName:
    Type: String
    Description: "Project name for resource naming"

  Environment:
    Type: String
    Description: "Environment name"

  SourceBucket:
    Type: String
    Description: "S3 bucket containing Lambda deployment packages"

  OrchestrationRoleArn:
    Type: String
    Description: "ARN of the orchestration role for all Lambda functions (passed from master stack)"

  ProtectionGroupsTableName:
    Type: String
    Description: "DynamoDB table name for Protection Groups"

  RecoveryPlansTableName:
    Type: String
    Description: "DynamoDB table name for Recovery Plans"

  ExecutionHistoryTableName:
    Type: String
    Description: "DynamoDB table name for Execution History"

  TargetAccountsTableName:
    Type: String
    Description: "DynamoDB table name for Target Accounts"

  SourceServerInventoryTableName:
    Type: String
    Description: "DynamoDB table name for Source Server Inventory"

  DRSRegionStatusTableName:
    Type: String
    Description: "DynamoDB table name for DRS Region Status"

  LambdaCodeVersion:
    Type: String
    Description: "Version identifier to force Lambda code updates (timestamp)"
    Default: "initial"

  ExecutionNotificationsTopicArn:
    Type: String
    Default: ""
    Description: "SNS topic ARN for execution notifications"

  DRSAlertsTopicArn:
    Type: String
    Default: ""
    Description: "SNS topic ARN for DRS operational alerts"

  ExecutionPauseTopicArn:
    Type: String
    Default: ""
    Description: "SNS topic ARN for execution pause notifications"

  ApiGatewayUrl:
    Type: String
    Default: ""
    Description: "API Gateway base URL for callback URL construction (empty if API Gateway not deployed)"

Resources:
  # ===========================================================================
  # DEAD LETTER QUEUE FOR LAMBDA FUNCTIONS
  # ===========================================================================
  # SQS queue to capture failed Lambda invocations for debugging
  # Required for CKV_AWS_116 (Lambda DLQ configuration)
  # All Lambda functions in this stack share this DLQ
  
  LambdaDeadLetterQueue:
    Type: AWS::SQS::Queue
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      QueueName: !Sub "${ProjectName}-lambda-dlq-${Environment}"
      MessageRetentionPeriod: 1209600  # 14 days
      KmsMasterKeyId: alias/aws/sqs
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # ===========================================================================
  # LAMBDA FUNCTIONS
  # ===========================================================================
  # All functions share unified OrchestrationRoleArn for DRS, DynamoDB, SNS, Step Functions access
  # Supports cross-account DRS operations via IAM role assumption
  # 
  # NOTE: CloudWatch Log Groups are NOT explicitly created here.
  # Lambda automatically creates log groups on first invocation.
  # This avoids "already exists" errors during CloudFormation updates.

  # Data Management Handler for Protection Groups and Recovery Plans CRUD operations
  # Handles tag resolution, launch configuration, and conflict detection
  DataManagementHandlerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-data-management-handler-${Environment}"
      Description: !Sub "Data Management handler for Protection Groups and Recovery Plans (v${LambdaCodeVersion})"
      Runtime: python3.12
      Handler: index.lambda_handler
      Role: !Ref OrchestrationRoleArn
      Code:
        S3Bucket: !Ref SourceBucket
        S3Key: "lambda/data-management-handler.zip"
      Timeout: 900  # 15 minutes - needed for tag sync across many accounts/regions
      MemorySize: 512
      ReservedConcurrentExecutions: 50
      DeadLetterConfig:
        TargetArn: !GetAtt LambdaDeadLetterQueue.Arn
      Environment:
        Variables:
          PROTECTION_GROUPS_TABLE: !Ref ProtectionGroupsTableName
          RECOVERY_PLANS_TABLE: !Ref RecoveryPlansTableName
          EXECUTION_HISTORY_TABLE: !Ref ExecutionHistoryTableName
          TARGET_ACCOUNTS_TABLE: !Ref TargetAccountsTableName
          SOURCE_SERVER_INVENTORY_TABLE: !Ref SourceServerInventoryTableName
          DRS_REGION_STATUS_TABLE: !Ref DRSRegionStatusTableName
          PROJECT_NAME: !Ref ProjectName
          ENVIRONMENT: !Ref Environment
          STATE_MACHINE_ARN: !Sub "arn:${AWS::Partition}:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${ProjectName}-orchestration-${Environment}"
          EXECUTION_NOTIFICATIONS_TOPIC_ARN: !Ref ExecutionNotificationsTopicArn
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # Execution Handler for DR operations and lifecycle management
  # Handles recovery plan execution, pause/resume, termination, and DRS operations
  ExecutionHandlerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-execution-handler-${Environment}"
      Description: !Sub "Execution handler for DR operations and lifecycle management (v${LambdaCodeVersion})"
      Runtime: python3.12
      Handler: index.lambda_handler
      Role: !Ref OrchestrationRoleArn
      Code:
        S3Bucket: !Ref SourceBucket
        S3Key: "lambda/execution-handler.zip"
      Timeout: 300
      MemorySize: 512
      ReservedConcurrentExecutions: 50
      DeadLetterConfig:
        TargetArn: !GetAtt LambdaDeadLetterQueue.Arn
      Environment:
        Variables:
          PROTECTION_GROUPS_TABLE: !Ref ProtectionGroupsTableName
          RECOVERY_PLANS_TABLE: !Ref RecoveryPlansTableName
          EXECUTION_HISTORY_TABLE: !Ref ExecutionHistoryTableName
          TARGET_ACCOUNTS_TABLE: !Ref TargetAccountsTableName
          SOURCE_SERVER_INVENTORY_TABLE: !Ref SourceServerInventoryTableName
          DRS_REGION_STATUS_TABLE: !Ref DRSRegionStatusTableName
          PROJECT_NAME: !Ref ProjectName
          ENVIRONMENT: !Ref Environment
          STATE_MACHINE_ARN: !Sub "arn:${AWS::Partition}:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${ProjectName}-orchestration-${Environment}"
          EXECUTION_NOTIFICATIONS_TOPIC_ARN: !Ref ExecutionNotificationsTopicArn
          EXECUTION_PAUSE_TOPIC_ARN: !Ref ExecutionPauseTopicArn
          API_GATEWAY_URL: !Ref ApiGatewayUrl
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # Query Handler for read-only DRS and EC2 infrastructure queries
  # Handles source servers, quotas, capacity, EC2 resources, and configuration export
  QueryHandlerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-query-handler-${Environment}"
      Description: !Sub "Query handler for read-only DRS and EC2 infrastructure queries (v${LambdaCodeVersion})"
      Runtime: python3.12
      Handler: index.lambda_handler
      Role: !Ref OrchestrationRoleArn
      Code:
        S3Bucket: !Ref SourceBucket
        S3Key: "lambda/query-handler.zip"
      Timeout: 60
      MemorySize: 256
      ReservedConcurrentExecutions: 50
      DeadLetterConfig:
        TargetArn: !GetAtt LambdaDeadLetterQueue.Arn
      Environment:
        Variables:
          PROTECTION_GROUPS_TABLE: !Ref ProtectionGroupsTableName
          RECOVERY_PLANS_TABLE: !Ref RecoveryPlansTableName
          EXECUTION_HISTORY_TABLE: !Ref ExecutionHistoryTableName
          TARGET_ACCOUNTS_TABLE: !Ref TargetAccountsTableName
          SOURCE_SERVER_INVENTORY_TABLE: !Ref SourceServerInventoryTableName
          DRS_REGION_STATUS_TABLE: !Ref DRSRegionStatusTableName
          PROJECT_NAME: !Ref ProjectName
          ENVIRONMENT: !Ref Environment
          EXECUTION_HANDLER_ARN: !GetAtt ExecutionHandlerFunction.Arn
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # DR Orchestration Step Function Handler (Refactored)
  # Generic wave-based orchestration with no DRS code
  # Invokes execution-handler and query-handler for DRS operations
  DrOrchestrationStepFunctionFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-dr-orch-sf-${Environment}"
      Description: !Sub "Generic wave-based orchestration (v${LambdaCodeVersion})"
      Runtime: python3.12
      Handler: index.lambda_handler
      Role: !Ref OrchestrationRoleArn
      Code:
        S3Bucket: !Ref SourceBucket
        S3Key: "lambda/dr-orchestration-stepfunction.zip"
      Timeout: 300
      MemorySize: 512
      ReservedConcurrentExecutions: 50
      DeadLetterConfig:
        TargetArn: !GetAtt LambdaDeadLetterQueue.Arn
      Environment:
        Variables:
          PROTECTION_GROUPS_TABLE: !Ref ProtectionGroupsTableName
          RECOVERY_PLANS_TABLE: !Ref RecoveryPlansTableName
          EXECUTION_HISTORY_TABLE: !Ref ExecutionHistoryTableName
          EXECUTION_NOTIFICATIONS_TOPIC_ARN: !Ref ExecutionNotificationsTopicArn
          DRS_ALERTS_TOPIC_ARN: !Ref DRSAlertsTopicArn
          EXECUTION_HANDLER_ARN: !GetAtt ExecutionHandlerFunction.Arn
          QUERY_HANDLER_ARN: !GetAtt QueryHandlerFunction.Arn
          API_GATEWAY_URL: !Ref ApiGatewayUrl
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # Builds and deploys React frontend to S3/CloudFront
  # Consolidates frontend build and bucket cleanup operations
  FrontendDeployerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-frontend-deployer-${Environment}"
      Description: !Sub "Builds and deploys React frontend to S3/CloudFront (v${LambdaCodeVersion})"
      Runtime: python3.12
      Handler: index.lambda_handler
      Role: !Ref OrchestrationRoleArn
      Code:
        S3Bucket: !Ref SourceBucket
        S3Key: "lambda/frontend-deployer.zip"
      Timeout: 900
      MemorySize: 2048
      ReservedConcurrentExecutions: 10
      DeadLetterConfig:
        TargetArn: !GetAtt LambdaDeadLetterQueue.Arn
      Environment:
        Variables:
          PROTECTION_GROUPS_TABLE: !Ref ProtectionGroupsTableName
          RECOVERY_PLANS_TABLE: !Ref RecoveryPlansTableName
          EXECUTION_HISTORY_TABLE: !Ref ExecutionHistoryTableName
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # ===========================================================================
  # LAMBDA RESOURCE-BASED POLICIES FOR DIRECT INVOCATION
  # ===========================================================================
  # Grant OrchestrationRole permission to invoke Lambda functions directly
  # Enables direct invocation mode without API Gateway
  # Required for: Requirements 7.6, 11.1, 11.2, 11.3
  
  # Permission for OrchestrationRole to invoke Query Handler
  QueryHandlerDirectInvocationPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref QueryHandlerFunction
      Action: lambda:InvokeFunction
      Principal: !Ref AWS::AccountId
      SourceArn: !Ref OrchestrationRoleArn

  # Permission for OrchestrationRole to invoke Execution Handler
  ExecutionHandlerDirectInvocationPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ExecutionHandlerFunction
      Action: lambda:InvokeFunction
      Principal: !Ref AWS::AccountId
      SourceArn: !Ref OrchestrationRoleArn

  # Permission for OrchestrationRole to invoke Data Management Handler
  DataManagementHandlerDirectInvocationPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DataManagementHandlerFunction
      Action: lambda:InvokeFunction
      Principal: !Ref AWS::AccountId
      SourceArn: !Ref OrchestrationRoleArn

  # ===========================================================================
  # EVENTBRIDGE SCHEDULED INVOCATIONS
  # ===========================================================================
  
  # EventBridge schedule for execution polling
  # Triggers execution-handler to find and poll active executions every 1 minute
  ExecutionFinderScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "${ProjectName}-execution-polling-schedule-${Environment}"
      Description: "Triggers Execution Handler to find and poll active executions every 1 minute"
      ScheduleExpression: "rate(1 minute)"
      State: ENABLED
      Targets:
        - Arn: !GetAtt ExecutionHandlerFunction.Arn
          Id: ExecutionHandlerTarget
          Input: '{"operation": "find"}'

  # Permission for EventBridge to invoke Execution Handler
  ExecutionFinderSchedulePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ExecutionHandlerFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ExecutionFinderScheduleRule.Arn

  # ============================================================================
  # DRS Agent Deployer - COMMENTED OUT (Not Yet Implemented)
  # ============================================================================
  # Automated DRS agent deployment across AWS accounts
  # Discovers instances with DR tags and deploys DRS agents via SSM
  # Supports cross-account role assumption for multi-account orchestration
  #
  # Implementation requirements before enabling:
  # - Finalize SSM command execution logic
  # - Add comprehensive error handling
  # - Implement retry mechanisms
  # - Add integration tests
  #
  # DRSAgentDeployerFunction:
  #   Type: AWS::Lambda::Function
  #   Properties:
  #     FunctionName: !Sub "${ProjectName}-drs-agent-deployer-${Environment}"
  #     Description: "Automated DRS agent deployment across AWS accounts"
  #     Runtime: python3.11
  #     Handler: index.lambda_handler
  #     Role: !Ref OrchestrationRoleArn
  #     Code:
  #       S3Bucket: !Ref SourceBucket
  #       S3Key: "lambda/drs-agent-deployer.zip"
  #     Timeout: 900  # 15 minutes
  #     MemorySize: 512
  #     Environment:
  #       Variables:
  #         TARGET_REGION: us-west-2
  #         SNS_TOPIC_ARN: !Ref ExecutionNotificationsTopicArn
  #         PROJECT_NAME: !Ref ProjectName
  #         ENVIRONMENT: !Ref Environment
  #     Tags:
  #       - Key: Project
  #         Value: !Ref ProjectName
  #       - Key: Environment
  #         Value: !Ref Environment
  #
  # # CloudWatch Log Group for DRS Agent Deployer
  # DRSAgentDeployerLogGroup:
  #   Type: AWS::Logs::LogGroup
  #   Properties:
  #     LogGroupName: !Sub "/aws/lambda/${ProjectName}-drs-agent-deployer-${Environment}"
  #     RetentionInDays: 30

Outputs:
  DataManagementHandlerFunctionArn:
    Description: "Data Management Handler Lambda Function ARN"
    Value: !GetAtt DataManagementHandlerFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-DataManagementHandlerArn"

  DataManagementHandlerFunctionName:
    Description: "Data Management Handler Lambda Function Name"
    Value: !Ref DataManagementHandlerFunction
    Export:
      Name: !Sub "${AWS::StackName}-DataManagementHandlerName"

  ExecutionHandlerFunctionArn:
    Description: "Execution Handler Lambda Function ARN"
    Value: !GetAtt ExecutionHandlerFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ExecutionHandlerArn"

  ExecutionHandlerFunctionName:
    Description: "Execution Handler Lambda Function Name"
    Value: !Ref ExecutionHandlerFunction
    Export:
      Name: !Sub "${AWS::StackName}-ExecutionHandlerName"

  QueryHandlerFunctionArn:
    Description: "Query Handler Lambda Function ARN"
    Value: !GetAtt QueryHandlerFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-QueryHandlerArn"

  QueryHandlerFunctionName:
    Description: "Query Handler Lambda Function Name"
    Value: !Ref QueryHandlerFunction
    Export:
      Name: !Sub "${AWS::StackName}-QueryHandlerName"

  DrOrchestrationStepFunctionArn:
    Description: "DR Orchestration Step Function Lambda ARN (Refactored)"
    Value: !GetAtt DrOrchestrationStepFunctionFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-DrOrchestrationStepFunctionArn"

  DrOrchestrationStepFunctionName:
    Description: "DR Orchestration Step Function Lambda Name (Refactored)"
    Value: !Ref DrOrchestrationStepFunctionFunction
    Export:
      Name: !Sub "${AWS::StackName}-DrOrchestrationStepFunctionName"

  ExecutionFinderScheduleRuleArn:
    Description: "EventBridge Schedule Rule ARN for execution polling"
    Value: !GetAtt ExecutionFinderScheduleRule.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ScheduleRuleArn"

  FrontendDeployerFunctionArn:
    Description: "Frontend Deployer Lambda Function ARN (Consolidated)"
    Value: !GetAtt FrontendDeployerFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-FrontendDeployerArn"

  # DRS Agent Deployer outputs - COMMENTED OUT (Under Development)
  # DRSAgentDeployerFunctionArn:
  #   Description: "DRS Agent Deployer Lambda Function ARN"
  #   Value: !GetAtt DRSAgentDeployerFunction.Arn
  #   Export:
  #     Name: !Sub "${AWS::StackName}-DRSAgentDeployerArn"
  #
  # DRSAgentDeployerFunctionName:
  #   Description: "DRS Agent Deployer Lambda Function Name"
  #   Value: !Ref DRSAgentDeployerFunction
  #   Export:
  #     Name: !Sub "${AWS::StackName}-DRSAgentDeployerName"

  # Legacy output for backward compatibility with existing CloudFormation references
  # Points to DataManagementHandler since it handles most API endpoints
  ApiHandlerFunctionArn:
    Description: "Legacy API Handler ARN (backward compatibility - points to Data Management Handler)"
    Value: !GetAtt DataManagementHandlerFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ApiHandlerArn"

  # Dead Letter Queue outputs
  LambdaDeadLetterQueueArn:
    Description: "Lambda Dead Letter Queue ARN"
    Value: !GetAtt LambdaDeadLetterQueue.Arn
    Export:
      Name: !Sub "${AWS::StackName}-LambdaDLQArn"

  LambdaDeadLetterQueueUrl:
    Description: "Lambda Dead Letter Queue URL"
    Value: !Ref LambdaDeadLetterQueue
    Export:
      Name: !Sub "${AWS::StackName}-LambdaDLQUrl"
