AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS DRS Orchestration Solution - Master Template (Nested Stack Architecture)'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'General Configuration'
        Parameters:
          - ProjectName
          - Environment
          - SourceBucket
      - Label:
          default: 'Authentication Configuration'
        Parameters:
          - AdminEmail
          - CognitoDomainPrefix
      - Label:
          default: 'Notification Configuration'
        Parameters:
          - NotificationEmail
      - Label:
          default: 'Security Configuration (Optional)'
        Parameters:
          - EnableWAF
          - EnableCloudTrail
          - EnableSecretsManager

Parameters:
  ProjectName:
    Type: String
    Default: 'aws-elasticdrs-orchestrator'
    Description: 'Project name used for resource naming'
    AllowedPattern: '^[a-z0-9-]+$'
    ConstraintDescription: 'Must contain only lowercase letters, numbers, and hyphens'

  Environment:
    Type: String
    Default: 'dev'
    Description: 'Environment name (dev, test, prod)'
    AllowedValues:
      - dev
      - test
      - qa
      - uat
      - prod

  SourceBucket:
    Type: String
    Default: 'aws-elasticdrs-orchestrator'
    Description: 'S3 bucket containing nested CloudFormation templates and Lambda code at root level'

  AdminEmail:
    Type: String
    Description: 'Email address for initial Cognito admin user'
    AllowedPattern: '^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
    ConstraintDescription: 'Must be a valid email address'

  CognitoDomainPrefix:
    Type: String
    Default: ''
    Description: 'Optional: Custom domain prefix for Cognito (leave empty for auto-generated)'

  NotificationEmail:
    Type: String
    Default: ''
    Description: 'Optional: Email address for execution notifications (leave empty to skip)'

  EnablePipelineNotifications:
    Type: String
    Default: 'true'
    Description: 'Enable SNS email notifications for pipeline and security scan failures'
    AllowedValues:
      - 'true'
      - 'false'

  EnableWAF:
    Type: String
    Default: 'true'
    Description: 'Enable AWS WAF for API Gateway protection'
    AllowedValues:
      - 'true'
      - 'false'

  EnableCloudTrail:
    Type: String
    Default: 'true'
    Description: 'Enable CloudTrail for audit logging'
    AllowedValues:
      - 'true'
      - 'false'

  EnableSecurityStack:
    Type: String
    Default: 'false'
    Description: 'Enable Security Stack (WAF, CloudTrail, Secrets Manager)'
    AllowedValues:
      - 'true'
      - 'false'

  EnableSecretsManager:
    Type: String
    Default: 'true'
    Description: 'Enable Secrets Manager for secure credential storage'
    AllowedValues:
      - 'true'
      - 'false'

  EnableTerminationProtection:
    Type: String
    Default: 'true'
    Description: 'Enable CloudFormation stack termination protection (CRITICAL for production)'
    AllowedValues:
      - 'true'
      - 'false'

  # Tag Sync Configuration
  EnableTagSync:
    Type: String
    Default: 'true'
    Description: 'Enable scheduled DRS tag synchronization'
    AllowedValues:
      - 'true'
      - 'false'

  # Cross-Account Configuration
  CrossAccountRoleName:
    Type: String
    Default: 'aws-elasticdrs-orchestrator-cross-account-role'
    Description: 'Name of the cross-account IAM role for DRS operations in target accounts'
    AllowedPattern: '^[a-zA-Z0-9+=,.@_-]+$'
    ConstraintDescription: 'Must be a valid IAM role name'

  TagSyncIntervalHours:
    Type: Number
    Default: 4
    MinValue: 1
    MaxValue: 24
    Description: 'Tag sync interval in hours (1-24)'

  # API Gateway Deployment
  ApiDeploymentTimestamp:
    Type: String
    Default: 'initial'
    Description: 'Timestamp to force API Gateway redeployment (pass unique value on each deploy)'

Conditions:
  HasNotificationEmail: !Not [!Equals [!Ref NotificationEmail, '']]
  EnableTagSyncCondition: !Equals [!Ref EnableTagSync, 'true']
  EnableSecurityStackCondition: !Equals [!Ref EnableSecurityStack, 'true']

Resources:
  # Database Stack - DynamoDB Tables
  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${SourceBucket}/cfn/database-stack.yaml'
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
      TimeoutInMinutes: 15

  # Lambda Stack - Lambda Functions and IAM Roles
  LambdaStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    DependsOn: DatabaseStack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${SourceBucket}/cfn/lambda-stack.yaml'
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        SourceBucket: !Ref SourceBucket
        ProtectionGroupsTableName: !GetAtt DatabaseStack.Outputs.ProtectionGroupsTableName
        RecoveryPlansTableName: !GetAtt DatabaseStack.Outputs.RecoveryPlansTableName
        ExecutionHistoryTableName: !GetAtt DatabaseStack.Outputs.ExecutionHistoryTableName
        TargetAccountsTableName: !GetAtt DatabaseStack.Outputs.TargetAccountsTableName
        NotificationTopicArn: ""
        CrossAccountRoleName: !Ref CrossAccountRoleName
        AdminEmail: !Ref AdminEmail
        EnablePipelineNotifications: !Ref EnablePipelineNotifications
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
      TimeoutInMinutes: 30

  # Step Functions Stack - State Machine for DRS Orchestration
  StepFunctionsStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    DependsOn:
      - DatabaseStack
      - LambdaStack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${SourceBucket}/cfn/step-functions-stack.yaml'
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        OrchestrationLambdaArn: !GetAtt LambdaStack.Outputs.OrchestrationStepFunctionsFunctionArn
        ApiHandlerFunctionName: !GetAtt LambdaStack.Outputs.ApiHandlerFunctionName
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
      TimeoutInMinutes: 10

  # API Authentication Stack - Cognito, IAM, SNS
  ApiAuthStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    DependsOn:
      - DatabaseStack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${SourceBucket}/cfn/api-auth-stack.yaml'
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        AdminEmail: !Ref AdminEmail
        CognitoDomainPrefix: !Ref CognitoDomainPrefix
        NotificationEmail: !If [HasNotificationEmail, !Ref NotificationEmail, !Ref AdminEmail]
        ExecutionHistoryTableArn: !GetAtt DatabaseStack.Outputs.ExecutionHistoryTableArn
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
      TimeoutInMinutes: 15

  # API Gateway Stack - API Gateway, Resources, Methods
  ApiGatewayStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    DependsOn:
      - DatabaseStack
      - LambdaStack
      - ApiAuthStack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${SourceBucket}/cfn/api-gateway-stack.yaml'
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        DeploymentTimestamp: !Ref ApiDeploymentTimestamp
        UserPoolId: !GetAtt ApiAuthStack.Outputs.UserPoolId
        ProtectionGroupsTableName: !GetAtt DatabaseStack.Outputs.ProtectionGroupsTableName
        RecoveryPlansTableName: !GetAtt DatabaseStack.Outputs.RecoveryPlansTableName
        ExecutionHistoryTableName: !GetAtt DatabaseStack.Outputs.ExecutionHistoryTableName
        ExecutionHistoryTableArn: !GetAtt DatabaseStack.Outputs.ExecutionHistoryTableArn
        TargetAccountsTableName: !GetAtt DatabaseStack.Outputs.TargetAccountsTableName
        ApiHandlerFunctionArn: !GetAtt LambdaStack.Outputs.ApiHandlerFunctionArn
        OrchestrationFunctionArn: !GetAtt LambdaStack.Outputs.OrchestrationStepFunctionsFunctionArn
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
      TimeoutInMinutes: 20

  # EventBridge Stack - Scheduled Drills and Tag Sync
  EventBridgeStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    DependsOn:
      - LambdaStack
      - StepFunctionsStack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${SourceBucket}/cfn/eventbridge-stack.yaml'
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        ModularOrchestratorArn: !GetAtt StepFunctionsStack.Outputs.StateMachineArn
        EnableWeeklyDrill: 'false'  # Disabled by default
        EnableTagSync: !Ref EnableTagSync
        TagSyncIntervalHours: !Ref TagSyncIntervalHours
        ApiHandlerFunctionArn: !GetAtt LambdaStack.Outputs.ApiHandlerFunctionArn
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
      TimeoutInMinutes: 10

  # Frontend Stack - S3, CloudFront, Custom Resources
  FrontendStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    DependsOn:
      - LambdaStack
      - ApiGatewayStack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${SourceBucket}/cfn/frontend-stack.yaml'
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        UserPoolId: !GetAtt ApiAuthStack.Outputs.UserPoolId
        UserPoolClientId: !GetAtt ApiAuthStack.Outputs.UserPoolClientId
        IdentityPoolId: !GetAtt ApiAuthStack.Outputs.IdentityPoolId
        ApiEndpoint: !GetAtt ApiGatewayStack.Outputs.ApiEndpoint
        BucketCleanerFunctionArn: !GetAtt LambdaStack.Outputs.BucketCleanerFunctionArn
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
      TimeoutInMinutes: 60

  # Security Stack - WAF, CloudTrail, Secrets Manager (Optional)
  SecurityStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Condition: EnableSecurityStackCondition
    DependsOn:
      - ApiGatewayStack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${SourceBucket}/cfn/security-stack.yaml'
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        RestApiId: !GetAtt ApiGatewayStack.Outputs.ApiId
        EnableWAF: !Ref EnableWAF
        EnableCloudTrail: !Ref EnableCloudTrail
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
      TimeoutInMinutes: 15

Outputs:
  # Database Stack Outputs
  ProtectionGroupsTableName:
    Description: 'DynamoDB table for Protection Groups'
    Value: !GetAtt DatabaseStack.Outputs.ProtectionGroupsTableName
    Export:
      Name: !Sub '${AWS::StackName}-ProtectionGroupsTable'

  RecoveryPlansTableName:
    Description: 'DynamoDB table for Recovery Plans'
    Value: !GetAtt DatabaseStack.Outputs.RecoveryPlansTableName
    Export:
      Name: !Sub '${AWS::StackName}-RecoveryPlansTable'

  ExecutionHistoryTableName:
    Description: 'DynamoDB table for Execution History'
    Value: !GetAtt DatabaseStack.Outputs.ExecutionHistoryTableName
    Export:
      Name: !Sub '${AWS::StackName}-ExecutionHistoryTable'

  ProtectionGroupsTableArn:
    Description: 'DynamoDB table ARN for Protection Groups'
    Value: !GetAtt DatabaseStack.Outputs.ProtectionGroupsTableArn
    Export:
      Name: !Sub '${AWS::StackName}-ProtectionGroupsTableArn'

  RecoveryPlansTableArn:
    Description: 'DynamoDB table ARN for Recovery Plans'
    Value: !GetAtt DatabaseStack.Outputs.RecoveryPlansTableArn
    Export:
      Name: !Sub '${AWS::StackName}-RecoveryPlansTableArn'

  ExecutionHistoryTableArn:
    Description: 'DynamoDB table ARN for Execution History'
    Value: !GetAtt DatabaseStack.Outputs.ExecutionHistoryTableArn
    Export:
      Name: !Sub '${AWS::StackName}-ExecutionHistoryTableArn'

  TargetAccountsTableName:
    Description: 'DynamoDB table for Target Accounts'
    Value: !GetAtt DatabaseStack.Outputs.TargetAccountsTableName
    Export:
      Name: !Sub '${AWS::StackName}-TargetAccountsTable'

  TargetAccountsTableArn:
    Description: 'DynamoDB table ARN for Target Accounts'
    Value: !GetAtt DatabaseStack.Outputs.TargetAccountsTableArn
    Export:
      Name: !Sub '${AWS::StackName}-TargetAccountsTableArn'

  # Lambda Stack Outputs
  ApiHandlerFunctionArn:
    Description: 'API Handler Lambda Function ARN'
    Value: !GetAtt LambdaStack.Outputs.ApiHandlerFunctionArn
    Export:
      Name: !Sub '${AWS::StackName}-ApiHandlerArn'

  OrchestrationFunctionArn:
    Description: 'Orchestration Lambda Function ARN'
    Value: !GetAtt LambdaStack.Outputs.OrchestrationStepFunctionsFunctionArn
    Export:
      Name: !Sub '${AWS::StackName}-OrchestrationArn'

  # API Stack Outputs
  UserPoolId:
    Description: 'Cognito User Pool ID'
    Value: !GetAtt ApiAuthStack.Outputs.UserPoolId
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolId'

  UserPoolClientId:
    Description: 'Cognito User Pool Client ID'
    Value: !GetAtt ApiAuthStack.Outputs.UserPoolClientId
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolClientId'

  IdentityPoolId:
    Description: 'Cognito Identity Pool ID'
    Value: !GetAtt ApiAuthStack.Outputs.IdentityPoolId
    Export:
      Name: !Sub '${AWS::StackName}-IdentityPoolId'

  ApiEndpoint:
    Description: 'API Gateway endpoint URL'
    Value: !GetAtt ApiGatewayStack.Outputs.ApiEndpoint
    Export:
      Name: !Sub '${AWS::StackName}-ApiEndpoint'

  ApiId:
    Description: 'API Gateway ID'
    Value: !GetAtt ApiGatewayStack.Outputs.ApiId
    Export:
      Name: !Sub '${AWS::StackName}-ApiId'

  StateMachineArn:
    Description: 'Step Functions State Machine ARN'
    Value: !GetAtt StepFunctionsStack.Outputs.StateMachineArn
    Export:
      Name: !Sub '${AWS::StackName}-StateMachineArn'

  # EventBridge Stack Outputs
  EventBridgeRoleArn:
    Description: 'EventBridge invoke role ARN'
    Value: !GetAtt EventBridgeStack.Outputs.EventBridgeInvokeRoleArn
    Export:
      Name: !Sub '${AWS::StackName}-EventBridgeRoleArn'

  TagSyncScheduleRuleName:
    Description: 'Tag sync schedule rule name'
    Value: !GetAtt EventBridgeStack.Outputs.TagSyncScheduleRuleName
    Export:
      Name: !Sub '${AWS::StackName}-TagSyncScheduleRuleName'
    Condition: EnableTagSyncCondition

  TagSyncScheduleExpression:
    Description: 'Tag sync schedule expression'
    Value: !GetAtt EventBridgeStack.Outputs.TagSyncScheduleExpression
    Export:
      Name: !Sub '${AWS::StackName}-TagSyncScheduleExpression'
    Condition: EnableTagSyncCondition


  # Frontend Stack Outputs
  CloudFrontUrl:
    Description: 'CloudFront Distribution URL'
    Value: !GetAtt FrontendStack.Outputs.CloudFrontUrl
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontUrl'

  CloudFrontDistributionId:
    Description: 'CloudFront Distribution ID'
    Value: !GetAtt FrontendStack.Outputs.CloudFrontDistributionId
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontDistributionId'

  FrontendBucketName:
    Description: 'S3 bucket for frontend hosting'
    Value: !GetAtt FrontendStack.Outputs.FrontendBucketName
    Export:
      Name: !Sub '${AWS::StackName}-FrontendBucket'



  # General Outputs
  Region:
    Description: 'AWS Region'
    Value: !Ref AWS::Region
    Export:
      Name: !Sub '${AWS::StackName}-Region'

  DeploymentBucket:
    Description: 'S3 bucket used for deployment artifacts'
    Value: !Ref SourceBucket
    Export:
      Name: !Sub '${AWS::StackName}-DeploymentBucket'

  # Security Stack Outputs (Conditional)
  WAFWebAclId:
    Description: 'WAF Web ACL ID'
    Value: !GetAtt SecurityStack.Outputs.WAFWebAclId
    Export:
      Name: !Sub '${AWS::StackName}-WAFWebAclId'
    Condition: EnableSecurityStackCondition

  CloudTrailArn:
    Description: 'CloudTrail ARN'
    Value: !GetAtt SecurityStack.Outputs.CloudTrailArn
    Export:
      Name: !Sub '${AWS::StackName}-CloudTrailArn'
    Condition: EnableSecurityStackCondition
