AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS DRS Orchestration Solution - Master Template'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'General Configuration'
        Parameters:
          - ProjectName
          - Environment
      - Label:
          default: 'Authentication Configuration'
        Parameters:
          - AdminEmail
          - CognitoDomainPrefix
      - Label:
          default: 'Lambda Configuration'
        Parameters:
          - LambdaCodeBucket
          - LambdaCodeKey
      - Label:
          default: 'Frontend Configuration'
        Parameters:
          - FrontendCodeBucket
          - FrontendCodeKey
      - Label:
          default: 'Notification Configuration'
        Parameters:
          - NotificationEmail

Parameters:
  ProjectName:
    Type: String
    Default: 'drs-orchestration'
    Description: 'Project name used for resource naming'
    AllowedPattern: '^[a-z0-9-]+$'
    ConstraintDescription: 'Must contain only lowercase letters, numbers, and hyphens'

  Environment:
    Type: String
    Default: 'prod'
    Description: 'Environment name (dev, test, prod)'
    AllowedValues:
      - dev
      - test
      - prod

  AdminEmail:
    Type: String
    Description: 'Email address for initial Cognito admin user'
    AllowedPattern: '^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
    ConstraintDescription: 'Must be a valid email address'

  CognitoDomainPrefix:
    Type: String
    Default: ''
    Description: 'Optional: Custom domain prefix for Cognito (leave empty for auto-generated)'

  LambdaCodeBucket:
    Type: String
    Default: ''
    Description: 'Optional: S3 bucket containing Lambda deployment packages (leave empty to use inline code)'

  LambdaCodeKey:
    Type: String
    Default: ''
    Description: 'Optional: S3 key prefix for Lambda code'

  FrontendCodeBucket:
    Type: String
    Default: ''
    Description: 'Optional: S3 bucket containing frontend source code'

  FrontendCodeKey:
    Type: String
    Default: ''
    Description: 'Optional: S3 key for frontend source code zip'

  NotificationEmail:
    Type: String
    Default: ''
    Description: 'Optional: Email address for execution notifications (leave empty to skip)'

Conditions:
  HasLambdaCodeBucket: !Not [!Equals [!Ref LambdaCodeBucket, '']]
  HasFrontendCodeBucket: !Not [!Equals [!Ref FrontendCodeBucket, '']]
  HasNotificationEmail: !Not [!Equals [!Ref NotificationEmail, '']]
  HasCognitoDomain: !Not [!Equals [!Ref CognitoDomainPrefix, '']]

Resources:
  # DynamoDB Tables
  ProtectionGroupsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-protection-groups'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: GroupId
          AttributeType: S
      KeySchema:
        - AttributeName: GroupId
          KeyType: HASH
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  RecoveryPlansTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-recovery-plans'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PlanId
          AttributeType: S
      KeySchema:
        - AttributeName: PlanId
          KeyType: HASH
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  ExecutionHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-execution-history'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: ExecutionId
          AttributeType: S
        - AttributeName: PlanId
          AttributeType: S
        - AttributeName: StartTime
          AttributeType: N
      KeySchema:
        - AttributeName: ExecutionId
          KeyType: HASH
        - AttributeName: PlanId
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: PlanIdIndex
          KeySchema:
            - AttributeName: PlanId
              KeyType: HASH
            - AttributeName: StartTime
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # S3 Bucket for Frontend Hosting
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-frontend-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # CloudFront Origin Access Control
  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub '${ProjectName}-oac'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub '${ProjectName} Frontend Distribution'
        DefaultRootObject: index.html
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            OriginAccessControlId: !Ref CloudFrontOAC
            S3OriginConfig:
              OriginAccessIdentity: ''
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          Compress: true
          DefaultTTL: 86400
          MaxTTL: 31536000
          MinTTL: 0
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
        PriceClass: PriceClass_100
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # S3 Bucket Policy for CloudFront
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub '${FrontendBucket.Arn}/*'
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}'

  # Cognito User Pool
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub '${ProjectName}-users'
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: false
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: true
      UserAttributeUpdateSettings:
        AttributesRequireVerificationBeforeUpdate:
          - email
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      UserPoolTags:
        Project: !Ref ProjectName
        Environment: !Ref Environment

  # Cognito User Pool Client
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub '${ProjectName}-client'
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      PreventUserExistenceErrors: ENABLED
      AccessTokenValidity: 60
      IdTokenValidity: 60
      RefreshTokenValidity: 30
      TokenValidityUnits:
        AccessToken: minutes
        IdToken: minutes
        RefreshToken: days

  # Cognito Identity Pool
  IdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: !Sub '${ProjectName}_identity_pool'
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId: !Ref UserPoolClient
          ProviderName: !GetAtt UserPool.ProviderName

  # IAM Role for Authenticated Users
  CognitoAuthRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-cognito-auth-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                cognito-identity.amazonaws.com:aud: !Ref IdentityPool
              ForAnyValue:StringLike:
                cognito-identity.amazonaws.com:amr: authenticated
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonCognitoReadOnly
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # Attach Identity Pool Roles
  IdentityPoolRoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref IdentityPool
      Roles:
        authenticated: !GetAtt CognitoAuthRole.Arn

  # SNS Topic for Notifications (Optional)
  NotificationTopic:
    Type: AWS::SNS::Topic
    Condition: HasNotificationEmail
    Properties:
      TopicName: !Sub '${ProjectName}-notifications'
      DisplayName: 'DRS Orchestration Notifications'
      Subscription:
        - Endpoint: !Ref NotificationEmail
          Protocol: email
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # Lambda Nested Stack
  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${LambdaCodeBucket}/lambda-stack.yaml'
      Parameters:
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        ProtectionGroupsTableName: !Ref ProtectionGroupsTable
        RecoveryPlansTableName: !Ref RecoveryPlansTable
        ExecutionHistoryTableName: !Ref ExecutionHistoryTable
        FrontendBucketName: !Ref FrontendBucket
        CloudFrontDistributionId: !Ref CloudFrontDistribution
        NotificationTopicArn: !If [HasNotificationEmail, !Ref NotificationTopic, '']
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

Outputs:
  ProtectionGroupsTableName:
    Description: 'DynamoDB table for Protection Groups'
    Value: !Ref ProtectionGroupsTable
    Export:
      Name: !Sub '${AWS::StackName}-ProtectionGroupsTable'

  RecoveryPlansTableName:
    Description: 'DynamoDB table for Recovery Plans'
    Value: !Ref RecoveryPlansTable
    Export:
      Name: !Sub '${AWS::StackName}-RecoveryPlansTable'

  ExecutionHistoryTableName:
    Description: 'DynamoDB table for Execution History'
    Value: !Ref ExecutionHistoryTable
    Export:
      Name: !Sub '${AWS::StackName}-ExecutionHistoryTable'

  UserPoolId:
    Description: 'Cognito User Pool ID'
    Value: !Ref UserPool
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolId'

  UserPoolClientId:
    Description: 'Cognito User Pool Client ID'
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolClientId'

  IdentityPoolId:
    Description: 'Cognito Identity Pool ID'
    Value: !Ref IdentityPool
    Export:
      Name: !Sub '${AWS::StackName}-IdentityPoolId'

  CloudFrontUrl:
    Description: 'CloudFront Distribution URL'
    Value: !Sub 'https://${CloudFrontDistribution.DomainName}'
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontUrl'

  FrontendBucketName:
    Description: 'S3 bucket for frontend hosting'
    Value: !Ref FrontendBucket
    Export:
      Name: !Sub '${AWS::StackName}-FrontendBucket'

  NotificationTopicArn:
    Description: 'SNS Topic ARN for notifications'
    Value: !If [HasNotificationEmail, !Ref NotificationTopic, '']
    Export:
      Name: !Sub '${AWS::StackName}-NotificationTopicArn'

  Region:
    Description: 'AWS Region'
    Value: !Ref AWS::Region
    Export:
      Name: !Sub '${AWS::StackName}-Region'
