AWSTemplateFormatVersion: '2010-09-09'
Description: |
  AWS DRS Orchestration - SNS Notification Infrastructure
  
  Provides multi-channel notification system for DR orchestration events.
  
  Notification Channels:
  - ExecutionNotificationsTopic: DR execution lifecycle events (start, complete, fail)
  - DRSOperationalAlertsTopic: Real-time DRS service alerts via EventBridge
  - ExecutionPauseTopic: Human approval gates for wave transitions
  
  Event Sources:
  - Step Functions: Execution status changes, pause gates
  - Lambda Functions: Custom notifications, error alerts
  - EventBridge: Native DRS service events (replication stalled, launch failures)
  
  Integration Points:
  - Notification Formatter Lambda: Transforms raw events into human-readable messages
  - Step Functions: Publishes to pause topic for manual approval workflows
  - EventBridge Rules: Captures DRS native events for operational alerting

Parameters:
  ProjectName:
    Type: String
    Description: 'Project name for resource naming'
  
  Environment:
    Type: String
    Description: 'Environment name (dev, test, prod)'
  
  AdminEmail:
    Type: String
    Description: 'Admin email for critical notifications'

Resources:
  # =============================================================================
  # EXECUTION NOTIFICATIONS
  # =============================================================================
  # Primary notification channel for DR execution lifecycle events.
  # Receives messages from:
  # - Step Functions: Execution start, completion, failure
  # - Lambda Functions: Custom status updates, error notifications
  # - Notification Formatter: Human-readable execution summaries
  
  ExecutionNotificationsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${ProjectName}-execution-notifications-${Environment}'
      DisplayName: 'DRS Orchestration Execution Notifications'
      KmsMasterKeyId: alias/aws/sns
      
  # Email subscription for admin notifications
  # Requires email confirmation before notifications are delivered
  ExecutionNotificationsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn: !Ref ExecutionNotificationsTopic
      Endpoint: !Ref AdminEmail

  # =============================================================================
  # DRS OPERATIONAL ALERTS
  # =============================================================================
  # Real-time alerts for DRS service health and operational issues.
  # Receives messages from:
  # - EventBridge Rules: Native DRS events (replication stalled, launch failures)
  # - Lambda Functions: Custom DRS health checks, threshold alerts
  # Use case: Immediate notification of DRS issues requiring attention
  
  DRSOperationalAlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${ProjectName}-drs-alerts-${Environment}'
      DisplayName: 'DRS Operational Alerts'
      KmsMasterKeyId: alias/aws/sns
      
  # Email subscription for DRS operational alerts
  DRSOperationalAlertsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn: !Ref DRSOperationalAlertsTopic
      Endpoint: !Ref AdminEmail

  # =============================================================================
  # EXECUTION PAUSE TOPIC
  # =============================================================================
  # Human approval gates for wave-based DR orchestration.
  # Receives messages from:
  # - Step Functions: Pause state notifications requiring manual approval
  # Use case: Enables human-in-the-loop validation between DR waves
  # Workflow: Step Functions pauses → SNS notification → Admin reviews → Resume via API
  
  ExecutionPauseTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${ProjectName}-execution-pause-${Environment}'
      DisplayName: 'DRS Orchestration Execution Pause'
      KmsMasterKeyId: alias/aws/sns
      
  # Email subscription for pause notifications
  ExecutionPauseSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn: !Ref ExecutionPauseTopic
      Endpoint: !Ref AdminEmail

  # =============================================================================
  # EVENTBRIDGE RULES FOR DRS EVENTS
  # =============================================================================
  # Captures native AWS DRS service events and routes to operational alerts.
  # DRS emits events for: replication status changes, launch results, agent health
  # These rules filter for critical events requiring immediate attention.
  
  # Rule: DRS Recovery Launch Failures
  # Triggers when a DRS recovery instance fails to launch
  # Common causes: IAM permissions, subnet capacity, instance type availability
  DRSRecoveryFailureRule:
    Type: AWS::Events::Rule
    Properties:
      Description: 'EventBridge rule for DRS recovery launch failures'
      State: ENABLED
      EventPattern:
        source: ["aws.drs"]
        detail-type: ["DRS Source Server Launch Result"]
        detail:
          state: ["RECOVERY_LAUNCH_FAILED"]
      Targets:
        - Arn: !Ref DRSOperationalAlertsTopic
          Id: DRSRecoveryFailureAlert
          InputTransformer:
            InputPathsMap:
              sourceServerId: "$.detail.sourceServerId"
              state: "$.detail.state"
              region: "$.region"
            InputTemplate: |
              {
                "alertType": "DRS Recovery Failure",
                "sourceServerId": "<sourceServerId>",
                "state": "<state>",
                "region": "<region>",
                "timestamp": "$.time",
                "message": "DRS recovery launch failed for source server <sourceServerId> in region <region>"
              }

  # Rule: DRS Replication Stalled
  # Triggers when data replication stops progressing
  # Common causes: Network issues, agent problems, storage constraints
  # Critical for maintaining RPO (Recovery Point Objective)
  DRSReplicationStalledRule:
    Type: AWS::Events::Rule
    Properties:
      Description: 'EventBridge rule for DRS replication stalled events'
      State: ENABLED
      EventPattern:
        source: ["aws.drs"]
        detail-type: ["DRS Source Server Data Replication Stalled Change"]
        detail:
          state: ["STALLED"]
      Targets:
        - Arn: !Ref DRSOperationalAlertsTopic
          Id: DRSReplicationStalledAlert
          InputTransformer:
            InputPathsMap:
              sourceServerId: "$.detail.sourceServerId"
              state: "$.detail.state"
              region: "$.region"
            InputTemplate: |
              {
                "alertType": "DRS Replication Stalled",
                "sourceServerId": "<sourceServerId>",
                "state": "<state>",
                "region": "<region>",
                "timestamp": "$.time",
                "message": "DRS replication stalled for source server <sourceServerId> in region <region>"
              }

  # =============================================================================
  # SNS TOPIC POLICIES
  # =============================================================================
  # Define which AWS services can publish to each SNS topic.
  # Follows least-privilege: only services that need to publish are allowed.
  
  # Policy: Execution Notifications Topic
  # Allows Lambda and Step Functions to publish execution status updates
  ExecutionNotificationsTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref ExecutionNotificationsTopic
      PolicyDocument:
        Id: ExecutionNotificationsTopicPolicy
        Version: '2012-10-17'
        Statement:
          - Sid: AllowLambdaPublish
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sns:Publish
            Resource: !Ref ExecutionNotificationsTopic
          - Sid: AllowStepFunctionsPublish
            Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sns:Publish
            Resource: !Ref ExecutionNotificationsTopic

  # Policy: DRS Operational Alerts Topic
  # Allows EventBridge to publish native DRS service events
  DRSOperationalAlertsTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref DRSOperationalAlertsTopic
      PolicyDocument:
        Id: DRSOperationalAlertsTopicPolicy
        Version: '2012-10-17'
        Statement:
          - Sid: AllowEventBridgePublish
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sns:Publish
            Resource: !Ref DRSOperationalAlertsTopic

  # Policy: Execution Pause Topic
  # Allows Step Functions to publish pause gate notifications
  ExecutionPauseTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref ExecutionPauseTopic
      PolicyDocument:
        Id: ExecutionPauseTopicPolicy
        Version: '2012-10-17'
        Statement:
          - Sid: AllowStepFunctionsPublish
            Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sns:Publish
            Resource: !Ref ExecutionPauseTopic

# =============================================================================
# OUTPUTS
# =============================================================================
# Exported values for cross-stack references.
# Other stacks (Lambda, Step Functions) import these ARNs to publish notifications.

Outputs:
  ExecutionNotificationsTopicArn:
    Description: 'ARN of the Execution Notifications SNS Topic'
    Value: !Ref ExecutionNotificationsTopic
    Export:
      Name: !Sub '${ProjectName}-execution-notifications-topic-${Environment}'

  DRSOperationalAlertsTopicArn:
    Description: 'ARN of the DRS Operational Alerts SNS Topic'
    Value: !Ref DRSOperationalAlertsTopic
    Export:
      Name: !Sub '${ProjectName}-drs-alerts-topic-${Environment}'

  ExecutionPauseTopicArn:
    Description: 'ARN of the Execution Pause SNS Topic'
    Value: !Ref ExecutionPauseTopic
    Export:
      Name: !Sub '${ProjectName}-execution-pause-topic-${Environment}'

