AWSTemplateFormatVersion: '2010-09-09'
Description: 'Security monitoring dashboard and alerting for AWS DRS Orchestration'

Parameters:
  ProjectName:
    Type: String
    Description: Name of the project for resource naming
    Default: aws-drs-orchestrator
    
  Environment:
    Type: String
    Description: Environment name (dev, test, prod)
    AllowedValues: [dev, test, prod]
    Default: test
    
  SecurityTeamEmail:
    Type: String
    Description: Email address for security alerts
    Default: security-team@example.com

Resources:
  # SNS Topic for Security Alerts
  SecurityAlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${ProjectName}-security-alerts-${Environment}'
      DisplayName: 'DRS Orchestration Security Alerts'
      
  SecurityAlertsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn: !Ref SecurityAlertsTopic
      Endpoint: !Ref SecurityTeamEmail

  # CloudWatch Dashboard for Security Monitoring
  SecurityDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub '${ProjectName}-security-${Environment}'
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "text",
              "x": 0,
              "y": 0,
              "width": 24,
              "height": 2,
              "properties": {
                "markdown": "# AWS DRS Orchestration Security Dashboard\n\nMonitoring security events, vulnerabilities, and compliance status for ${Environment} environment."
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 2,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/Lambda", "Errors", "FunctionName", "${ProjectName}-lambda-${Environment}" ],
                  [ ".", "Duration", ".", "." ],
                  [ ".", "Invocations", ".", "." ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "Lambda Security Events",
                "period": 300,
                "stat": "Sum"
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 2,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/ApiGateway", "4XXError", "ApiName", "${ProjectName}-api-${Environment}" ],
                  [ ".", "5XXError", ".", "." ],
                  [ ".", "Count", ".", "." ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "API Gateway Security Metrics",
                "period": 300,
                "stat": "Sum"
              }
            },
            {
              "type": "log",
              "x": 0,
              "y": 8,
              "width": 24,
              "height": 6,
              "properties": {
                "query": "SOURCE '/aws/lambda/${ProjectName}-lambda-${Environment}'\n| fields @timestamp, @message\n| filter @message like /SECURITY/\n| sort @timestamp desc\n| limit 100",
                "region": "${AWS::Region}",
                "title": "Security Log Events",
                "view": "table"
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 14,
              "width": 8,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/DynamoDB", "ConsumedReadCapacityUnits", "TableName", "${ProjectName}-protection-groups-${Environment}" ],
                  [ ".", "ConsumedWriteCapacityUnits", ".", "." ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "DynamoDB Access Patterns",
                "period": 300,
                "stat": "Sum"
              }
            },
            {
              "type": "metric",
              "x": 8,
              "y": 14,
              "width": 8,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/CloudFront", "Requests", "DistributionId", "DISTRIBUTION_ID" ],
                  [ ".", "BytesDownloaded", ".", "." ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "us-east-1",
                "title": "Frontend Access Patterns",
                "period": 300,
                "stat": "Sum"
              }
            },
            {
              "type": "metric",
              "x": 16,
              "y": 14,
              "width": 8,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/CodeBuild", "Builds", "ProjectName", "${ProjectName}-security-scan-${Environment}" ],
                  [ ".", "FailedBuilds", ".", "." ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "Security Scan Results",
                "period": 300,
                "stat": "Sum"
              }
            }
          ]
        }

  # CloudWatch Alarms for Security Events
  HighErrorRateAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-high-error-rate-${Environment}'
      AlarmDescription: 'High error rate detected in Lambda functions'
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Sub '${ProjectName}-lambda-${Environment}'
      AlarmActions:
        - !Ref SecurityAlertsTopic

  UnauthorizedAccessAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-unauthorized-access-${Environment}'
      AlarmDescription: 'High rate of 4XX errors indicating potential unauthorized access'
      MetricName: 4XXError
      Namespace: AWS/ApiGateway
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 50
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiName
          Value: !Sub '${ProjectName}-api-${Environment}'
      AlarmActions:
        - !Ref SecurityAlertsTopic

  SecurityScanFailureAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-security-scan-failure-${Environment}'
      AlarmDescription: 'Security scan build failures detected'
      MetricName: FailedBuilds
      Namespace: AWS/CodeBuild
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: ProjectName
          Value: !Sub '${ProjectName}-security-scan-${Environment}'
      AlarmActions:
        - !Ref SecurityAlertsTopic

  # Custom Metrics for Security Events
  SecurityMetricsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-security-metrics-${Environment}'
      RetentionInDays: 30

  # Metric Filters for Security Events
  CriticalVulnerabilityMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Ref SecurityMetricsLogGroup
      FilterPattern: '[timestamp, requestId, level="CRITICAL", event="VULNERABILITY", ...]'
      MetricTransformations:
        - MetricNamespace: !Sub '${ProjectName}/Security'
          MetricName: CriticalVulnerabilities
          MetricValue: '1'
          DefaultValue: 0

  AuthenticationFailureMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-lambda-${Environment}'
      FilterPattern: '[timestamp, requestId, level="ERROR", event="AUTH_FAILURE", ...]'
      MetricTransformations:
        - MetricNamespace: !Sub '${ProjectName}/Security'
          MetricName: AuthenticationFailures
          MetricValue: '1'
          DefaultValue: 0

  InputValidationFailureMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-lambda-${Environment}'
      FilterPattern: '[timestamp, requestId, level="WARN", event="INPUT_VALIDATION_FAILURE", ...]'
      MetricTransformations:
        - MetricNamespace: !Sub '${ProjectName}/Security'
          MetricName: InputValidationFailures
          MetricValue: '1'
          DefaultValue: 0

  # Alarms for Custom Security Metrics
  CriticalVulnerabilityAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-critical-vulnerability-${Environment}'
      AlarmDescription: 'Critical security vulnerability detected'
      MetricName: CriticalVulnerabilities
      Namespace: !Sub '${ProjectName}/Security'
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref SecurityAlertsTopic
      TreatMissingData: notBreaching

  AuthenticationFailureAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-auth-failure-${Environment}'
      AlarmDescription: 'High rate of authentication failures'
      MetricName: AuthenticationFailures
      Namespace: !Sub '${ProjectName}/Security'
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref SecurityAlertsTopic
      TreatMissingData: notBreaching

  # IAM Role for Security Monitoring
  SecurityMonitoringRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-security-monitoring-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: SecurityMonitoringPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*'
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                  - cloudwatch:GetMetricStatistics
                  - cloudwatch:ListMetrics
                Resource: '*'
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref SecurityAlertsTopic

Outputs:
  SecurityDashboardURL:
    Description: 'URL to the CloudWatch Security Dashboard'
    Value: !Sub 'https://${AWS::Region}.console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=${ProjectName}-security-${Environment}'
    Export:
      Name: !Sub '${ProjectName}-security-dashboard-url-${Environment}'

  SecurityAlertsTopicArn:
    Description: 'ARN of the Security Alerts SNS Topic'
    Value: !Ref SecurityAlertsTopic
    Export:
      Name: !Sub '${ProjectName}-security-alerts-topic-${Environment}'

  SecurityMonitoringRoleArn:
    Description: 'ARN of the Security Monitoring IAM Role'
    Value: !GetAtt SecurityMonitoringRole.Arn
    Export:
      Name: !Sub '${ProjectName}-security-monitoring-role-${Environment}'