AWSTemplateFormatVersion: '2010-09-09'
Description: 'Step Functions State Machine for DRS Orchestration - Based on drs-plan-automation reference'

Parameters:
  ProjectName:
    Type: String
    Description: 'Project name for resource naming'
    Default: 'drs-orchestration'
  
  Environment:
    Type: String
    Description: 'Environment name (dev, test, prod)'
    Default: 'test'
  
  OrchestrationLambdaArn:
    Type: String
    Description: 'ARN of the orchestration Lambda function'

Resources:
  # Step Functions State Machine - Based on drs-plan-automation reference
  DRSOrchestrationStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub '${ProjectName}-state-machine-${Environment}'
      RoleArn: !GetAtt StateMachineRole.Arn
      Definition:
        Comment: 'DRS Recovery Plan Orchestration - Wait/Poll/Check/Loop pattern from reference implementation'
        StartAt: 'InitiateWavePlan'
        States:
          # Step 1: Initialize the wave plan
          InitiateWavePlan:
            Type: Task
            Resource: 'arn:aws:states:::lambda:invoke'
            Parameters:
              FunctionName: !Ref OrchestrationLambdaArn
              Payload:
                action: 'begin'
                execution.$: '$.Execution.Id'
                plan.$: '$.Plan'
                isDrill.$: '$.IsDrill'
            ResultPath: '$.application'
            ResultSelector:
              plan_id.$: '$.Payload.plan_id'
              execution_id.$: '$.Payload.execution_id'
              is_drill.$: '$.Payload.is_drill'
              waves.$: '$.Payload.waves'
              current_wave_number.$: '$.Payload.current_wave_number'
              all_waves_completed.$: '$.Payload.all_waves_completed'
              wave_completed.$: '$.Payload.wave_completed'
              current_wave_update_time.$: '$.Payload.current_wave_update_time'
              current_wave_total_wait_time.$: '$.Payload.current_wave_total_wait_time'
              current_wave_max_wait_time.$: '$.Payload.current_wave_max_wait_time'
              status.$: '$.Payload.status'
              job_id.$: '$.Payload.job_id'
              region.$: '$.Payload.region'
              server_ids.$: '$.Payload.server_ids'
              wave_results.$: '$.Payload.wave_results'
              error.$: '$.Payload.error'
            Next: 'DetermineWavePlanState'
            Retry:
              - ErrorEquals:
                  - 'Lambda.ServiceException'
                  - 'Lambda.AWSLambdaException'
                  - 'Lambda.SdkClientException'
                IntervalSeconds: 2
                MaxAttempts: 6
                BackoffRate: 2
          
          # Step 2: Check overall plan state
          DetermineWavePlanState:
            Type: Choice
            Choices:
              # Check for failure
              - Variable: '$.application.status'
                StringEquals: 'failed'
                Next: 'PlanFailed'
              # Check for timeout
              - Variable: '$.application.status'
                StringEquals: 'timeout'
                Next: 'PlanTimeout'
              # Check if all waves completed
              - Variable: '$.application.all_waves_completed'
                BooleanEquals: true
                Next: 'PlanCompleted'
              # Otherwise check wave state
              - Variable: '$.application.all_waves_completed'
                BooleanEquals: false
                Next: 'DetermineWaveState'
            Default: 'DetermineWaveState'
          
          # Step 3: Check current wave state
          DetermineWaveState:
            Type: Choice
            Choices:
              # Check for failure
              - Variable: '$.application.status'
                StringEquals: 'failed'
                Next: 'PlanFailed'
              # Check for timeout
              - Variable: '$.application.status'
                StringEquals: 'timeout'
                Next: 'PlanTimeout'
              # Check if all waves completed (after wave completion)
              - Variable: '$.application.all_waves_completed'
                BooleanEquals: true
                Next: 'PlanCompleted'
              # Check if current wave is still in progress
              - Variable: '$.application.wave_completed'
                BooleanEquals: false
                Next: 'WaitForWaveUpdate'
              # Wave completed, check plan state
              - Variable: '$.application.wave_completed'
                BooleanEquals: true
                Next: 'DetermineWavePlanState'
            Default: 'WaitForWaveUpdate'
          
          # Step 4: Wait before polling (dynamic wait time from application state)
          WaitForWaveUpdate:
            Type: Wait
            SecondsPath: '$.application.current_wave_update_time'
            Next: 'UpdateWaveStatus'
          
          # Step 5: Poll DRS job status and check server launch status
          UpdateWaveStatus:
            Type: Task
            Resource: 'arn:aws:states:::lambda:invoke'
            Parameters:
              FunctionName: !Ref OrchestrationLambdaArn
              Payload:
                action: 'update_wave_status'
                application.$: '$.application'
            ResultPath: '$.application'
            ResultSelector:
              plan_id.$: '$.Payload.plan_id'
              execution_id.$: '$.Payload.execution_id'
              is_drill.$: '$.Payload.is_drill'
              waves.$: '$.Payload.waves'
              current_wave_number.$: '$.Payload.current_wave_number'
              all_waves_completed.$: '$.Payload.all_waves_completed'
              wave_completed.$: '$.Payload.wave_completed'
              current_wave_update_time.$: '$.Payload.current_wave_update_time'
              current_wave_total_wait_time.$: '$.Payload.current_wave_total_wait_time'
              current_wave_max_wait_time.$: '$.Payload.current_wave_max_wait_time'
              status.$: '$.Payload.status'
              job_id.$: '$.Payload.job_id'
              region.$: '$.Payload.region'
              server_ids.$: '$.Payload.server_ids'
              wave_results.$: '$.Payload.wave_results'
              error.$: '$.Payload.error'
            Next: 'DetermineWaveState'
            Retry:
              - ErrorEquals:
                  - 'Lambda.ServiceException'
                  - 'Lambda.AWSLambdaException'
                  - 'Lambda.SdkClientException'
                IntervalSeconds: 2
                MaxAttempts: 6
                BackoffRate: 2
          
          # Success state
          PlanCompleted:
            Type: Succeed
          
          # Failure states
          PlanFailed:
            Type: Fail
            Error: 'PlanExecutionFailed'
            Cause: 'DRS recovery plan execution failed'
          
          PlanTimeout:
            Type: Fail
            Error: 'PlanExecutionTimeout'
            Cause: 'DRS recovery plan execution timed out'
  
  # IAM Role for Step Functions
  StateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-statemachine-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: !Sub '${ProjectName}-statemachine-policy-${Environment}'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'lambda:InvokeFunction'
                Resource: !Ref OrchestrationLambdaArn
              - Effect: Allow
                Action:
                  - 'logs:CreateLogDelivery'
                  - 'logs:GetLogDelivery'
                  - 'logs:UpdateLogDelivery'
                  - 'logs:DeleteLogDelivery'
                  - 'logs:ListLogDeliveries'
                  - 'logs:PutResourcePolicy'
                  - 'logs:DescribeResourcePolicies'
                  - 'logs:DescribeLogGroups'
                Resource: '*'

Outputs:
  StateMachineArn:
    Description: 'ARN of the DRS Orchestration State Machine'
    Value: !Ref DRSOrchestrationStateMachine
    Export:
      Name: !Sub '${ProjectName}-state-machine-arn-${Environment}'
  
  StateMachineName:
    Description: 'Name of the DRS Orchestration State Machine'
    Value: !GetAtt DRSOrchestrationStateMachine.Name
    Export:
      Name: !Sub '${ProjectName}-state-machine-name-${Environment}'
