AWSTemplateFormatVersion: '2010-09-09'
Description: 'Step Functions State Machine for DRS Orchestration - Simple Map State Pattern (Working Archive Pattern)'

Parameters:
  ProjectName:
    Type: String
    Description: 'Project name for resource naming'
    Default: 'drs-orchestration'
  
  Environment:
    Type: String
    Description: 'Environment name (dev, test, prod)'
    Default: 'test'
  
  OrchestrationLambdaArn:
    Type: String
    Description: 'ARN of the orchestration Lambda function'
  
  ApiHandlerFunctionName:
    Type: String
    Description: 'Name of the API handler Lambda function'

Resources:
  # Step Functions State Machine - Simple Map State Pattern (from working archive)
  DRSOrchestrationStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub '${ProjectName}-orchestration-${Environment}'
      RoleArn: !GetAtt StateMachineRole.Arn
      Definition:
        Comment: 'DRS Recovery Plan Orchestration - Simple Map State Pattern'
        StartAt: 'InitializeExecution'
        States:
          # Step 1: Initialize the execution context
          InitializeExecution:
            Type: Task
            Resource: !Ref OrchestrationLambdaArn
            Parameters:
              action: 'initialize'
              executionId.$: '$$.Execution.Name'
              input.$: '$'
            ResultPath: '$.executionContext'
            Next: 'ProcessWaves'
            Retry:
              - ErrorEquals:
                  - 'Lambda.ServiceException'
                  - 'Lambda.AWSLambdaException'
                  - 'Lambda.SdkClientException'
                IntervalSeconds: 2
                MaxAttempts: 6
                BackoffRate: 2
          
          # Step 2: Process all waves using Map state (simple pattern)
          ProcessWaves:
            Type: Map
            ItemsPath: '$.executionContext.waves'
            Iterator:
              StartAt: 'ProcessWave'
              States:
                ProcessWave:
                  Type: Task
                  Resource: !Ref OrchestrationLambdaArn
                  Parameters:
                    action: 'processWave'
                    wave.$: '$'
                    executionId.$: '$$.Execution.Name'
                    isDrill.$: '$.isDrill'
                    AccountContext.$: '$.AccountContext'
                  ResultPath: '$.waveResult'
                  End: true
                  Retry:
                    - ErrorEquals:
                        - 'Lambda.ServiceException'
                        - 'Lambda.AWSLambdaException'
                        - 'Lambda.SdkClientException'
                      IntervalSeconds: 2
                      MaxAttempts: 6
                      BackoffRate: 2
            ResultPath: '$.waveResults'
            Next: 'FinalizeExecution'
          
          # Step 3: Finalize the execution
          FinalizeExecution:
            Type: Task
            Resource: !Ref OrchestrationLambdaArn
            Parameters:
              action: 'finalize'
              executionId.$: '$$.Execution.Name'
              results.$: '$.waveResults'
            End: true
            Retry:
              - ErrorEquals:
                  - 'Lambda.ServiceException'
                  - 'Lambda.AWSLambdaException'
                  - 'Lambda.SdkClientException'
                IntervalSeconds: 2
                MaxAttempts: 6
                BackoffRate: 2
  
  # IAM Role for Step Functions
  StateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-statemachine-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: !Sub '${ProjectName}-statemachine-policy-${Environment}'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'lambda:InvokeFunction'
                Resource: !Ref OrchestrationLambdaArn
              - Effect: Allow
                Action:
                  - 'logs:CreateLogDelivery'
                  - 'logs:GetLogDelivery'
                  - 'logs:UpdateLogDelivery'
                  - 'logs:DeleteLogDelivery'
                  - 'logs:ListLogDeliveries'
                  - 'logs:PutResourcePolicy'
                  - 'logs:DescribeResourcePolicies'
                  - 'logs:DescribeLogGroups'
                Resource: '*'

Outputs:
  StateMachineArn:
    Description: 'ARN of the DRS Orchestration State Machine'
    Value: !Ref DRSOrchestrationStateMachine
    Export:
      Name: !Sub '${ProjectName}-state-machine-arn-${Environment}'
  
  StateMachineName:
    Description: 'Name of the DRS Orchestration State Machine'
    Value: !GetAtt DRSOrchestrationStateMachine.Name
    Export:
      Name: !Sub '${ProjectName}-state-machine-name-${Environment}'
