AWSTemplateFormatVersion: '2010-09-09'
Description: 'Step Functions State Machine for DRS Orchestration - Complete Archive Pattern Implementation'

Parameters:
  ProjectName:
    Type: String
    Description: 'Project name for resource naming'
    Default: 'drs-orchestration'
  
  Environment:
    Type: String
    Description: 'Environment name (dev, test, prod)'
    Default: 'test'
  
  OrchestrationLambdaArn:
    Type: String
    Description: 'ARN of the orchestration Lambda function'
  
  ApiHandlerFunctionName:
    Type: String
    Description: 'Name of the API handler Lambda function'

Resources:
  # Step Functions State Machine - Complete Archive Pattern Implementation
  DRSOrchestrationStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub '${ProjectName}-orchestration-${Environment}'
      RoleArn: !GetAtt StateMachineRole.Arn
      LoggingConfiguration:
        Level: ALL
        IncludeExecutionData: true
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt StateMachineLogGroup.Arn
      Definition:
        Comment: 'DRS Recovery Plan Orchestration - Complete Archive Pattern with Error Handling'
        StartAt: 'InitiateWavePlan'
        States:
          # Step 1: Initialize the wave plan - Lambda returns FULL state
          InitiateWavePlan:
            Type: Task
            Resource: 'arn:aws:states:::lambda:invoke'
            Parameters:
              FunctionName: !Ref OrchestrationLambdaArn
              Payload:
                action: 'begin'
                execution.$: '$.Execution.Id'
                plan.$: '$.Plan'
                isDrill.$: '$.IsDrill'
                AccountContext.$: '$.AccountContext'
                ResumeFromWave.$: '$.ResumeFromWave'
            OutputPath: '$.Payload'
            Next: 'DetermineWavePlanState'
            Retry:
              - ErrorEquals:
                  - 'Lambda.ServiceException'
                  - 'Lambda.AWSLambdaException'
                  - 'Lambda.SdkClientException'
                  - 'Lambda.TooManyRequestsException'
                IntervalSeconds: 2
                MaxAttempts: 6
                BackoffRate: 2
            Catch:
              - ErrorEquals:
                  - 'States.ALL'
                Next: 'HandleInitializationError'
          
          # Handle initialization errors
          HandleInitializationError:
            Type: Task
            Resource: 'arn:aws:states:::lambda:invoke'
            Parameters:
              FunctionName: !Ref OrchestrationLambdaArn
              Payload:
                action: 'handle_error'
                error_type: 'initialization_failed'
                error_details.$: '$.Error'
                cause.$: '$.Cause'
                execution.$: '$.Execution.Id'
                plan.$: '$.Plan'
                AccountContext.$: '$.AccountContext'
            OutputPath: '$.Payload'
            Next: 'PlanFailed'
          
          # Step 2: Check overall plan state
          DetermineWavePlanState:
            Type: Choice
            Choices:
              # Check for failure first
              - Variable: '$.status'
                StringEquals: 'failed'
                Next: 'PlanFailed'
              # Check for timeout
              - Variable: '$.status'
                StringEquals: 'timeout'
                Next: 'PlanTimeout'
              # Check for cancellation
              - Variable: '$.status'
                StringEquals: 'cancelled'
                Next: 'PlanCancelled'
              # Check for paused (PauseBeforeWave)
              - Variable: '$.status'
                StringEquals: 'paused'
                Next: 'WaitForResume'
              # Check if all waves completed
              - Variable: '$.all_waves_completed'
                BooleanEquals: true
                Next: 'PlanCompleted'
              # Otherwise check wave state
              - Variable: '$.all_waves_completed'
                BooleanEquals: false
                Next: 'DetermineWaveState'
            Default: 'DetermineWaveState'
          
          # Step 3: Check current wave state
          DetermineWaveState:
            Type: Choice
            Choices:
              # Check for failure first
              - Variable: '$.status'
                StringEquals: 'failed'
                Next: 'PlanFailed'
              # Check for timeout
              - Variable: '$.status'
                StringEquals: 'timeout'
                Next: 'PlanTimeout'
              # Check for cancellation
              - Variable: '$.status'
                StringEquals: 'cancelled'
                Next: 'PlanCancelled'
              # Check for paused (PauseBeforeWave) - CRITICAL: must check before wave_completed
              - Variable: '$.status'
                StringEquals: 'paused'
                Next: 'WaitForResume'
              # Check if all waves completed (after wave completion)
              - Variable: '$.all_waves_completed'
                BooleanEquals: true
                Next: 'PlanCompleted'
              # Check if current wave is still in progress
              - Variable: '$.wave_completed'
                BooleanEquals: false
                Next: 'WaitForWaveUpdate'
              # Wave completed, check plan state
              - Variable: '$.wave_completed'
                BooleanEquals: true
                Next: 'DetermineWavePlanState'
            Default: 'WaitForWaveUpdate'
          
          # Step 4: Wait before polling (with dynamic wait time)
          WaitForWaveUpdate:
            Type: Wait
            SecondsPath: '$.current_wave_update_time'
            Next: 'TransformForUpdate'
          
          # Pause state: Wait for external resume signal (callback pattern)
          WaitForResume:
            Type: Task
            Resource: 'arn:aws:states:::lambda:invoke.waitForTaskToken'
            Parameters:
              FunctionName: !Ref OrchestrationLambdaArn
              Payload:
                action: 'store_task_token'
                application.$: '$'
                taskToken.$: '$.Task.Token'
                AccountContext.$: '$.AccountContext'
            # NOTE: No OutputPath here - callback output is returned directly at root level
            TimeoutSeconds: 31536000  # 1 year max timeout for pause/resume
            Next: 'ResumeWavePlan'
            Catch:
              - ErrorEquals:
                  - 'States.Timeout'
                Next: 'PlanTimeout'
              - ErrorEquals:
                  - 'States.ALL'
                Next: 'HandleResumeError'
          
          # Handle resume errors
          HandleResumeError:
            Type: Task
            Resource: 'arn:aws:states:::lambda:invoke'
            Parameters:
              FunctionName: !Ref OrchestrationLambdaArn
              Payload:
                action: 'handle_error'
                error_type: 'resume_failed'
                error_details.$: '$.Error'
                cause.$: '$.Cause'
                application.$: '$'
                AccountContext.$: '$.AccountContext'
            OutputPath: '$.Payload'
            Next: 'PlanFailed'
          
          # After resume, start the next wave - Lambda returns FULL state
          ResumeWavePlan:
            Type: Task
            Resource: 'arn:aws:states:::lambda:invoke'
            Parameters:
              FunctionName: !Ref OrchestrationLambdaArn
              Payload:
                action: 'resume_wave'
                application.$: '$'
                AccountContext.$: '$.AccountContext'
            OutputPath: '$.Payload'
            Next: 'DetermineWaveState'
            Retry:
              - ErrorEquals:
                  - 'Lambda.ServiceException'
                  - 'Lambda.AWSLambdaException'
                  - 'Lambda.SdkClientException'
                  - 'Lambda.TooManyRequestsException'
                IntervalSeconds: 2
                MaxAttempts: 6
                BackoffRate: 2
            Catch:
              - ErrorEquals:
                  - 'States.ALL'
                Next: 'HandleResumeError'
          
          # Step 5: Transform data for Lambda compatibility
          TransformForUpdate:
            Type: Pass
            Parameters:
              action: 'update_wave_status'
              application.$: '$'
              AccountContext.$: '$.AccountContext'
            Next: 'UpdateWaveStatus'
          
          # Step 6: Poll DRS job status - Lambda returns FULL state
          UpdateWaveStatus:
            Type: Task
            Resource: 'arn:aws:states:::lambda:invoke'
            Parameters:
              FunctionName: !Ref OrchestrationLambdaArn
              Payload.$: '$'
            OutputPath: '$.Payload'
            Next: 'DetermineWaveState'
            Retry:
              - ErrorEquals:
                  - 'Lambda.ServiceException'
                  - 'Lambda.AWSLambdaException'
                  - 'Lambda.SdkClientException'
                  - 'Lambda.TooManyRequestsException'
                IntervalSeconds: 2
                MaxAttempts: 6
                BackoffRate: 2
              # DRS-specific retries
              - ErrorEquals:
                  - 'ConflictException'
                  - 'ThrottlingException'
                IntervalSeconds: 5
                MaxAttempts: 10
                BackoffRate: 2
            Catch:
              - ErrorEquals:
                  - 'States.ALL'
                Next: 'HandlePollingError'
          
          # Handle polling errors
          HandlePollingError:
            Type: Task
            Resource: 'arn:aws:states:::lambda:invoke'
            Parameters:
              FunctionName: !Ref OrchestrationLambdaArn
              Payload:
                action: 'handle_error'
                error_type: 'polling_failed'
                error_details.$: '$.Error'
                cause.$: '$.Cause'
                application.$: '$'
                AccountContext.$: '$.AccountContext'
            OutputPath: '$.Payload'
            Next: 'PlanFailed'
          
          # Success state
          PlanCompleted:
            Type: Succeed
          
          # Failure states with proper cleanup
          PlanFailed:
            Type: Task
            Resource: 'arn:aws:states:::lambda:invoke'
            Parameters:
              FunctionName: !Ref OrchestrationLambdaArn
              Payload:
                action: 'cleanup_failed_execution'
                application.$: '$'
                AccountContext.$: '$.AccountContext'
            End: true
          
          PlanTimeout:
            Type: Task
            Resource: 'arn:aws:states:::lambda:invoke'
            Parameters:
              FunctionName: !Ref OrchestrationLambdaArn
              Payload:
                action: 'cleanup_timeout_execution'
                application.$: '$'
                AccountContext.$: '$.AccountContext'
            End: true
          
          PlanCancelled:
            Type: Task
            Resource: 'arn:aws:states:::lambda:invoke'
            Parameters:
              FunctionName: !Ref OrchestrationLambdaArn
              Payload:
                action: 'cleanup_cancelled_execution'
                application.$: '$'
                AccountContext.$: '$.AccountContext'
            End: true

  # CloudWatch Log Group for Step Functions
  StateMachineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/stepfunctions/${ProjectName}-orchestration-${Environment}'
      RetentionInDays: 30

  # IAM Role for Step Functions with enhanced permissions
  StateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-statemachine-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: !Sub '${ProjectName}-statemachine-policy-${Environment}'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Lambda invocation permissions
              - Effect: Allow
                Action:
                  - 'lambda:InvokeFunction'
                Resource: !Ref OrchestrationLambdaArn
              
              # CloudWatch Logs permissions for Step Functions logging
              - Effect: Allow
                Action:
                  - 'logs:CreateLogDelivery'
                  - 'logs:GetLogDelivery'
                  - 'logs:UpdateLogDelivery'
                  - 'logs:DeleteLogDelivery'
                  - 'logs:ListLogDeliveries'
                  - 'logs:PutResourcePolicy'
                  - 'logs:DescribeResourcePolicies'
                  - 'logs:DescribeLogGroups'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
              
              # X-Ray tracing permissions (optional but recommended)
              - Effect: Allow
                Action:
                  - 'xray:PutTraceSegments'
                  - 'xray:PutTelemetryRecords'
                  - 'xray:GetSamplingRules'
                  - 'xray:GetSamplingTargets'
                Resource: '*'

Outputs:
  StateMachineArn:
    Description: 'ARN of the DRS Orchestration State Machine'
    Value: !Ref DRSOrchestrationStateMachine
    Export:
      Name: !Sub '${ProjectName}-state-machine-arn-${Environment}'
  
  StateMachineName:
    Description: 'Name of the DRS Orchestration State Machine'
    Value: !GetAtt DRSOrchestrationStateMachine.Name
    Export:
      Name: !Sub '${ProjectName}-state-machine-name-${Environment}'
  
  StateMachineLogGroupArn:
    Description: 'ARN of the Step Functions Log Group'
    Value: !GetAtt StateMachineLogGroup.Arn
    Export:
      Name: !Sub '${ProjectName}-state-machine-logs-arn-${Environment}'