AWSTemplateFormatVersion: '2010-09-09'
Description: |
  WAF Web ACL for CloudFront protection using AWS Managed Rules.
  Provides baseline security without IP restrictions.

# =============================================================================
# MINIMAL WAF CONFIGURATION
# =============================================================================
# Uses AWS Managed Rule Groups for common threat protection:
# - AWSManagedRulesCommonRuleSet: OWASP Top 10, common exploits
# - AWSManagedRulesKnownBadInputsRuleSet: Known malicious patterns
#
# No IP restrictions - allows all traffic while blocking known attacks.
# All rules in COUNT mode initially for safe rollout (change to BLOCK for enforcement).

Parameters:
  ProjectName:
    Type: String
    Description: Project name for resource naming

  Environment:
    Type: String
    Description: Environment name
    AllowedValues: [dev, test, prod]

Resources:
  # ===========================================================================
  # WAF WEB ACL
  # ===========================================================================
  # CloudFront-scoped WAF with AWS Managed Rules.
  # Default action ALLOW - only blocks known malicious requests.
  WebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub '${ProjectName}-waf-${Environment}'
      Description: !Sub 'WAF for ${ProjectName} CloudFront distribution'
      Scope: CLOUDFRONT
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Sub '${ProjectName}-waf-${Environment}'
      Rules:
        # -----------------------------------------------------------------
        # AWS Common Rule Set - OWASP Top 10 protection
        # -----------------------------------------------------------------
        - Name: AWSManagedRulesCommonRuleSet
          Priority: 1
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: !Sub '${ProjectName}-common-rules'
        # -----------------------------------------------------------------
        # AWS Known Bad Inputs - Log4j, known exploits
        # -----------------------------------------------------------------
        - Name: AWSManagedRulesKnownBadInputsRuleSet
          Priority: 2
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: !Sub '${ProjectName}-bad-inputs'
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

Outputs:
  WebACLArn:
    Description: WAF Web ACL ARN for CloudFront association
    Value: !GetAtt WebACL.Arn
    Export:
      Name: !Sub '${AWS::StackName}-WebACLArn'

  WebACLId:
    Description: WAF Web ACL ID
    Value: !Ref WebACL
    Export:
      Name: !Sub '${AWS::StackName}-WebACLId'
