"""
Frontend Builder Custom Resource
Builds React application and deploys to S3 with CloudFormation configuration injection
"""

import boto3
import json
import os
import shutil
import subprocess
import tempfile
from crhelper import CfnResource

s3 = boto3.client('s3')
cloudfront = boto3.client('cloudfront')
helper = CfnResource()


def inject_aws_config(frontend_dir, properties):
    """Generate aws-config.ts with CloudFormation outputs"""
    region = properties.get('Region', os.environ.get('AWS_REGION', 'us-west-2'))
    
    config_content = f"""// AWS Configuration - Auto-generated by CloudFormation Custom Resource
// DO NOT EDIT - This file is automatically generated during CloudFormation deployment

export const awsConfig = {{
  Auth: {{
    Cognito: {{
      region: '{region}',
      userPoolId: '{properties.get('UserPoolId', '')}',
      userPoolClientId: '{properties.get('UserPoolClientId', '')}',
      identityPoolId: '{properties.get('IdentityPoolId', '')}',
      loginWith: {{
        email: true
      }}
    }}
  }},
  API: {{
    REST: {{
      DRSOrchestration: {{
        endpoint: '{properties.get('ApiEndpoint', '')}',
        region: '{region}'
      }}
    }}
  }}
}};
"""
    
    config_path = os.path.join(frontend_dir, 'src', 'aws-config.ts')
    os.makedirs(os.path.dirname(config_path), exist_ok=True)
    
    with open(config_path, 'w') as f:
        f.write(config_content)
    
    print(f"Generated aws-config.ts with CloudFormation configuration")
    print(f"  Region: {region}")
    print(f"  User Pool ID: {properties.get('UserPoolId', '')}")
    print(f"  API Endpoint: {properties.get('ApiEndpoint', '')}")


def build_react_app(frontend_dir):
    """Build React application with npm"""
    print("Installing npm dependencies...")
    subprocess.run(
        ['npm', 'ci'],
        cwd=frontend_dir,
        check=True,
        capture_output=True,
        text=True
    )
    
    print("Building React application...")
    result = subprocess.run(
        ['npm', 'run', 'build'],
        cwd=frontend_dir,
        check=True,
        capture_output=True,
        text=True
    )
    
    print("Build output:")
    print(result.stdout)
    
    if result.stderr:
        print("Build warnings/errors:")
        print(result.stderr)
    
    dist_dir = os.path.join(frontend_dir, 'dist')
    if not os.path.exists(dist_dir):
        raise Exception(f"Build failed - dist directory not created at {dist_dir}")
    
    print(f"Build successful - dist directory created")
    return dist_dir


@helper.create
@helper.update
def create_or_update(event, context):
    """Build and deploy frontend"""
    properties = event['ResourceProperties']
    bucket_name = properties['BucketName']
    distribution_id = properties['DistributionId']
    
    print(f"Frontend Builder: Building and deploying to bucket: {bucket_name}")
    
    try:
        # Create temporary directory for build
        with tempfile.TemporaryDirectory() as temp_dir:
            frontend_dir = os.path.join(temp_dir, 'frontend')
            
            # Option 1: Copy frontend source from Lambda package
            # In Lambda, the frontend source would be packaged alongside this Lambda
            # For now, we'll check if frontend source is available
            
            lambda_frontend_path = '/var/task/frontend'
            if os.path.exists(lambda_frontend_path):
                print(f"Copying frontend source from Lambda package...")
                shutil.copytree(lambda_frontend_path, frontend_dir)
            else:
                # Option 2: Download from S3 if FrontendCodeBucket is specified
                frontend_bucket = properties.get('FrontendCodeBucket')
                frontend_key = properties.get('FrontendCodeKey')
                
                if frontend_bucket and frontend_key:
                    print(f"Downloading frontend source from s3://{frontend_bucket}/{frontend_key}")
                    zip_path = os.path.join(temp_dir, 'frontend.zip')
                    s3.download_file(frontend_bucket, frontend_key, zip_path)
                    
                    # Extract zip
                    import zipfile
                    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
                        zip_ref.extractall(frontend_dir)
                else:
                    # Fallback: Deploy placeholder HTML (current behavior)
                    print("WARNING: No frontend source available - deploying placeholder HTML")
                    return deploy_placeholder(bucket_name, distribution_id, properties, context)
            
            # Inject AWS configuration from CloudFormation outputs
            inject_aws_config(frontend_dir, properties)
            
            # Build React application
            dist_dir = build_react_app(frontend_dir)
            
            # Upload dist to S3
            print("Uploading build artifacts to S3...")
            uploaded_files = upload_to_s3(dist_dir, bucket_name)
            
            print(f"Upload complete. Total files: {len(uploaded_files)}")
            
            # Invalidate CloudFront cache
            print("Creating CloudFront invalidation...")
            invalidation_response = cloudfront.create_invalidation(
                DistributionId=distribution_id,
                InvalidationBatch={
                    'Paths': {
                        'Quantity': 1,
                        'Items': ['/*']
                    },
                    'CallerReference': str(context.request_id)
                }
            )
            
            invalidation_id = invalidation_response['Invalidation']['Id']
            print(f"CloudFront invalidation created: {invalidation_id}")
            
            print("Frontend deployment complete!")
            
            return {
                'BucketName': bucket_name,
                'FilesDeployed': len(uploaded_files),
                'InvalidationId': invalidation_id,
                'BuildType': 'react-production'
            }
            
    except subprocess.CalledProcessError as e:
        error_msg = f"Build command failed: {e.cmd}\nStdout: {e.stdout}\nStderr: {e.stderr}"
        print(error_msg)
        raise Exception(error_msg)
    except Exception as e:
        error_msg = f"Error deploying frontend: {str(e)}"
        print(error_msg)
        import traceback
        traceback.print_exc()
        raise Exception(error_msg)


def upload_to_s3(dist_dir, bucket_name):
    """Upload all files from dist directory to S3 with proper cache headers"""
    uploaded_files = []
    
    for root, dirs, files in os.walk(dist_dir):
        for file in files:
            local_path = os.path.join(root, file)
            relative_path = os.path.relpath(local_path, dist_dir)
            s3_key = relative_path.replace('\\', '/')
            
            # Determine content type
            content_type = get_content_type(file)
            
            # Set cache control based on file type
            # index.html: no cache (always fetch fresh)
            # Static assets: long-term cache (immutable with hashed filenames)
            cache_control = 'no-cache, no-store, must-revalidate' if file == 'index.html' else 'public, max-age=31536000, immutable'
            
            s3.upload_file(
                local_path,
                bucket_name,
                s3_key,
                ExtraArgs={
                    'ContentType': content_type,
                    'CacheControl': cache_control
                }
            )
            
            uploaded_files.append(s3_key)
            print(f"  Uploaded: {s3_key} ({content_type}, {cache_control})")
    
    return uploaded_files


def get_content_type(filename):
    """Determine content type from file extension"""
    ext = os.path.splitext(filename)[1].lower()
    
    content_types = {
        '.html': 'text/html',
        '.css': 'text/css',
        '.js': 'application/javascript',
        '.json': 'application/json',
        '.png': 'image/png',
        '.jpg': 'image/jpeg',
        '.jpeg': 'image/jpeg',
        '.gif': 'image/gif',
        '.svg': 'image/svg+xml',
        '.ico': 'image/x-icon',
        '.woff': 'font/woff',
        '.woff2': 'font/woff2',
        '.ttf': 'font/ttf',
        '.eot': 'application/vnd.ms-fontobject',
        '.txt': 'text/plain',
        '.xml': 'application/xml',
        '.pdf': 'application/pdf'
    }
    
    return content_types.get(ext, 'application/octet-stream')


def deploy_placeholder(bucket_name, distribution_id, properties, context):
    """Deploy placeholder HTML when React source is not available"""
    region = properties.get('Region', 'us-west-2')
    api_endpoint = properties.get('ApiEndpoint', '')
    user_pool_id = properties.get('UserPoolId', '')
    user_pool_client_id = properties.get('UserPoolClientId', '')
    identity_pool_id = properties.get('IdentityPoolId', '')
    
    print("Deploying placeholder HTML...")
    
    build_dir = '/tmp/frontend-placeholder'
    if os.path.exists(build_dir):
        shutil.rmtree(build_dir)
    os.makedirs(build_dir)
    
    # Create placeholder index.html
    index_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AWS DRS Orchestration</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f0f2f5;
        }}
        .container {{
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        h1 {{
            color: #232f3e;
            border-bottom: 3px solid #ff9900;
            padding-bottom: 10px;
        }}
        .status {{
            background: #fff3cd;
            border-left: 4px solid #ff9900;
            padding: 15px;
            margin: 20px 0;
        }}
        .config {{
            background: #f7f7f7;
            padding: 15px;
            border-radius: 4px;
            margin: 20px 0;
        }}
        .config-item {{
            margin: 10px 0;
            font-family: 'Courier New', monospace;
            font-size: 14px;
        }}
        .label {{ font-weight: bold; color: #232f3e; }}
        .value {{ color: #ff9900; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>AWS DRS Orchestration Platform</h1>
        
        <div class="status">
            <strong>⚠️ React App Not Yet Deployed</strong>
            <p>The CloudFormation Custom Resource Lambda needs the React frontend source code to build and deploy the full application.</p>
            <p><strong>To deploy the React app:</strong></p>
            <ol>
                <li>Package the frontend source code and upload to S3</li>
                <li>Update the CloudFormation stack with FrontendCodeBucket and FrontendCodeKey parameters</li>
                <li>The Lambda will automatically build and deploy the React app on stack update</li>
            </ol>
        </div>

        <div class="config">
            <h2>AWS Configuration (Available for React App)</h2>
            <div class="config-item"><span class="label">API Endpoint:</span> <span class="value">{api_endpoint or 'Not configured'}</span></div>
            <div class="config-item"><span class="label">Region:</span> <span class="value">{region}</span></div>
            <div class="config-item"><span class="label">User Pool ID:</span> <span class="value">{user_pool_id or 'Not configured'}</span></div>
            <div class="config-item"><span class="label">User Pool Client ID:</span> <span class="value">{user_pool_client_id or 'Not configured'}</span></div>
            <div class="config-item"><span class="label">Identity Pool ID:</span> <span class="value">{identity_pool_id or 'Not configured'}</span></div>
        </div>
    </div>
    
    <script>
        window.AWS_CONFIG = {{
            apiEndpoint: '{api_endpoint}',
            userPoolId: '{user_pool_id}',
            userPoolClientId: '{user_pool_client_id}',
            identityPoolId: '{identity_pool_id}',
            region: '{region}'
        }};
        console.log('AWS DRS Orchestration - Placeholder Page');
        console.log('AWS Configuration:', window.AWS_CONFIG);
    </script>
</body>
</html>"""
    
    with open(f'{build_dir}/index.html', 'w') as f:
        f.write(index_html)
    
    # Upload placeholder to S3
    uploaded_files = upload_to_s3(build_dir, bucket_name)
    
    # Invalidate CloudFront cache
    invalidation_response = cloudfront.create_invalidation(
        DistributionId=distribution_id,
        InvalidationBatch={
            'Paths': {'Quantity': 1, 'Items': ['/*']},
            'CallerReference': str(context.request_id)
        }
    )
    
    return {
        'BucketName': bucket_name,
        'FilesDeployed': len(uploaded_files),
        'InvalidationId': invalidation_response['Invalidation']['Id'],
        'BuildType': 'placeholder'
    }


@helper.delete
def delete(event, context):
    """No-op for Delete - S3 cleanup handles bucket emptying"""
    print("Frontend Builder: Delete event - S3 cleanup handles bucket emptying")
    return None


def lambda_handler(event, context):
    """Main handler for CloudFormation custom resource"""
    print(f"Frontend Builder: Received event: {json.dumps(event, default=str)}")
    helper(event, context)
