/**
 * AWS Configuration
 * 
 * This file checks for runtime-injected configuration (window.AWS_CONFIG)
 * which is generated by the CloudFormation deployment Lambda.
 * 
 * If window.AWS_CONFIG is not available (local development), it falls back
 * to placeholder values. Update these for local testing.
 */

// Extend Window interface to include AWS_CONFIG and configReady promise
declare global {
  interface Window {
    AWS_CONFIG?: {
      Auth: {
        Cognito: {
      region: string;
      userPoolId: string;
      userPoolClientId: string;
      identityPoolId?: string; // Optional - only needed for AWS service access
      loginWith: {
            email: boolean;
          };
        };
      };
      API: {
        REST: {
          DRSOrchestration: {
            endpoint: string;
            region: string;
          };
        };
      };
    };
    configReady?: Promise<void>;
  }
}

// Default configuration for local development (update these as needed)
const defaultConfig = {
  Auth: {
    Cognito: {
      region: 'us-east-1',
      userPoolId: 'UPDATE_ME',
      userPoolClientId: 'UPDATE_ME',
      // identityPoolId not needed for basic Cognito auth
      loginWith: {
        email: true
      }
    }
  },
  API: {
    REST: {
      DRSOrchestration: {
        endpoint: 'UPDATE_ME',
        region: 'us-east-1'
      }
    }
  }
};

// Function to get config - checks window.AWS_CONFIG dynamically
function getAwsConfig() {
  if (window.AWS_CONFIG) {
    return window.AWS_CONFIG;
  }
  return defaultConfig;
}

// Export as getter property so it always gets fresh value
export const awsConfig = new Proxy({} as typeof defaultConfig, {
  get(_target, prop) {
    const config = getAwsConfig();
    return config[prop as keyof typeof config];
  }
});

// Log config status only in development mode
if (import.meta.env.DEV) {
  if (window.AWS_CONFIG) {
    console.log('✅ AWS Config loaded from CloudFormation');
  } else {
    console.log('⚠️ Using default AWS config (local dev)');
  }
}
