/**
 * AWS Configuration
 * 
 * This file checks for runtime-injected configuration (window.AWS_CONFIG)
 * which is generated by the CloudFormation deployment Lambda.
 * 
 * If window.AWS_CONFIG is not available (local development), it falls back
 * to placeholder values. Update these for local testing.
 */

// Extend Window interface to include AWS_CONFIG and configReady promise
declare global {
  interface Window {
    AWS_CONFIG?: {
      Auth: {
        Cognito: {
      region: string;
      userPoolId: string;
      userPoolClientId: string;
      identityPoolId?: string; // Optional - only needed for AWS service access
      loginWith: {
            email: boolean;
          };
        };
      };
      API: {
        REST: {
          DRSOrchestration: {
            endpoint: string;
            region: string;
          };
        };
      };
    };
    configReady?: Promise<void>;
  }
}

// Default configuration for local development (update these as needed)
const defaultConfig = {
  Auth: {
    Cognito: {
      region: 'us-east-1',
      userPoolId: 'UPDATE_ME',
      userPoolClientId: 'UPDATE_ME',
      // identityPoolId not needed for basic Cognito auth
      loginWith: {
        email: true
      }
    }
  },
  API: {
    REST: {
      DRSOrchestration: {
        endpoint: 'UPDATE_ME',
        region: 'us-east-1'
      }
    }
  }
};

// Function to get config - checks window.AWS_CONFIG dynamically
function getAwsConfig() {
  if (window.AWS_CONFIG) {
    // Validate and sanitize the region to prevent corruption
    const config = { ...window.AWS_CONFIG };
    if (config.Auth?.Cognito?.region) {
      // Ensure region is valid - if corrupted, fall back to us-east-1
      const region = config.Auth.Cognito.region;
      if (!region.match(/^[a-z]{2}-[a-z]+-\d+$/)) {
        console.warn(`⚠️ Invalid region detected: "${region}", falling back to us-east-1`);
        config.Auth.Cognito.region = 'us-east-1';
      }
    }
    return config;
  }
  return defaultConfig;
}

// Export the actual config object (not a proxy to avoid issues)
export const awsConfig = getAwsConfig();

// Log config status only in development mode
// Development mode logging removed for production
