/**
 * AWS Configuration
 * 
 * This file checks for runtime-injected configuration (window.AWS_CONFIG)
 * which is generated by the CloudFormation deployment Lambda.
 * 
 * If window.AWS_CONFIG is not available (local development), it falls back
 * to placeholder values. Update these for local testing.
 */

// Extend Window interface to include AWS_CONFIG
declare global {
  interface Window {
    AWS_CONFIG?: {
      Auth: {
        Cognito: {
          region: string;
          userPoolId: string;
          userPoolClientId: string;
          identityPoolId: string;
          loginWith: {
            email: boolean;
          };
        };
      };
      API: {
        REST: {
          DRSOrchestration: {
            endpoint: string;
            region: string;
          };
        };
      };
    };
  }
}

// Default configuration for local development (update these as needed)
const defaultConfig = {
  Auth: {
    Cognito: {
      region: 'us-east-1',
      userPoolId: 'UPDATE_ME',
      userPoolClientId: 'UPDATE_ME',
      identityPoolId: 'UPDATE_ME',
      loginWith: {
        email: true
      }
    }
  },
  API: {
    REST: {
      DRSOrchestration: {
        endpoint: 'UPDATE_ME',
        region: 'us-east-1'
      }
    }
  }
};

// Use runtime-injected config if available, otherwise use defaults
export const awsConfig = window.AWS_CONFIG || defaultConfig;

// Log which config is being used (helps with debugging)
if (window.AWS_CONFIG) {
  console.log('Using CloudFormation-injected AWS configuration');
  console.log('API Endpoint:', window.AWS_CONFIG.API.REST.DRSOrchestration.endpoint);
  console.log('User Pool ID:', window.AWS_CONFIG.Auth.Cognito.userPoolId);
} else {
  console.warn('Using default AWS configuration - CloudFormation config not found');
  console.warn('This is expected during local development');
}
