#!/usr/bin/env node

/**
 * AWS Configuration Injection Script
 * 
 * This script updates the frontend/src/aws-config.ts file with actual
 * AWS values from CloudFormation stack outputs before building.
 * 
 * Usage:
 *   node inject-config.js --region REGION --user-pool-id POOL_ID ...
 */

const fs = require('fs');
const path = require('path');

// Parse command line arguments
function parseArgs() {
  const args = process.argv.slice(2);
  const config = {
    region: 'us-west-2',
    userPoolId: '',
    userPoolClientId: '',
    identityPoolId: '',
    apiEndpoint: '',
    environment: 'prod'
  };

  for (let i = 0; i < args.length; i += 2) {
    const key = args[i].replace(/^--/, '');
    const value = args[i + 1];
    
    switch (key) {
      case 'region':
        config.region = value;
        break;
      case 'user-pool-id':
        config.userPoolId = value;
        break;
      case 'user-pool-client-id':
        config.userPoolClientId = value;
        break;
      case 'identity-pool-id':
        config.identityPoolId = value;
        break;
      case 'api-endpoint':
        config.apiEndpoint = value;
        break;
      case 'environment':
        config.environment = value;
        break;
    }
  }

  return config;
}

// Validate configuration
function validateConfig(config) {
  const errors = [];

  if (!config.region) {
    errors.push('Missing required parameter: --region');
  }
  if (!config.userPoolId || config.userPoolId === 'null') {
    errors.push('Missing required parameter: --user-pool-id');
  }
  if (!config.userPoolClientId || config.userPoolClientId === 'null') {
    errors.push('Missing required parameter: --user-pool-client-id');
  }
  if (!config.identityPoolId || config.identityPoolId === 'null') {
    errors.push('Missing required parameter: --identity-pool-id');
  }
  if (!config.apiEndpoint || config.apiEndpoint === 'null') {
    errors.push('Missing required parameter: --api-endpoint');
  }

  if (errors.length > 0) {
    console.error('\n❌ Configuration validation failed:\n');
    errors.forEach(error => console.error(`  - ${error}`));
    console.error('\nPlease ensure CloudFormation stack has all required outputs.\n');
    process.exit(1);
  }
}

// Generate aws-config.ts content
function generateConfig(config) {
  const template = `/**
 * AWS Amplify Configuration
 * 
 * This file was automatically generated by scripts/inject-config.js
 * Environment: ${config.environment}
 * Generated: ${new Date().toISOString()}
 * 
 * DO NOT EDIT THIS FILE MANUALLY IN PRODUCTION
 * Run the deployment script to regenerate with correct values
 */

export const awsConfig = {
  Auth: {
    Cognito: {
      // AWS Region where resources are deployed
      region: '${config.region}',
      
      // Cognito User Pool ID (from CloudFormation output: UserPoolId)
      userPoolId: '${config.userPoolId}',
      
      // Cognito User Pool App Client ID (from CloudFormation output: UserPoolClientId)
      userPoolClientId: '${config.userPoolClientId}',
      
      // Cognito Identity Pool ID (from CloudFormation output: IdentityPoolId)
      identityPoolId: '${config.identityPoolId}',
      
      // Sign-in options
      loginWith: {
        email: true,
      },
    }
  },
  
  API: {
    REST: {
      DRSOrchestration: {
        // API Gateway endpoint (from CloudFormation output: ApiEndpoint)
        endpoint: '${config.apiEndpoint}',
        region: '${config.region}',
      }
    }
  }
};

// Export region for convenience
export const AWS_REGION = awsConfig.Auth.Cognito.region;

// Export API name for convenience
export const API_NAME = 'DRSOrchestration';
`;

  return template;
}

// Main execution
function main() {
  console.log('\n🔧 AWS Configuration Injection\n');

  // Parse arguments
  const config = parseArgs();
  
  console.log(`Environment: ${config.environment}`);
  console.log(`Region: ${config.region}`);
  console.log(`User Pool ID: ${config.userPoolId}`);
  console.log(`API Endpoint: ${config.apiEndpoint}\n`);

  // Validate configuration
  validateConfig(config);

  // Determine file path
  const scriptDir = __dirname;
  const projectRoot = path.dirname(scriptDir);
  const configPath = path.join(projectRoot, 'frontend', 'src', 'aws-config.ts');

  console.log(`Target file: ${configPath}`);

  // Check if file exists
  if (!fs.existsSync(configPath)) {
    console.error(`\n❌ Error: Configuration file not found: ${configPath}\n`);
    process.exit(1);
  }

  // Create backup of original file
  const backupPath = configPath + '.backup';
  try {
    fs.copyFileSync(configPath, backupPath);
    console.log(`✅ Created backup: ${backupPath}`);
  } catch (error) {
    console.error(`\n❌ Error creating backup: ${error.message}\n`);
    process.exit(1);
  }

  // Generate new configuration
  const newContent = generateConfig(config);

  // Write new configuration
  try {
    fs.writeFileSync(configPath, newContent, 'utf8');
    console.log(`✅ Configuration injected successfully`);
    console.log(`\n📝 Updated aws-config.ts with ${config.environment} environment values\n`);
  } catch (error) {
    console.error(`\n❌ Error writing configuration: ${error.message}\n`);
    // Restore backup on error
    try {
      fs.copyFileSync(backupPath, configPath);
      console.log('✅ Restored from backup');
    } catch (restoreError) {
      console.error(`❌ Error restoring backup: ${restoreError.message}`);
    }
    process.exit(1);
  }

  // Display summary
  console.log('Configuration Details:');
  console.log('=====================');
  console.log(`Region:              ${config.region}`);
  console.log(`User Pool:           ${config.userPoolId}`);
  console.log(`Client ID:           ${config.userPoolClientId}`);
  console.log(`Identity Pool:       ${config.identityPoolId}`);
  console.log(`API Endpoint:        ${config.apiEndpoint}`);
  console.log(`Environment:         ${config.environment}`);
  console.log('');

  process.exit(0);
}

// Run main function
main();
